- Braintree/UI/Views/BTUIViewUtil.m
Repaired BTUIViewUtil.m so the card types and the return values now
properly match.
> BTUIViewUtil.m Repair

- Braintree/UI/Models/BTUICardType.h
- Braintree/UI/Models/BTUICardType.m
- Braintree/UI/Views/Form Fields/BTUICardNumberField.m
- Specs/Braintree-UI-Specs/BTUICardTypeSpec.m
Don't auto-advance if card type might allow for longer card numbers.
This addresses #120
> Fix Maestro card number limit

- Braintree/API/Networking/BTURLUtils.m
- Braintree/API/Offline Mode/BTOfflineModeURLProtocol.m
- Braintree/Braintree.h
- Braintree/Coinbase/Vendor/BTCoinbaseOAuth.m
- Braintree/Drop-In/BTDropInErrorAlert.m
- Braintree/Drop-In/BTDropInViewController.m
- Braintree/UI/Models/BTUIUtil.h
- Braintree/UI/Models/BTUIUtil.m
- Braintree/UI/Views/Forms/BTUICardFormView.m
Code review:
```
CFURLCreateStringByAddingPercentEscapes() ->
-stringByAddingPercentEncodingWithAllowedCharacters:
-stringByReplacingPercentEscapesUsingEncoding: ->
-stringByRemovingPercentEncoding
UIAlertView -> UIAlertController
```
> Replace deprecated APIs

- BraintreeCard/BTCard.m
- BraintreeCard/Public/BTCard.h
- UnitTests/BTCard_Internal_Tests.m
Added new properties to BTCard:
- streetAddress
- locality
- region
- countryName
- countryCodeAlpha2
> Card additional parameters

- BraintreeUI/Views/Custom Views/BTUIFormField.m
> Declare as static variables

- BraintreePayPal/PayPalOneTouch/Configuration/PPOTConfiguration.h
- BraintreePayPal/PayPalOneTouch/Configuration/PPOTConfiguration.m
- BraintreePayPal/PayPalOneTouch/Models/PPOTRequest.m
- BraintreePayPal/PayPalOneTouch/Public/PPOTRequest.h
- BraintreePayPal/PayPalUtils/Public/PPOTMacros.h
> #420 use "#ifdef DEBUG" instead of "if"

- Braintree.xcodeproj/project.pbxproj
- BraintreePayPal/PayPalDataCollector/PPDataCollector.m
- BraintreePayPal/PayPalDataCollector/Public/PPDataCollector.h
- UnitTests/PayPalOneTouch/PPDataCollectorTest.m
Adding a function to PPDataCollector to get PayPalDeviceInfo
>  Adding collectPayPalDeviceInfo to PPDataCollector

- CHANGELOG.md
- Demo/Application/Features/Ideal/BraintreeDemoIdealViewController.m
- Demo/UI Tests/PayPal UI Tests/PayPal_BillingAgreement_UITests.swift
- Demo/UI Tests/PayPal UI Tests/PayPal_OneTimePayment_UITests.swift
- Sources/BraintreePaymentFlow/BTLocalPaymentRequest.m
- Sources/BraintreePaymentFlow/Public/BraintreePaymentFlow/BTLocalPaymentRequest.h
- UnitTests/BraintreePaymentFlowTests/BTLocalPayment_Tests.swift
- Add `paymentTypeCountryCode` to `BTLocalPaymentRequest`
- @sestevens
> Add paymentTypeCountryCode to BTLocalPaymentRequest

- .github/workflows/build.yml
- SampleApps/SPMTest/SPMTest.xcodeproj/project.pbxproj
- Add check for Swift Package Manager integrations to Build workflow on GitHub Actions
- Update SPMTest to use `https://github.com/braintree/braintree_ios.git` instead of `git@github.com:braintree/braintree_ios.git` to avoid SSH error (see [this SO post](https://stackoverflow.com/a/62296401))
- @sestevens
> Add SPM check to Build workflow on GitHub Actions

- CHANGELOG.md
- Sources/BraintreeThreeDSecure/BTPaymentFlowDriver+ThreeDSecure.m
- Sources/BraintreeThreeDSecure/Public/BraintreeThreeDSecure/BTThreeDSecureRequest.h
- UnitTests/BraintreeThreeDSecureTests/BTPaymentFlowDriver+ThreeDSecure_Tests.swift
- Add `dataOnlyRequested` to `BTThreeDSecureRequest`
- @sestevens
> Add dataOnlyRequested to BTThreeDSecureRequest

- Sources/BraintreePayPal/BTPayPalDriver.m
- Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalAccountNonce.h
- Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalCheckoutRequest.h
- Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalRequest.h
- Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalVaultRequest.h
- Update doc strings for PayPal flow
- @sestevens
> Update doc strings for PayPal flow

- DEVELOPMENT.md
- README.md
- V5_MIGRATION.md
- Add table of contents to migration guide and alphabetize sections
- Remove references to v5 beta from migration guide and README
- Update SDK status table in README
- Update rake task for integration tests in DEVELOPMENT.md
- @sestevens 
- @hollabaq86
> Update README and Migration Guide for v5 Release

- .github/ISSUE_TEMPLATE/bug_report.md
- Update issue template for SPM
> Update Issue template for SPM

- Braintree.xcodeproj/project.pbxproj
- CHANGELOG.md
- Sources/BraintreePaymentFlow/BTLocalPaymentRequest.m
- Sources/BraintreePaymentFlow/Public/BraintreePaymentFlow/BTLocalPaymentRequest.h
- UnitTests/BraintreePaymentFlowTests/BTLocalPaymentRequest_Tests.swift
- UnitTests/BraintreePaymentFlowTests/MockPaymentFlowDriverDelegate.swift
- Add `bic` to `BTLocalPaymentRequest`
- @sestevens
> Add bic to BTLocalPaymentRequest

- .github/ISSUE_TEMPLATE/bug_report.md
> Update Issue Template

- Sources/BraintreePayPalNative/Public/BraintreePayPalNative/BTPayPalNativeClient.swift
- Hide cancel modal
- @sestevens 
- @sshropshire
> Hide Cancel Modal

- SampleApps/SPMTest/SPMTest.xcodeproj/project.pbxproj
- Reset SPMTest app to reference master
- Looks like this change from a previous PR accidentally made it into master
@scannillo
> Reset SPMTest app to reference master

- Sources/BraintreeVenmo/BTVenmoAccountNonce.m
- Sources/BraintreeVenmo/BTVenmoDriver.m
- Sources/BraintreeVenmo/Public/BraintreeVenmo/BTVenmoAccountNonce.h
- UnitTests/BraintreeVenmoTests/BTVenmoAccountNonce_Tests.swift
- Add email, externalId, firstName, lastName, phoneNumber to BTVenmoAccountNonce
These fields will only be available in certain situations.
**Blocked for e2e testing**
- @demerino
> [BLOCKED] PwV - Enrich Consumer Data

- CHANGELOG.md
- Package.swift
- Add explicit package dependencies (fix for #735)
- @sarahkoop @Epreuve @jaxdesmarais
> Update Package Dependencies

- CHANGELOG.md
- Demo/Application/Features/Fraud Protection - BTDataCollector/BraintreeDemoBTDataCollectorViewController.m
- Sources/BraintreeDataCollector/BTDataCollector.m
- Sources/BraintreePayPal/BTPayPalDriver.m
- Sources/BraintreePaymentFlow/BTLocalPaymentRequest.m
- Sources/PayPalDataCollector/Public/PayPalDataCollector/PPDataCollector.swift
- UnitTests/PayPalDataCollectorTests/PPDataCollector_Tests.swift
- Allow passing isSandbox bool for data collection in `clientMetadataID` and `collectPayPalDeviceData` functions
- @sarahkoop @jaxdesmarais
> Add isSandbox bool to PPDataCollector Functions

- .github/workflows/build.yml
- Braintree.xcodeproj/project.pbxproj
- Demo/Demo.xcodeproj/project.pbxproj
- SampleApps/CarthageTest/Cartfile
- SampleApps/SPMTest/SPMTest.xcodeproj/project.pbxproj
The below were done to allow CI to pass temporarily but now that the sepa-feature branch has been merged we can point everything back to main as expected:
- Point carthage sample app back to main since the sepa-feature has been merged into main - we no longer need to point to our feature branch for the sample app builds
- Point SPM sample app back to main since the sepa-feature has been merged into main - we no longer need to point to our feature branch for the sample app builds
> Cleanup Sample Apps and Workflows Post SEPA/NXO Feature Merge

- .github/workflows/build.yml
> Test forward slashes in branch names for sed

- Sources/BraintreeCoreSwift/BTHTTP.swift
- Sources/BraintreeCoreSwift/BTHTTPErrorCode.swift
- Replaced authorizationFingerprint and tokenizationKey with a private enum and associated values.
-
> Create ClientAuthorization enum

- .github/workflows/build.yml
- Update build.yml to remove derived data 
- @scannillo @mattwylder @jaxdesmarais
> Update build.yml to Remove Derived Data

- Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutClient.swift
- Sources/BraintreePayPalNativeCheckout/BTPayPalNativeOrderCreationClient.swift
- Sources/BraintreePayPalNativeCheckout/BTPayPalNativeTokenizationClient.swift
- UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeCheckoutClient_Tests.swift
- UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeOrderCreationClient_Tests.swift
- UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeTokenizationClient_Tests.swift
- add analytics events for PayPal Native Checkout
- add tests for analytics
> Add Analytics for PayPal Native Checkout

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- This PR adds "Developer Support" as a 3rd option to our issues workflow (alongside the existing "Bug Report" and "Feature Request" options)
This will look something like this, and the button will take them directly to our support link.
@scannillo
> Add Support contact as button to issue workflow

- Demo/Demo.xcodeproj/project.pbxproj
- Embed and Codesign Magnes Framework
- Add signing team to InAppSettingsKit
> Fixed build issues on physical device

- Demo/Application/Features/SEPA Direct Debit/BraintreeDemoSEPADirectDebitViewController.swift
- Update the IBAN used in our Demo app for SEPA Direct Debit - the one in there has been used too many times and is now invalid so we need to swap it out (again). We should have a better testing story for this but alas. 😢 
> Update SEPA Direct Debit IBAN in Demo App

- Braintree.xcodeproj/project.pbxproj
- CHANGELOG.md
- Demo/Application/Features/SEPA Direct Debit/BraintreeDemoSEPADirectDebitViewController.swift
- Sources/BraintreeSEPADirectDebit/BTSEPADirectDebitTestHelper.swift
- So we don't have to change the IBANs all the time added a test helper class to randomly generate french IBANs
- Resources: [Gateway helper functions for IBAN generation](https://github.braintreeps.com/braintree/gateway/pull/24498/files) and a [article about calculating values for IBAN generation](https://community.appway.com/screen/kb/article/generating-and-validating-an-iban-1683400256881)
- Opened a new PR because the old one #910 was off of the `next-major-version` branch and not `5.x`
> Add Valid IBAN Generator Test Helper

- Braintree.xcodeproj/project.pbxproj
- CHANGELOG.md
- Demo/Application/Features/SEPA Direct Debit/BTSEPADirectDebitTestHelper.swift
- Demo/Demo.xcodeproj/project.pbxproj
- Per our convo in stand, we decided to move `BTSEPADirectDebitTestHelper` into the Demo app! This PR does that. 😄 
- ~[ ] Added a changelog entry~ removed the changelog since it's in the demo app now
> Move `BTSEPADirectDebitTestHelper` into the Demo App

- Braintree.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- SampleApps/CarthageTest/Cartfile
- SampleApps/SPMTest/SPMTest.xcodeproj/project.pbxproj
- Update branch for `CarthageTest` and `SPMTest`
- During the `next-major-version` work we pointed these to that branch for CI purposes, now that that branch is merged in we need to update these to point back to the main branch again
> Update Branch for `CarthageTest` and `SPMTest`

- CHANGELOG.md
- Demo/Application/Features/PayPal - Checkout/BraintreeDemoPayPalCheckoutViewController.swift
- Demo/Application/Features/PayPal - Pay Later/BraintreeDemoPayPalPayLaterViewController.swift
- Demo/Application/Features/PayPal - Vault/BraintreeDemoPayPalVaultViewController.swift
- Demo/Application/Features/Preferred Payment Methods/BraintreeDemoPreferredPaymentMethodsViewController.swift
- Demo/Application/Features/SEPA Direct Debit/BraintreeDemoSEPADirectDebitViewController.swift
- Sources/BraintreePayPal/BTPayPalClient.swift
- Sources/BraintreePayPal/BTPayPalRequest.swift
- Sources/BraintreeSEPADirectDebit/BTSEPADirectDebitClient.swift
- UnitTests/BraintreeSEPADirectDebitTests/BTSEPADirectDebitClient_Tests.swift
- V6_MIGRATION.md
- Removed `BTPayPalRequest.activeWindow`
- Removed merchant conformance to `ASWebAuthenticationPresentationContextProviding`
- Removed the `context` parameter from the `BTSEPADirectDebitClient.tokenize` method
- Moved `BTPayPalClient` and `BTSEPADirectDebitClient` conformance to `ASWebAuthenticationPresentationContextProviding` into an extension
- Updated demo app with the above changes
The above changes have been tested in the demo app to confirm everything is still working as it was previously 🚀 
> Update ASWebAuthenticationSession Usage

- CHANGELOG.md
- Demo/Application/Features/3D Secure/BraintreeDemoThreeDSecurePaymentFlowViewController.m
- Sources/BraintreeThreeDSecure/BTPaymentFlowDriver+ThreeDSecure.m
- Sources/BraintreeThreeDSecure/BTThreeDSecureRequest.m
- Sources/BraintreeThreeDSecure/BTThreeDSecureRequest_Internal.h
- Sources/BraintreeThreeDSecure/Public/BraintreeThreeDSecure/BTThreeDSecureRequest.h
- UnitTests/BraintreeThreeDSecureTests/BTThreeDSecureRequest_Tests.swift
- Add `requestedExemptionType` to `BTThreeDSecureRequest`
> Add `requestedExemptionType` to `BTThreeDSecureRequest`

- .gitignore
- Add `Braintree.xcworkspace/xcshareddata/swiftpm/` to `.gitignore`
> Added SPM directory to .gitignore

- Braintree.xcodeproj/project.pbxproj
- Sources/BraintreeApplePay/BTApplePayAnalytics.swift
- Sources/BraintreeApplePay/BTApplePayClient.swift
- Sources/BraintreeCore/BTAnalyticsService.swift
- UnitTests/BraintreeApplePayTests/BTApplePayAnalytics_Tests.swift
- UnitTests/BraintreeApplePayTests/BTApplePay_Tests.swift
These changes are going into the fpti-feature branch. Which will get merged in once we audit all modules and make the switch to the FPTI endpoints
- Update ApplePay analytics events to prepare for switch to FPTI
- Update tests
- @scannillo @KunJeongPark @jaxdesmarais
> Audit Apple Pay Analytics Events

- Braintree.xcodeproj/project.pbxproj
- Sources/BraintreeAmericanExpress/BTAmericanExpressAnalytics.swift
- Sources/BraintreeAmericanExpress/BTAmericanExpressClient.swift
- Sources/BraintreeCore/BTAnalyticsService.swift
- UnitTests/BraintreeAmericanExpressTests/BTAmericanExpressAnalytics_Tests.swift
- UnitTests/BraintreeAmericanExpressTests/BTAmericanExpressClient_Tests.swift
These changes are going into the `fpti-feature` branch. Which will get merged in once we audit all modules and make the switch to the FPTI endpoints
- Update AmericanExpress analytics events to prepare for switch to FPTI
- Update tests
- @scannillo @KunJeongPark @jaxdesmarais
> Audit American Express Analytics Events

- Braintree.xcodeproj/project.pbxproj
- Sources/BraintreeCard/BTCardAnalytics.h
- Sources/BraintreeCard/BTCardAnalytics.m
- Sources/BraintreeCard/BTCardAnalytics_Internal.h
- Sources/BraintreeCard/BTCardClient.m
- UnitTests/BraintreeCardTests/BTCardAnalytics_Tests.swift
- UnitTests/BraintreeCardTests/BTCardClient_Tests.swift
- UnitTests/BraintreeCardTests/BTCard_Tests.swift
- UnitTests/BraintreeCardTests/BraintreeCardTests-Bridging-Header.h
These changes are going into the fpti-feature branch. Which will get merged in once we audit all modules and make the switch to the FPTI endpoints
-Update Card analytics events to prepare for switch to FPTI
-Update tests
- @KunJeongPark @jaxdesmarais @scannillo
> Audit Card Analytics Events

- README.md
- See PR description for - https://github.com/braintree/braintree_ios/pull/972
@scannillo
> [v5] Add M1 CocoaPods workaround to README

- Sources/BraintreeCore/Analytics/BTAnalyticsService.swift
- Sources/BraintreeCore/Analytics/FPTIBatchData.swift
- Sources/BraintreeCore/BTConfiguration+Core.swift
- Sources/BraintreeCore/BTConfiguration.swift
- UnitTests/BraintreeCoreTests/Analytics/BTAnalyticsService_Tests.swift
- Pull the merchant ID from the config for analytics
> Merchant ID for Analytics

- Sources/BraintreeThreeDSecure/BTThreeDSecureClient.swift
- UnitTests/BraintreeThreeDSecureTests/BTThreeDSecureClient_Tests.swift
- Add else block for if we get 3DSv1 back in the lookup response
- Add new unit test
- @scannillo @jaxdesmarais
> Check For 3DSv1 in Lookup

- Braintree.xcodeproj/project.pbxproj
- IntegrationTests/BraintreeCard_IntegrationTests.m
- Podfile
- Podfile.lock
- UnitTests/BraintreeCoreTests/BTHTTP_Tests.swift
- Remove unused `Expecta` test dependency
- Prepping for moving away from CocoaPods for our project setup, and over to SPM
@scannillo
> Remove Expecta dependency

- CHANGELOG.md
- SDK_ERROR_CODES.md
- Sources/BraintreeApplePay/BTApplePayError.swift
- Sources/BraintreeCard/BTCardError.swift
- Sources/BraintreeCore/BTClientTokenError.swift
- Sources/BraintreeCore/BTJSONError.swift
- Sources/BraintreeDataCollector/BTDataCollectorError.swift
- Sources/BraintreeVenmo/BTVenmoError.swift
JIRA DTBTSDK-2788
- Add `SDK_ERROR_CODES.md` file with consolidated list of all error cases & codes thrown from each feature module
- Remove mention of error updates in each V6-beta CHANGELOG notes
- Updating error case docstrings if missing code value 
@scannillo @jaxdesmarais
> Add `SDK_ERROR_CODES.md` file

- SDK_ERROR_CODES.md
- Sources/BraintreeVenmo/BTVenmoError.swift
- Add missing BTVenmoError’s to SDK_ERROR_CODES
> Add missing BTVenmoError’s to SDK_ERROR_CODES

- CHANGELOG.md
- Add note to link all betas in GA unreleased CHANGELOG
> Finalize Changelog

- CHANGELOG.md
- Sources/BraintreeVenmo/BTVenmoClient.swift
- Sources/BraintreeVenmo/BTVenmoRequest.swift
- UnitTests/BraintreeVenmoTests/BTVenmoClient_Tests.swift
- Fix bug where tokenizations failed by only adding transaction details dictionary when present (fixes #1074)
- Fix typo in docstrings
- @scannillo @jaxdesmarais
> Fix Venmo Dictionary Construction

- CHANGELOG.md
- Add recently released 5.x CHANGELOG entry
> Update CHANGELOG.md with 5.x Release

- Demo/Application/Features/3D Secure/BraintreeDemoThreeDSecurePaymentFlowViewController.swift
- Demo/Application/Features/Amex/BraintreeDemoAmexViewController.swift
- Demo/Application/Features/CardHelpers.swift
- Demo/Application/Features/Credit Card Tokenization/BraintreeDemoCardTokenizationViewController.swift
- Demo/Demo.xcodeproj/project.pbxproj
- Add `CardHelpers` class for logic duplicated across View Controllers to generate future dates and cards
> Demo App - Add `CardHelpers` for Shared Logic

- Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
- UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClient_Tests.swift
- Product decision wants us to remove the app installed checks and always call the EligiblePayments API
@scannillo
> [ShopperInsights] Remove app installed checks

- Demo/Application/Features/ShopperInsightsViewController.swift
- Add merchant-triggered analytic events to ShopperInsights Demo ViewController
@scannillo
> [ShopperInsights] Add merchant-triggered analytic events to Demo

- Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
- Update the docstrings for ShopperInsightsClient.getRecommendedPaymentMethods() to call out
> DocStrings on Country Restrictions

- README.md
- Changed Xcode version requirements in README file as per Apple guidelines https://developer.apple.com/news/?id=khzvxn8a
- @stechiu
> Updated README.md with Xcode version bump

- CHANGELOG.md
- Sources/BraintreeCore/Analytics/BTAnalyticsService.swift
- Sources/BraintreeCore/Analytics/FPTIBatchData.swift
- Sources/BraintreeCore/BTAPIClient.swift
- Sources/BraintreePayPal/BTPayPalAnalytics.swift
- Sources/BraintreePayPal/BTPayPalApprovalURLParser.swift
- Sources/BraintreePayPal/BTPayPalClient.swift
- UnitTests/BraintreeCoreTests/Analytics/FPTIBatchData_Tests.swift
- UnitTests/BraintreeCoreTests/Analytics/FakeAnalyticsService.swift
- UnitTests/BraintreePayPalTests/BTPayPalAnalytics_Tests.swift
- UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift
- UnitTests/BraintreeTestShared/MockAPIClient.swift
- Send `link_type` and `paypal_installed` in `event_params` when available to FPTI for the PayPal flow
- Verified via FPTI Explorer we are seeing these events
> [QL] App Switch Analytics

- Braintree.xcodeproj/project.pbxproj
- Sources/BraintreePayPal/BTPayPalApprovalURLParser.swift
- UnitTests/BraintreePayPalTests/BTPayPalApprovalURLParser_Tests.swift
- Add `BTPayPalApprovalURLParser_Tests` and test cases
> [QL] Add `BTPayPalApprovalURLParser_Tests`

- Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
- Sources/BraintreeShopperInsights/BTShopperInsightsRequest.swift
- Sources/BraintreeShopperInsights/BTShopperInsightsResult.swift
- Update `BTShopperInsightsClient` class and `getRecommendedPaymentMethods` method from `Note` to `Warning`
- @agedd
> Update Beta Docstrings to `Warning` For Shopper-Insights Feature

- Sources/BraintreePayPalMessaging/BTPayPalMessagingColor.swift
- Sources/BraintreePayPalMessaging/BTPayPalMessagingDelegate.swift
- Sources/BraintreePayPalMessaging/BTPayPalMessagingError.swift
- Sources/BraintreePayPalMessaging/BTPayPalMessagingLogoType.swift
- Sources/BraintreePayPalMessaging/BTPayPalMessagingOfferType.swift
- Sources/BraintreePayPalMessaging/BTPayPalMessagingPageType.swift
- Sources/BraintreePayPalMessaging/BTPayPalMessagingRequest.swift
- Sources/BraintreePayPalMessaging/BTPayPalMessagingTextAlignment.swift
- Sources/BraintreePayPalMessaging/BTPayPalMessagingView.swift
- Change comments in public functions and objects from note to warning about beta status
- @KunJeongPark @jwarmkessel @saperi22
> PayPal Messaging Note in comments to Warning

- Demo/Application/Features/PayPalWebCheckoutViewController.swift
- Add ability to test app switch in stage, production, and sandbox
- Add "App Switch Stage" toggle for testing in the staging environment
- Sandbox and Production are being rolled out today/tomorrow and we want the ability to continue to test stage as well as Sandbox/Production concurrently
> [QL] Enable App Switch Sandbox/Production Testing

- Braintree.podspec
- Braintree.xcodeproj/project.pbxproj
- Cartfile
- Package.swift
- Update PayPalMessages dependency to 1.0.0
- @jwarmkessel 
- @KunJeongPark 
- @saperi22
> Update PayPalMessages dependency to 1.0.0

- Braintree.podspec
- Braintree.xcodeproj/project.pbxproj
- Package.swift
- Sources/BraintreePayPalMessaging/PrivacyInfo.xcprivacy
- Add Privacy Manifest for PayPal Messaging Module
> Paypal Messaging Privacy Manifest

- CHANGELOG.md
- Sources/BraintreeCore/Analytics/BTAnalyticsService.swift
- Sources/BraintreeCore/BTAPIClient.swift
- Sources/BraintreePayPal/BTPayPalClient.swift
- Sources/BraintreeVenmo/BTVenmoClient.swift
- UnitTests/BraintreeCoreTests/Analytics/FakeAnalyticsService.swift
- UnitTests/BraintreeTestShared/MockAPIClient.swift
- Alphabetize analytics events in `sendAnalyticsEvent`
> Alphabetize Analytics Events

- CHANGELOG.md
- Demo/Application/Features/PayPalWebCheckoutViewController.swift
- Sources/BraintreePayPal/BTPayPalCheckoutRequest.swift
- Sources/BraintreePayPal/BTPayPalClient.swift
- Sources/BraintreePayPal/BTPayPalRequest.swift
- Sources/BraintreePayPal/BTPayPalVaultBaseRequest.swift
- Sources/BraintreePayPal/BTPayPalVaultRequest.swift
- UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift
- UnitTests/BraintreePayPalTests/BTPayPalRequest_Tests.swift
- UnitTests/BraintreePayPalTests/BTPayPalVaultRequest_Tests.swift
- Move `universalLink` to `BTPayPalClient` initializer
> Move `universalLink` to `BTPayPalClient`

- CHANGELOG.md
- Sources/BraintreePayPal/BTPayPalClient.swift
- Sources/BraintreePayPal/BTPayPalVaultRequest.swift
- A few small docstrings updates to prepare for beta release of the PP App Switch feature
- Sandbox support is in progress
- Clarify CHANGELOG entry to highlight that this feature is marked "BETA"
@scannillo
> [QL] PP App Switch - cleanup docstrings for release

- Sources/BraintreeCore/Analytics/RepeatingTimer.swift
- Cleanup Docstrings to Match Formatting
> Cleanup Docstrings to Match Formatting

- CHANGELOG.md
- Updating to align the naming of this feature across iOS and Android per this comment: https://github.com/braintree/braintree_android/pull/1075#discussion_r1686819660
> Align Edit FI CHANGELOG with Android

- Demo/Application/Features/PayPalWebCheckoutViewController.swift
- Sources/BraintreePayPal/RecurringBillingMetadata/BTPayPalRecurringBillingDetails.swift
- UnitTests/BraintreePayPalTests/BTPayPalVaultRequest_Tests.swift
Additional field needed to be added to the iOS feature branch, total_amount. 
@jwarmkessel 
@KunJeongPark
> Recurring Billing Agreement Add total amount.

- Sources/BraintreePayPal/BTPayPalVaultEditResult.swift
- Add properties to BTPayPalVaultEdit Result
- Change from class to struct
> Update BTPayPalVaultEditResult Object

- Sources/BraintreePayPal/BTPayPalAnalytics.swift
Adding references to new PayPal analytic events. 
@jwarmkessel @KunJeongPark 
-
> Edit fi analytics

- Demo/Application/Base/ContainmentViewController.swift
Enable production env when new PayPal exp token is selected.
@jwarmkessel @KunJeongPark 
-
> Rba metadata feature tokenization key

- README.md
- Add information about upgrading to the latest SDK version based on how our SDK has been integrated.
- @agedd
> Update README - Add Instructions To Upgrade SDK Version

- .swiftlint.yml
- Sources/BraintreeShopperInsights/BTEligiblePaymentMethods.swift
- Sources/BraintreeShopperInsights/BTEligiblePaymentsRequest.swift
- Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
- Add `BraintreeShopperInsights` module to `.swiftlint.yml`
- Address all swiftlint violations in `BraintreeShopperInsights` - will enable 1 module at a time to make PRs easier to reason about, additionally this allow us to progressively enable Swiftlint across the SDK while ensure code changes in modules where it's enable are compliant
> Add SwiftLint to `BraintreeShopperInsights`

- .swiftlint.yml
- Sources/BraintreeVenmo/BTVenmoAnalytics.swift
- Sources/BraintreeVenmo/BTVenmoAppSwitchRedirectURL.swift
- Sources/BraintreeVenmo/BTVenmoClient.swift
- Sources/BraintreeVenmo/BTVenmoLineItem.swift
- Add `BraintreeVenmo` module to `.swiftlint.yml`
- Address all swiftlint violations in `Sources`
> Add SwiftLint to `BraintreeVenmo`

- Sources/BraintreeCore/BTURLUtils.swift
- Sources/BraintreePayPal/BTPayPalAnalytics.swift
- Sources/BraintreePayPal/BTPayPalClient.swift
- UnitTests/BraintreePayPalTests/BTPayPalAnalytics_Tests.swift
- UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift
- Send analytics events for the edit FI feature
> [QL] Edit FI Analytics

- README.md
- I noticed there were several places where our README was outdated so wanted to clean it up a bit
> Cleanup/Update README.md

- Braintree.xcodeproj/project.pbxproj
- Sources/BraintreeAmericanExpress/BTAmericanExpressClient.swift
- Sources/BraintreeAmericanExpress/Models/BTAmexRewardsBalanceGETBody.swift
- Sources/BraintreeApplePay/BTApplePayClient.swift
- Sources/BraintreeApplePay/Models/BTApplePaymentTokensPOSTBody.swift
- Sources/BraintreeSEPADirectDebit/Models/SEPADebitAccountsPOSTBody.swift
- Sources/BraintreeSEPADirectDebit/Models/SEPADebitPOSTBody.swift
- Sources/BraintreeSEPADirectDebit/SEPADirectDebitAPI.swift
- Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
- Sources/BraintreeShopperInsights/Models/BTEligiblePaymentsPOSTBody.swift
- Sources/BraintreeVenmo/BTVenmoClient.swift
- Sources/BraintreeVenmo/Models/VenmoAccountsPOSTBody.swift
JIRA DTMOBILES-1202
- Rename all Encodable model types from `<API_Name>Request` format to `<API_Name><HTTP_Request_Method_Type>Body`
@scannillo
> [v7] Rename Encodable bodies to standardized format

- Demo/Demo.xcodeproj/xcshareddata/xcschemes/Demo.xcscheme
- Remove Native Checkout testable reference
| 🐛 | 🧽 |
|-----------------|-----------------|
| ![Screenshot 2024-11-07 at 2 50 47 p m](https://github.com/user-attachments/assets/a35805b1-89fa-4dbc-8fd8-593e0c007817) | ![Screenshot 2024-11-07 at 2 50 21 p m](https://github.com/user-attachments/assets/05c86a81-c147-4ec9-ac98-e00c247e57a7) |
- @richherrera
> [V7] Remove MXO testable reference

- Demo/Application/Features/PayPalWebCheckoutViewController.swift
- Remove duplicate contact information.
- @richherrera
> Fix merge on demo app

- Sources/BraintreePayPal/BTPayPalApprovalURLParser.swift
- Sources/BraintreePayPal/BTPayPalCheckoutRequest.swift
- Make updates to the parse the URL returned from gateway for the 1-time checkout app switch flow. 
- @agedd
> Update Parsing App Switch URL For 1-Time Checkout

- CHANGELOG.md
- Demo/Application/Features/AmexViewController.swift
- Demo/Application/Features/CardTokenizationViewController.swift
- Demo/Application/Features/ThreeDSecureViewController.swift
- IntegrationTests/BTCardClient_IntegrationTests.swift
- IntegrationTests/BraintreeAmexExpress_IntegrationTests.swift
- SampleApps/CarthageTest/CarthageTest/ViewController.swift
- SampleApps/SPMTest/SPMTest/ViewController.swift
- Sources/BraintreeCard/BTCardClient.swift
- UnitTests/BraintreeCardTests/BTCardClient_Tests.swift
- V7_MIGRATION.md
- Update `BTCardClient` with new BTAPIClient pattern
- @agedd
> [v7] Update `BTCardClient` with new APIClient Pattern

- CHANGELOG.md
- Demo/Application/Features/ShopperInsightsViewController.swift
- Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
- UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClient_Tests.swift
- V7_MIGRATION.md
Update initializer to `BTShopperInsightsClient(authorization:shopperSessionID:)`
@jwarmkessel @warmkesselj
> Update ShopperInsights signature 

- Braintree.xcodeproj/project.pbxproj
- Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
- Sources/BraintreeShopperInsights/BTShopperInsightsClientV2.swift
- Add skeleton BTShopperInsightsClientV2 class
- Deprecate BTShopperInsightsClient
- @richherrera
> [PRV2] Add BTShopperInsightsClientV2

- Braintree.xcodeproj/project.pbxproj
- Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
- Sources/BraintreeShopperInsights/BTShopperInsightsClientV2.swift
- UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClientV2_Tests.swift
- Add analytics calls and app installed checks to BTShopperInsightsClientV2 
- @richherrera
> [PRV2] Move existing logic to BTShopperInsightsClientV2

- Demo/Application/Features/PayPalWebCheckoutViewController.swift
> RBA demo app

- Braintree.xcodeproj/project.pbxproj
- CHANGELOG.md
- Sources/BraintreeVisaCheckout/BTVisaCheckoutAddress.swift
- UnitTests/BraintreeVisaCheckoutTests/BTVisaCheckoutClient_Tests.swift
Create BTVisaCheckoutAddress
@jwarmkessel @warmkesselj
> Create BTVisaCheckoutAddress swift version

- Sources/BraintreePayPal/BTPayPalPhoneNumber.swift
- Update BTPayPalPhoneNumber doc string to include number formatting rules
-
> Update BTPayPalPhoneNumber doc string

- Braintree.xcodeproj/project.pbxproj
- Sources/BraintreeCard/CreditCardGraphQLBody.swift
- Sources/BraintreeCore/BTGraphQLEncodableBody.swift
- Sources/BraintreeVenmo/Models/VenmoCreatePaymentContextGraphQLBody.swift
- Sources/BraintreeVenmo/Models/VenmoQueryPaymentContextGraphQLBody.swift
Define a protocol for Encodable objects to standardize how we pass queries and query variables specific to our backend implementation.
@jwarmkessel @warmkesselj
> Introduce protocol to standardize GraphQL body structure

- .github/workflows/build.yml
- Temporary fix for recent build issues. This fix is suggested by GitHub until they fix their runner: https://github.com/actions/runner-images/issues/12863#issuecomment-3210358802
> Temporary Runner Fix

- .github/workflows/security.yml
- Removes if condition in this shared workflow since the condition since additional support is added in the security-workflows repo for push events.
-
> Remove If Block in Shared Workflow 
