Braintree/API/Client/BTClientToken.m

This is an alternative approach to #88 that leaves the public `BTClient` interface intact.

Add additional BT_ENABLE_APPLE_PAY preprocessor macros in BTClient.m

---

Braintree/Payments/@Public/BTPaymentProvider.h
Braintree/Payments/BTPaymentProvider.m
Specs/Braintree-Payments-Specs/BTPaymentsSpec.m

This provides information about the status of the transaction by the time that requestsDismissalOfViewController: is called. See #73

Added status property to BTPaymentProvider

---

Braintree/API/Networking/BTHTTP.m
Rakefile
Specs/Braintree-API-Integration-Specs/BTHTTPSSLPinningSpec.m

Today, there was a configuration change in sandbox that caused our HTTP client to break. In particular, the sandbox began to request [SSL client certificates](https://docs.oracle.com/cd/E19424-01/820-4811/aakhe/index.html). Our [status page](https://status.braintreepayments.com/incidents/ypbc8csb6hpk) has more details about the incident.
Unfortunately, our HTTP client, `BTHTTP`, uses [SSL pinning code](https://github.com/braintree/braintree_ios/blob/3.5.0/Braintree/API/Networking/BTHTTP.m#L378-L389) that did not handle a challenge with this type of authentication method. Specifically, we never called the callback in 
our implementation of `URLSession:didReceiveChallenge:completionHandler:` when the authentication method type was anything other than `NSURLAuthenticationMethodServerTrust`. …

[Bugfix] SSL Pinning should pass through unexpected authentication methods

---

Braintree/Drop-In/BTDropInContentView.m
Braintree/UI/Views/Payments Components/BTUISummaryView.m

This should fix https://github.com/braintree/braintree_ios/issues/101.
Please note that, since I'm not an Obj C developer, I haven't written any tests to validate correct behaviour. If anyone is more comfortable with the testing frameworks braintree uses, feel free to pick it up and add tests.
Here are two screenshots demonstrating the issue before and after the fix:
**Before fix**
**After fix**

Fix wrapping of texts in SummaryView

---

Braintree/Drop-In/BTPaymentButton.m

Also gets rid of "negative or zero sizes are not supported in the flow layout" log message when BTPaymentButton is shown.

Fix setupViews being called twice in BTPaymentButton

---

BraintreeApplePay/Public/BTConfiguration+ApplePay.h

Fix the following error when integrating via CocoaPods with `use_frameworks!`
'BraintreeCore/BraintreeCore.h' file not found

Fix import of BraintreeCore.h

---

BraintreePayPal/BTPayPalDriver.m

Addresses this issue: https://github.com/braintree/braintree_ios/issues/182
Calls the tokenization callback for cancellation when:
* `SFSafariViewController` "Done" button is tapped

4.0 safari cancellation redux

---

BraintreePayPal/BTPayPalDriver.m

This fix prevents calling requestsDismissalOfViewController when there is nothing to dismiss. The same way `requestsPresentationOfViewController` is not being called when there is nothing to present.
Before this, the library was crashing on runtime when using swift and iOS < 9 as this is passing `nil` to a function signature that is marked as `non_null`.

Prevent calling requestsDismissalOfViewController

---

README.md

This addresses #202 and clarifies that the manual integrations doc applies to v3, and that v4 instructions are coming soon.
@skunkworks @intelliot @demerino :eyes: ?

Fix manual integration instructions link in README

---

DEVELOPMENT.md

Fix a typo

---

BraintreePayPal/PayPalOneTouch/Analytics/PPFPTITracker.h

This missing specifier is preventing the project to build in Xcode 7.3 (beta 3). I realize 7.3 is not officially released and things could change between now and the final release, but it's probably good to add this regardless of Xcode version.

Add missing _Nullable specification

---

BraintreeUI/Views/Custom Views/BTUIFloatLabel.m
BraintreeUI/Views/Forms/BTUICardFormView.m

If you setup a theme on `BTUICardFormView` it's not correctly propagated to children for fields and float labels. This patch does that.

Update theme on child components if set/changed

---

Braintree.xcodeproj/project.pbxproj

Currently static library (libBraintree.a) has missing two symbols:
- `_OBJC_CLASS_$_BTUICardPhoneNumberField`
- `_OBJC_CLASS_$_BTUIUnionPayVectorArtView`
The patch fixes the problem by adding corresponding classes into the
target.

Include missing sources

---

BraintreeCore/Public/BTAPIClient.h

Developers should use `initWithAuthorization:`

BTAPIClient.h - Update init unavailable message

---

BraintreeCore/Public/BTAPIClient.h

Fixes https://github.com/braintree/braintree_ios/issues/285

[Fix] @param warning for incorrect argument name

---

BraintreeCore/BTAnalyticsMetadata.m

#290 
This is the implementation that was used in PINCache: https://github.com/pinterest/PINCache/pull/72
It has since been removed, but as far as I can tell, only because the feature requiring `[UIApplication sharedApplication]` was removed as well:
https://github.com/pinterest/PINCache/pull/99

[fix] Add app extension compatibility

---

BraintreeCore/BTAnalyticsMetadata.m
UnitTests/BTAnalyticsMetadataSpec.m

See also https://github.com/braintree/braintree_ios/pull/291
When running in an iOS app extension, we don't have access to `[UIApplication sharedApplication]`, which is used in BraintreeCore's BTAnalyticsMetadata.
We've also hijacked the `deviceScreenOrientation` analytics property to return `AppExtension` when running inside an app extension, which may be useful later.

Add support for App Extensions

---

.travis.yml
Podfile.lock

As titled.
It seems that `pod install` fails if BraintreeDropIn is already installed under ./Pods directory and its latest commit hash differs from the hash written in .lock file. So as a workaround, delete ./Pods directory and retry installation when `pod install` failed.

Make CI passable

---

BraintreeCore/BTAnalyticsMetadata.m
BraintreeUI/Views/Apple Pay/BTMockApplePayPaymentAuthorizationView.h
BraintreeUI/Views/Apple Pay/BTMockApplePayPaymentAuthorizationView.m
BraintreeUI/Views/Apple Pay/BTMockApplePayPaymentAuthorizationViewController.h
BraintreeUI/Views/Apple Pay/BTMockApplePayPaymentAuthorizationViewController.m

Enabling BTMockApplePayPaymentAuthorizationView, BTMockApplePayPaymentAuthorizationViewController and fixing NS_DESIGNATED_INITIALIZER build issue.
since BT_ENABLE_APPLE_PAY is no longer needed we need to cancel the pre-proccesing macro protection.

Enabling BTMockApplePayPaymentAuthorizationViewController

---

BraintreeCore/BTAPIClient.m

`components.port` is being set to an `NSString` when it expects an `NSNumber`. For some reason this works on iOS 10, but it causes a crash on iOS 11 (building with Xcode 9 beta 3).

Set port correctly in base url

---

BraintreePayPal/BTPayPalDriver.m
BraintreePayPal/BTPayPalRequestFactory.h
BraintreePayPal/BTPayPalRequestFactory.m
BraintreePayPal/PayPalDataCollector/PPDataCollector.m
BraintreePayPal/PayPalOneTouch/Analytics/PPFPTITracker.m
BraintreePayPal/PayPalOneTouch/Analytics/PPOTAnalyticsTracker.m
BraintreePayPal/PayPalOneTouch/Configuration/PPOTConfiguration.m
BraintreePayPal/PayPalOneTouch/Models/PPOTAppSwitchResponse.m
BraintreePayPal/PayPalOneTouch/Models/PPOTAppSwitchUtil.m
BraintreePayPal/PayPalOneTouch/Models/PPOTAuthorizationRequest.m
BraintreePayPal/PayPalOneTouch/Models/PPOTBillingAgreementRequest.m
BraintreePayPal/PayPalOneTouch/Models/PPOTCheckoutAppSwitchRequest.m
BraintreePayPal/PayPalOneTouch/Models/PPOTCheckoutBrowserSwitchRequest.m
BraintreePayPal/PayPalOneTouch/Models/PPOTCheckoutRequest.m
BraintreePayPal/PayPalOneTouch/Models/PPOTCore.m
BraintreePayPal/PayPalOneTouch/Models/PPOTOAuth2BrowserSwitchRequest.m
BraintreePayPal/PayPalOneTouch/Models/PPOTOAuth2SwitchRequest.m
BraintreePayPal/PayPalOneTouch/Models/PPOTPersistentRequestData.h
BraintreePayPal/PayPalOneTouch/Models/PPOTPersistentRequestData.m
BraintreePayPal/PayPalOneTouch/Models/PPOTRequest.m
BraintreePayPal/PayPalOneTouch/Models/PPOTResult.m
BraintreePayPal/PayPalOneTouch/Models/PPOTSwitchRequest.m

Build systems (like BUCK) require imports from other frameworks to use the angled bracket syntax. This pull request addresses this for the BraintreePayPal framework.

Update BraintreePayPal framework to support system/framework imports

---

BraintreeVenmo/BTVenmoAppSwitchRequestURL.m
BraintreeVenmo/BTVenmoAppSwitchReturnURL.m
BraintreeVenmo/BTVenmoDriver.m

Build systems (like BUCK) require imports from other frameworks to use the angled bracket syntax. This pull request addresses this for the BraintreeVenmo framework.
Similar issue addressed by @nudge ( #377 )

Fix BraintreeVenmo framework to support system/framework imports

---

BraintreeUI/Models/BTUICardType.m
CHANGELOG.md

UnionPay cards used to be issued with luhn invalid card numbers. We have always rejected luhn invalid cards on the backend, so this just brings the front end in line with that behavior.
@braintree/team-dx

Luhn validate UnionPay cards

---

BraintreeCore/BTAPIClient_Internal.h

`graphQLURLForEnvironment:` could return `nil` but was marked as returning a `nonnull` object.

Fix a static analyzer memory error in BTAPIClient

---

BraintreePaymentFlow/ThreeDSecure/BTThreeDSecureV2Provider.m

This PR fixes the following warning cased by importing the `BTConfiguration+ThreeDSecure` implementation file rather than the header:
> instance method ‘cardinalAuthenticationJWT’ in category from BTConfiguration+ThreeDSecure.o conflicts with same method from another category

Correct importing of BTConfiguration+ThreeDSecure

---

.gitignore

https://github.com/braintree/braintree_ios/issues/485
When integrating braintree_ios sdk via Carthage (as submodules), consumer Applications repos are dirtied due to a SYMLink between the cloned carthage checkout directory, and the Applications root Carthage/Checkout directory.
This had not been an issue with our previous integration of Release 4.24.0, which didn't have the Cardinal dependency yet to reveal this issue.
When Carthage integrates dependencies, it inspects each dependency as that dependencies dependency, and eventually constructs a Cartfile.resolved include all dependencies in the graph.
As part of this resolution, all dependencies of dependencies are cloned to the top level which may then be shared with dependencies (if multiple dependencies reuse the same item). This is …

Issue 485: Carthage Submodule Integration Dirty

---

Gemfile
Gemfile.lock

- Clean up unused gems
- `git-pairing`
- `xcpretty` _was replaced by the xcbeautify Pod_
- `rake_commit`
There is a slight chance some folks are using `git-pairing`, though I haven't seen it used. I see more commonly people have `git duet` enabled configured on their machines. Let us know if you have objections to removing it!
@scannillo

Cleanup unused gems

---

.github/workflows/testing.yml
Demo/UI Tests/PayPal UI Tests/PayPal_BillingAgreement_UITests.swift
Demo/UI Tests/PayPal UI Tests/PayPal_OneTimePayment_UITests.swift

* Update GH Actions file to always use Xcode 12.2
* Tap in corner of screen during PayPal flow so that the tests don't accidentally dismiss the PayPal site early
- @sestevens

CI stability improvements

---

Demo/Application/Features/3D Secure/BraintreeDemoThreeDSecurePaymentFlowViewController.m

- The method signature for `onLookupComplete` changed in v5-beta1, so we can remove the old method from the 3DS demo view controller.
- It looks like `UiCustomization` (and related classes) are not being exposed to merchants property, so I also added a TODO. We'll fix this in a separate PR.
- @sestevens

Remove old delegate method from 3DS demo view controller

---

V5_MIGRATION.md

- In section on 3DS, make the comments for each integration method (CocoaPods, Carthage, SPM) collapsible so that the guide is easier to read
- Add section on changes to 3DS delegate method
- Add note about `Braintree/Apple-Pay` subspec being renamed to `Braintree/ApplePay`
**NOTE:** It might be helpful to look at the [rendered markdown file](https://github.com/braintree/braintree_ios/blob/v5-migration-guide-updates/V5_MIGRATION.md).
- @sestevens

Update v5 migration guide

---

Sources/BraintreeThreeDSecure/BTThreeDSecureRequest.m
UnitTests/BraintreeThreeDSecureTests/BTThreeDSecure_Tests.swift

- Move check for nil delegate when 3DS 2 is requested earlier in flow. This should help with a unit test that's been flaky in CI.
- @sestevens

Update 3DS Unit Test

---

Sources/BraintreeCore/BTAPIClient_Internal.h
Sources/BraintreeCore/Public/BraintreeCore/BTAPIClient.h
Sources/BraintreeCore/Public/BraintreeCore/BTPreferredPaymentMethods.h

- Braintree Drop-in uses a couple of methods on BTAPIClient that are currently internal only. BT Drop-in was redeclaring these methods in an internal header in order to access them. We're making these methods public in order to avoid a "ambiguous reference" error in Drop-in. (See https://github.com/braintree/braintree-ios-drop-in/pull/256.)
We aren't adding a changelog entry or doc comments for these methods, since we don't intend them to be used by merchants.
- @scannillo
- @sestevens

Make GET and POST methods on BTAPIClient Public

---

CHANGELOG.md
Sources/BraintreeThreeDSecure/BTThreeDSecureRequest.m
UnitTests/BraintreeThreeDSecureTests/BTThreeDSecureRequest_Tests.swift
V5_MIGRATION.md

- Change default 3DS version to 3DS2
- @sestevens

Change default 3DS version to 3DS2

---

UnitTests/BraintreeThreeDSecureTests/BTThreeDSecureRequest_Tests.swift
UnitTests/BraintreeThreeDSecureTests/BTThreeDSecure_Tests.swift
UnitTests/BraintreeThreeDSecureTests/MockDelegates.swift

- This is a follow up to PR #585 
- Fix UnitTest that broke due to changing the default 3DS version from 1 to 2
- @scannillo @sestevens

Update 3DS Unit Tests for defaulting to v2

---

CHANGELOG.md
Demo/Application/Features/3D Secure/BraintreeDemoThreeDSecurePaymentFlowViewController.m
Sources/BraintreeThreeDSecure/BTPaymentFlowDriver+ThreeDSecure.m
Sources/BraintreeThreeDSecure/BTThreeDSecureRequest.m
Sources/BraintreeThreeDSecure/BTThreeDSecureRequest_Internal.h
Sources/BraintreeThreeDSecure/Public/BraintreeThreeDSecure/BTThreeDSecureRequest.h
UnitTests/BraintreeThreeDSecureTests/BTPaymentFlowDriver+ThreeDSecure_Tests.swift
UnitTests/BraintreeThreeDSecureTests/BTThreeDSecureRequest_Tests.swift
V5_MIGRATION.md

- Make shippingMethod property on BTThreeDSecureRequest an enum instead of a string
- @sestevens
- @scannillo

Make shippingMethod property on BTThreeDSecureRequest an enum

---

Sources/BraintreeThreeDSecure/BTPaymentFlowDriver+ThreeDSecure.m
Sources/BraintreeThreeDSecure/BTThreeDSecureRequest.m
Sources/BraintreeThreeDSecure/BTThreeDSecureRequest_Internal.h
UnitTests/BraintreeThreeDSecureTests/BTPaymentFlowDriver+ThreeDSecure_Tests.swift
UnitTests/BraintreeThreeDSecureTests/BTThreeDSecureRequest_Tests.swift
UnitTests/BraintreeThreeDSecureTests/BTThreeDSecure_Tests.swift
UnitTests/BraintreeThreeDSecureTests/BraintreeThreeDSecureTests-Bridging-Header.h

- Update sdkVersion param for server-side 3DS lookup to include platform as well as version. This fixes a discrepancy observed between client-side and server-side lookups.
- We also discovered that client-side lookup requests were missing the requested version param, so we're adding it now.
- @sestevens 
- @scannillo

Update sdkVersion param for server-side 3DS lookup to include platform

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalDriver.m
Sources/BraintreePayPal/BTPayPalRequest.m
Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalRequest.h
UnitTests/BraintreePayPalTests/BTPayPalDriver_Checkout_Tests.swift

Add `offerPayLater` to `BTPayPalRequest`. This will default the customer to the Pay Later tab if they qualify during the Checkout experience.
- @demerino

Add offerPayLater to BTPayPalRequest

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalDriver.m

- This [GH issue](https://github.com/braintree/braintree_ios/issues/563) surfaced a memory leak in v4 of Braintree iOS for the PayPal flow
- This PR fixes the issue in v5 by making sure to set the `self.authenticationSession` property to nil for _both_ the success and cancel PayPal flows
- @scannillo 
- @sestevens

Fix memory leak in BTPayPalDriver

---

SampleApps/CarthageTest/CarthageTest.xcodeproj/project.pbxproj

- Remove old frameworks linked to CarthageTest app. This fixes duplicate symbol errors when trying to build the app.
- Added a changelog entry
- @sestevens 
- @scannillo

Remove old frameworks linked to CarthageTest app

---

Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Demo/Application/Features/Preferred Payment Methods/BraintreeDemoPreferredPaymentMethodsViewController.swift
Demo/Application/Features/Venmo - Custom Button/BraintreeDemoCustomVenmoButtonViewController.m
Sources/BraintreeVenmo/BTVenmoDriver.m
Sources/BraintreeVenmo/BTVenmoRequest.m
Sources/BraintreeVenmo/Public/BraintreeVenmo/BTVenmoDriver.h
Sources/BraintreeVenmo/Public/BraintreeVenmo/BTVenmoRequest.h
Sources/BraintreeVenmo/Public/BraintreeVenmo/BraintreeVenmo.h
UnitTests/BraintreeVenmoTests/BTVenmoDriver_Tests.swift
V5_MIGRATION.md

- Addresses feedback in PR #595 
- Adds `BTVenmoRequest`
- Replaces methods on `BTVenmoDriver` that required separate `vault` and `profileID` params to accept a single `BTVenmoRequest` 
- Update V5_MIGRATION_GUIDE.md
@scannillo @sestevens

Add BTVenmoRequest

---

Sources/BraintreePayPal/BTPayPalDriver.m

- Addresses feedback in #595 
- JS and Android do not include this `bt_int_type` param on the PayPal checkout URLs. It was used a few years ago for some A/B testing with `SFSafariAuthenticationSession`, and is no longer used in other BT repos. (Confirmed by @crookedneighbor).

Remove bt_int_type from PayPal checkout URL

---

CHANGELOG.md
Demo/Application/Features/Fraud Protection - BTDataCollector/BraintreeDemoBTDataCollectorViewController.m
IntegrationTests/BraintreeDataCollector_IntegrationTests.m
Sources/BraintreeDataCollector/BTDataCollector.m
Sources/BraintreeDataCollector/Public/BraintreeDataCollector/BTDataCollector.h
UnitTests/BraintreeDataCollectorTests/BTDataCollector_Tests.swift
UnitTests/BraintreeThreeDSecureTests/BTPaymentFlowDriver+ThreeDSecure_Tests.swift
V5_MIGRATION.md

- Addresses comments in #595 
- Android (and JS to my understanding) doesn't have an equivalent of `BTDataCollectorDelegate` for merchants to hook into notifications for when Kount started, succeeded, or errored.
- We can remove `collectCardFraudData` in favor of `collectDeviceData`, since both methods collected all data (Kount & PayPal). This also matches Android.
- Remove `BTDataCollectorDelegate`
- Remove `BTDataCollector.collectCardFraudData()` method
- Remove `BTDataCollectorKountErrorDomain`
- @scannillo

Clean up BTDataCollector

---

Sources/BraintreeCore/BTAnalyticsMetadata.m
UnitTests/BraintreeCoreTests/BTAnalyticsMetadataSpec.m
UnitTests/BraintreeThreeDSecureTests/BTPaymentFlowDriver+ThreeDSecure_Tests.swift

Add Analytics metadata for if Swift Package Manager is used.
It would be nice to have an `iosPackageManager` field that returns a string `CocoaPods`, `Swift Package Manager`, or `Carthage`. However, there is no way to differentiate between a Carthage integration & a manual integration. 
We could leave as-is, or instead have an `iosPackageManager` field with the options of:
- `CocoaPods`
- `Swift Package Manager`
- `Carthage or Manual integration`

SPM Analytics Metadata

---

Gemfile.lock

- we noticed we haven't been using the [newest major version](https://bundler.io/blog/2019/01/03/announcing-bundler-2.html) of bundler, so this PR updates the Gemfile. Biggest change is that bundler v2 drops support for ruby versions lower than 2.3.0.
- We don't think this needs a CHANGELOG entry, but if folks feel otherwise let us know.
> @scannillo 
> @hollabaq86

update bundler @ 2.2.9, drops supports for Ruby versions < 2.3.0

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalCheckoutRequest.m
Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalCheckoutRequest.h
Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalRequest.h
Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalVaultRequest.h
UnitTests/BraintreePayPalTests/BTPayPalCheckoutRequest_Tests.swift

- Add `requestBillingAgreement` to `BTPayPalCheckoutRequest`
- Move `billingAgreementDescription` from `BTPayPalVaultRequest` to `BTPayPalRequest`
- @sestevens

PayPal Checkout with Vault (Take 2)

---

CHANGELOG.md

- Add links to v5 betas at the end of the v5 CHANGELOG entry so that it's clear that everything in the betas is included in v5.
- @sestevens 
- @scannillo

Update v5 changelog to include links to betas

---

.github/workflows/release.yml
Braintree.podspec

- Fix `git push` step so that it also pushes the tag for the new version
- Remove unneeded links from Braintree.podspec, since they were causing warnings during `pod lib lint`:
```
- WARN  | url: The URL (https://raw.githubusercontent.com/braintree/braintree_ios/master/Docs/screenshot.png) is not reachable.
- WARN  | screenshot: The screenshot https://raw.githubusercontent.com/braintree/braintree_ios/master/Docs/screenshot.png is not a valid image.
- WARN  | url: The URL (https://twitter.com/braintree) is not reachable.
```
- @sestevens

Update Release Script and Podspec

---

UnitTests/BraintreeCardTests/BTCardClient_Tests.swift
UnitTests/BraintreeCoreTests/BTPreferredPaymentMethods_Tests.swift
UnitTests/BraintreeDataCollectorTests/BTDataCollector_Tests.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift
UnitTests/BraintreeUnionPayTests/BTCardClient_UnionPayTests.swift
UnitTests/BraintreeVenmoTests/BTVenmoDriver_Tests.swift

I noticed that a lot of the unit tests that randomly fail (especially in CI) are using `BTAPIClient` with a mock `BTHTTP` when they could be using `MockAPIClient`. Since `BTAPIClient` kicks off a configuration request in the initializer, I have a hunch that there could be a race condition that causes tests to sporadically fail.
This PR updates unit tests to use `MockAPIClient` where possible. It doesn't address the sporadic failures in the unit tests for `BTAPIClient` itself.
- @sestevens

Update unit tests to use MockAPIClient

---

.github/workflows/release.yml

- The release script depends on there being a CHANGELOG section with the header `## unreleased`. Let's fail early if that's not found.
- @sestevens

Release script - exit early if changelog doesn't have an unreleased section

---

.github/workflows/build.yml
.github/workflows/tests.yml

- Use actions/checkout@v2 instead of v1
- Use Xcode 12.4 instead of 12.3
- Update Carthage check to build the CarthageTest demo app. This is a more thorough check since it pulls down our dependencies (CardinalMobile and PPRiskMagnes).
- Remove `--allow-warnings` flag from `pod lib lint` so that it fails if there are warnings
- Allow Test and Build workflows to be run manually as well as on pull requests. This way we can run them manually prior to releasing.
- @sestevens

Update GH Actions Test and Build Workflows

---

SampleApps/CarthageTest/CarthageTest.xcodeproj/project.pbxproj

- Add each Braintree framework to the Carthage demo app's `Frameworks, Libraries, and Embedded Content` project settings.
- Allows the Carthage demo app to build & run.

Re-link Braintree frameworks to Carthage demo app

---

README.md

Use full links in README so that they work when the README is displayed in our [reference docs](https://braintree.github.io/braintree_ios/) and on [CocoaPods](https://cocoapods.org/pods/Braintree).
- @sestevens

Use full links in README

---

.github/workflows/release.yml
Rakefile

- Update Rakefile and release.yml steps for publishing reference docs to allow multiple version to exist at once
I went ahead and published docs for [4.37.0](https://braintree.github.io/braintree_ios/4.37.0/), so they now live alongside the docs for [5.0.0](https://braintree.github.io/braintree_ios/5.0.0/). Ideally, there would be a drop-down allowing you to toggle between versions, but currently you have to change the version in the URL.
[Related PR in iOS Drop-in](https://github.com/braintree/braintree-ios-drop-in/pull/273)
- @sestevens

Allow multiple versions of the reference docs

---

CHANGELOG.md
Sources/BraintreeApplePay/BTConfiguration+ApplePay.m
UnitTests/BraintreeApplePayTests/BTConfiguration+ApplePay_Tests.swift

- Add support for `PKPaymentNetworkElo` when using the gateway configuration for Apple Pay
- Elo support was added in iOS `12.1.1` but we support down to `12.0` so there is an availability check
> extern PKPaymentNetwork const PKPaymentNetworkElo API_AVAILABLE(macos(11.0), ios(12.1.1), watchos(5.1.2));
- @demerino

Add Elo support to Apple Pay Configuration

---

CHANGELOG.md
Sources/BraintreeCore/BTGraphQLHTTP.m
UnitTests/BraintreeCoreTests/BTGraphQLHTTP_Tests.m

- I was experiencing an app crash when I was testing removing a vaulted payment method in Drop In. This happened because I was able to trigger a VALIDATION error in attempting to delete a payment method belonging to the incorrect customerID.
- Most features in GraphQL that correspond to a GW behavior include a `legacyCode` in their response. Others, such as delete payment method, don't have a corresponding error code in the GW to warrant including a `legacyCode`.
- This PR adds a check for if `errorJSON[@"extensions"][@"legacyCode"]` exists before setting the `code` value.
@scannillo

Fix potential crash on missing `legacyCode` GraphQL param

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalDriver.m
Sources/BraintreePayPal/BTPayPalVaultRequest.m
Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalVaultRequest.h
UnitTests/BraintreePayPalTests/BTPayPalDriver_Tests.swift
UnitTests/BraintreePayPalTests/BTPayPalVaultRequest_Tests.swift
V5_MIGRATION.md

- Add `offerCredit` to `BTPayPalVaultRequest`. This field was initially removed from v5 in favor of `offerPayLater`, but since this field only applies to PayPal Checkout flows, `offerCredit` is still needed on PayPal Vault flows.
- @sestevens 
- @scannillo

Add offerCredit to BTPayPalVaultRequest

---

Demo/Application/Features/Venmo - Custom Button/BraintreeDemoCustomVenmoButtonViewController.m
Demo/Demo.xcodeproj/project.pbxproj
Demo/Demo.xcodeproj/xcshareddata/xcschemes/MockVenmo.xcscheme
Demo/MockVenmo/AppDelegate.swift
Demo/MockVenmo/AppSwitcher.swift
Demo/MockVenmo/Assets.xcassets/AccentColor.colorset/Contents.json
Demo/MockVenmo/Assets.xcassets/AppIcon.appiconset/Contents.json
Demo/MockVenmo/Assets.xcassets/Contents.json
Demo/MockVenmo/Base.lproj/LaunchScreen.storyboard
Demo/MockVenmo/Base.lproj/Main.storyboard
Demo/MockVenmo/Info.plist
Demo/MockVenmo/SceneDelegate.swift
Demo/MockVenmo/ViewController.swift
Demo/UI Tests/Venmo UI Tests/Venmo_UITests.swift

- Add UI tests for the Venmo flow using a dummy app that stands in for the real Venmo app. This won't protect us against changes on the Venmo side that could break this flow, but it'll ensure that we catch any changes to our SDK or the iOS SDK that could break this flow.
- I also updated the demo app to use `PPRiskMagnes.framework` instead of `PPRiskMagnes.xcframework`, which fixes the issue with not being able to run the demo app on a device.
- @sestevens

Venmo UI Tests w/ MockVenmo app

---

Demo/Application/Base/Settings/Settings.bundle/Root.plist
Demo/Application/Features/PayPal - Billing Agreement/BraintreeDemoPayPalBillingAgreementViewController.h
Demo/Application/Features/PayPal - Checkout/BraintreeDemoPayPalCheckoutViewController.h
Demo/Application/Features/PayPal - Checkout/BraintreeDemoPayPalCheckoutViewController.m
Demo/Application/Features/PayPal - Checkout/BraintreeDemoPayPalOneTimePaymentViewController.h
Demo/Application/Features/PayPal - Vault/BraintreeDemoPayPalVaultViewController.h
Demo/Application/Features/PayPal - Vault/BraintreeDemoPayPalVaultViewController.m
Demo/Application/Features/Preferred Payment Methods/BraintreeDemoPreferredPaymentMethodsViewController.swift
Demo/Demo.xcodeproj/project.pbxproj
Demo/UI Tests/PayPal UI Tests/PayPal_Checkout_UITests.swift
Demo/UI Tests/PayPal UI Tests/PayPal_Vault_UITests.swift
Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalDriver.h

- Update demo app:
- Replace "PayPal Billing Agreements" with "PayPal Vault"
- Replace "PayPal One-Time Payments" with "PayPal Checkout"
- Simplify doc string for `BTPayPalDriver`, since it's outdated. The new comment matches what we have on Android.
- @sestevens

Update PayPal terms used in demo app

---

Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Podfile.lock

- Update PPRiskMagnesOC to 4.0.12. This version of Magnes resolves a duplicate symbols errors that a merchant reported with Magnes and another SDK.
Updating this in 4.x because the merchant who reported the issue is using Drop-in, and the latest GA release of Drop-in uses version 4.x of Braintree iOS. We won't need to update this in v5 because v5 uses the Swift version of Magnes, not the Obj-C version.
- @sestevens

Update PPRiskMagnesOC to 4.0.12

---

README.md
V5_MIGRATION.md

- Clarify Swift 5.1+ requirement. Swift 5 introduces ABI stability & 5.1 introduces module stability.
@scannillo

Clarify Swift 5.1

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift

- We did an audit of redundant package dependency declarations found in:
- Braintree.podspec
- Package.swift
- Xcode project file (within each framework target)
@sestevens @scannillo

Cleanup dependencies

---

Sources/PayPalDataCollector/Public/PayPalDataCollector/PPDataCollector.swift

- We got some feedback about a misleading doc string in `PPDataCollector`. The device data collected can be used for cards, not just PayPal and Venmo transactions, so this PR updates that comment.
- @sestevens

Update PPDataCollector doc string

---

Sources/BraintreeVenmo/BTVenmoDriver.m
Sources/BraintreeVenmo/BTVenmoDriver_Internal.h
Sources/BraintreeVenmo/Public/BraintreeVenmo/BTVenmoRequest.h
UnitTests/BraintreeVenmoTests/BTVenmoDriver_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoRequest_Tests.swift

- Launch the new VenmoContext flow only if the `paymentMethodUsage` property on `BTVenmoRequest` is explicitly set
- Adds a default enum case to `BTVenmoPaymentMethodUsage` for `None`
- Reorganize methods in `BTVenmoDriver.m` to align with pragma mark descriptions
- I have an open question regarding how we should communicate this new "feature" to merchants, using this opt-in pattern. See PR comment.
- [JIRA](https://engineering.paypalcorp.com/jira/browse/DTBTSDK-942)
@scannillo

Make Venmo Context flow opt-in

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalDriver.m

- Fix a bug where `userAction` on `BTPayPalCheckoutRequest` was ignored, which meant that the button in the PayPal web page displayed the wrong text.
The bug was that we had a local variable called `approvalURL` as well as a property, `self.approvalURL`. We added the `userAction` query param to `self.approvalURL`, but then were actually using `approvalURL` (the local variable, which didn't have the `userAction` query param) to open the web page.
The tests didn't catch this because they are checking `self.approvalURL`, which was constructed correctly (but then not actually used). Instead of setting `self.approvalURL` early on, I moved it so that it is set right before we pass the URL to `ASWebAuthenticationSession`. That way, we're testing the URL that we're actually using.
> List GitHub …

Fix bug where `userAction` on `BTPayPalCheckoutRequest` was ignored

---

Sources/BraintreeVenmo/BTVenmoDriver.m
UnitTests/BraintreeVenmoTests/BTVenmoDriver_Tests.swift

- Add error handling for the following cases of the Venmo Payment Context flow:
- 1) If the request to `CreateVenmoPaymentContext` fails
- 2) If the result of `CreateVenmoPaymentContext` is unable to parse a `venmoContextPaymentID`
- [JIRA](https://engineering.paypalcorp.com/jira/browse/DTBTSDK-955)
@scannillo

Error handling for VenmoPaymentContextID fetch/parse

---

Sources/BraintreeCard/BTCardClient.m
Sources/BraintreeCore/BTAPIClient.m
Sources/BraintreeCore/BTJSON.m
Sources/BraintreeCore/BTPayPalIDToken.m
Sources/BraintreeCore/Public/BraintreeCore/BTJSON.h
Sources/BraintreeThreeDSecure/BTThreeDSecureResult.m
UnitTests/BraintreeCoreTests/BTAPIClient_SwiftTests.swift
UnitTests/BraintreeCoreTests/BTBinData_Tests.swift
UnitTests/BraintreeCoreTests/BTJSON_Tests.swift
UnitTests/BraintreeDataCollectorTests/BTDataCollector_Tests.swift

While adding the new module for PayPal native checkout in Swift, we came across some inconsistencies with the return types of methods on `BTJSON`. We've updated these methods so that working with `BTJSON` in Swift is more straightforward.
* Update `asArray` method to return `NSArray<BTJSON *> *`
* Update `asStringArray` method to return `NSArray<String *>`
* Update `objectForKeyedSubscript` to return `BTJSON`
* Update `objectAtIndexedSubscript` to return `BTJSON`
Once this change is released, we'll need to make a small update to iOS Drop-in: https://github.com/braintree/braintree-ios-drop-in/pull/329.
- @sestevens 
- @scannillo

Update BTJSON for Swift compatibility

---

Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalCheckoutRequest.h

- Remove incorrect docs indicating that commas are allowed in the amount on BTPayPalCheckoutRequest
- @sestevens

Fix docs for `amount` on `BTPayPalCheckoutRequest`

---

README.md

- Clarify that versions 4.9.6 and below are unsupported due to expired SSL cert usage.

Clarify SDK Deprecation Policy Note

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/tests.yml
Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Demo/UI Tests/Helpers/BTUITest.swift
Package.swift
UnitTests/BraintreeCoreTests/BTAppContextSwitcher_Tests.swift
UnitTests/BraintreeCoreTests/BraintreeCoreTests-Bridging-Header.h
UnitTests/BraintreeCoreTests/Helpers/BTMockOpenURLContext.h
UnitTests/BraintreeCoreTests/Helpers/BTMockOpenURLContext.m

- Update GitHub Action workflows to use macOS 11 and Xcode 12.5
- Update how we mock `UIOpenURLContext` in unit tests. Creating a subclass is not longer possible since the initializer is not available. So now we use OCMock (an Obj-C mocking framework) instead, following [this approach](https://github.com/markspanbroek/MockingInSwift#cheating).
- @scannillo 
- @sestevens

Update CI to use macOS 11 and Xcode 12.5

---

CHANGELOG.md
Sources/BraintreeCore/Public/BraintreeCore/BTPreferredPaymentMethods.h
Sources/BraintreePayPal/BTPayPalDriver.m
Sources/BraintreeVenmo/BTVenmoDriver.m
Sources/BraintreeVenmo/BTVenmoDriver_Internal.h

[GitHub Issue](https://github.com/braintree/braintree-ios-drop-in/issues/343)
[XCode 13-beta3](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes) release notes call out the following change:
> Linking Swift packages from application extension targets or watchOS applications no longer emits unresolvable warnings about linking to libraries not safe for use in application extensions. This means that code referencing APIs annotated as unavailable for use in app extensions must now themselves be annotated as unavailable for use in application extensions, in order to allow that code to be used in both apps and app extensions. (66928265)
In places that we use Apple APIs which aren't usable in App Extensions (`UIApplication.sharedApplication`) we need to …

Xcode13-beta3 Fix

---

Braintree.xcodeproj/project.pbxproj

- The dependency of `BraintreeVenmo` on `BraintreeCore` should have been `Do Not Embed`, but it was set to `Embed & Sign`. **This PR sets it to `Do Not Embed`.**
- This was causing duplicate framework issues when trying to upload our Demo app to TestFlight. See the image below for the details.
@scannillo

TestFlight Fix 

---

CHANGELOG.md
Sources/BraintreeThreeDSecure/BTPaymentFlowDriver+ThreeDSecure.m
Sources/BraintreeThreeDSecure/BTThreeDSecureRequest.m
Sources/BraintreeThreeDSecure/Public/BraintreeThreeDSecure/BTThreeDSecureRequest.h
UnitTests/BraintreeThreeDSecureTests/BTPaymentFlowDriver+ThreeDSecure_Tests.swift

- Add `cardAddChallengeRequested` to `BTThreeDSecureRequest`
- Create `BTThreeDSecureCardAddChallenge` enum to allow for true, false, or nil options for this param 
- @kate-paypal 
- @sarahkoop

Add `BTThreeDSecureCardAddChallenge`

---

Demo/UI Tests/PayPal UI Tests/PayPal_Checkout_UITests.swift
Demo/UI Tests/PayPal UI Tests/PayPal_Vault_UITests.swift
Demo/UI Tests/ThreeDSecure UI Tests/ThreeDSecure_V1_UITests.swift
Demo/UI Tests/ThreeDSecure UI Tests/ThreeDSecure_V2_UITests.swift

- Use Apple built in `waitForExistence` method to speed up UI tests and fix flakiness when running locally
- Use Apple springboard to access built-in alert dialog button in PayPal UI tests to fix CI flakiness
- @scannillo 
- @sarahkoop

Fix Flakey UI Tests

---

.github/workflows/build.yml

- We can remove the `--allow-warnings` tag on the `pod lib lint` command in our CI now that we fixed [this issue](https://github.com/braintree/braintree_ios/pull/719).
@scannillo

Remove "allow warnings" on pod lib lint

---

.github/workflows/build.yml
.github/workflows/release.yml

- Remove GitHub Actions jobs using Xcode 12.5 which will no longer be supported in v6.
- @scannillo 
- @sarahkoop

Remove Xcode 12.5 GitHub Actions Jobs

---

BraintreePayPal/BTPayPalDriver.m
BraintreePayPal/BTPayPalRequest.m
BraintreePayPal/Public/BTPayPalRequest.h
CHANGELOG.md
Podfile.lock
UnitTests/BraintreePayPal_UnitTests/BTPayPalDriver_Tests.swift

- Add `offerPayLater` to `BTPayPalRequest` to v4 for an LE merchant
- Mimics (https://github.com/braintree/braintree_ios/pull/590) which added it to v5
@scannillo

v4 - Add offerPayLater to BTPayPalRequest

---

CHANGELOG.md
Demo/Application/Features/Preferred Payment Methods/BraintreeDemoPreferredPaymentMethodsViewController.swift
Demo/Application/Features/Venmo - Custom Button/BraintreeDemoCustomVenmoButtonViewController.m
Demo/MockVenmo/AppSwitcher.swift
Sources/BraintreeVenmo/BTVenmoDriver.m
Sources/BraintreeVenmo/BTVenmoRequest.m
Sources/BraintreeVenmo/Public/BraintreeVenmo/BTVenmoRequest.h
UnitTests/BraintreeVenmoTests/BTVenmoDriver_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoRequest_Tests.swift
V6_MIGRATION.md

> NEXT_MAJOR_VERSION - make paymentMethodUsage a required param in the initializer & remove UNSPECIFIED case from enum
This PR addresses the above comment to achieve parity with Android v4.
- Remove `BTVenmoPaymentMethodUsageUnspecified` case.
- Require merchant to initialize `BTVenmoRequest` with a `paymentMethodUsage` (single or multi use)
- Always use the Venmo PaymentContext flow.
- Update UnitTests accordingly.
@scannillo @sarahkoop

iOS v6 - Update Venmo Payment Context Flow

---

Demo/Application/Base/BraintreeDemoAppDelegate.m
Demo/Application/Base/BraintreeDemoContainmentViewController.m
UnitTests/BraintreeCoreTests/BTHTTPSpec.m

- Update deprecated `UIBarStyleBlackTranslucent`
- Remove deprecated network activity indicator methods
- See [Apple doc](https://developer.apple.com/design/human-interface-guidelines/ios/controls/progress-indicators/)
- "The network activity indicator is deprecated in iOS 13 and on devices with edge-to-edge displays."
- Silence function signature warning for old HTTPSpec tests
@scannillo

Remove Xcode 13 Warnings

---

CHANGELOG.md
Package.swift

These changes will help streamline our docs, as well as simplify things for merchants.
Before:
- 3DS via SPM: Include the `BraintreeThreeDSecure` and `PayPalDataCollector` frameworks
- PayPal via SPM: Include the `BraintreePayPal` and `PayPalDataCollector` frameworks
- Local Payments via SPM:  Include the `BraintreePaymentFlow` and `PayPalDataCollector` frameworks
After:
- 3DS via SPM: Include the `BraintreeThreeDSecure` framework
- PayPal via SPM: Include the `BraintreePayPal` framework
- Local Payments via SPM:  Include the `BraintreePaymentFlow` framework
- Add `PPRiskMagnes` binary as target to SPM libraries which require PayPalDataCollector.
@scannillo

Streamline SPM imports

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalDriver.m
Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalDriver.h
UnitTests/BraintreePayPalTests/BTPayPalDriver_Tests.swift

* Remove `BTPayPalDriver.requestOneTimePayment` in favor of `tokenizePayPalAccount` on `BTPayPalDriver`
* Remove `BTPayPalDriver.requestBillingAgreement` in favor of `tokenizePayPalAccount` on `BTPayPalDriver`
I didn't think this is worthy of a MIGRATION guide update since the methods were already deprecated and the new methods are documented how to use in the V5_MIGRATION guide.
@scannillo & Katy Perry

Remove deprecated PayPal checkout methods

---

.github/ISSUE_TEMPLATE/bug_report.md

- Lately, we have to follow up most iOS inquiries asking which mac type they're using for development (Intel or M1). This PR adds that criteria to the GH Issue template.
@scannillo

Add Mac Processor Type to Issue Template

---

DEVELOPMENT.md

Prior - we had release instructions in 2 places, this repo itself & the knowledge repo. The knowledge repo had instructions for releasing the Carthage binaries to hosted-mobile-assets.
Let's consolidate them all to one place.
@scannillo

Consolidate Release Instructions to Knowledge Repo

---

Demo/UI Tests/Helpers/BTUITest.swift
Demo/UI Tests/Venmo UI Tests/Venmo_UITests.swift

- Simplify `XCTestCase` helper methods
- Add `waitForElementToBeHittable` timeout to all button presses in the UI Venmo test flow (in hopes to reduce UI test flakiness on CI)
@scannillo @sarahkoop @jaxdesmarais

Fix Flakey Venmo UI Tests

---

CHANGELOG.md
README.md

- This PR clarifies our README and CHANGELOG to explicitly state that v6 requires Carthage merchants use `xcframeworks`. 
- _Note:_ `xcframework`s are required by Apple for M1 support. `.framework` use is discouraged since Xcode 13 and requires some weird workarounds to get working. Let's follow Apple's standards.
@scannillo

Clarify Carthage Instructions - Require `xcframework`s

---

CHANGELOG.md
Sources/BraintreeCard/BTCard.m
UnitTests/BraintreeCardTests/BTCardClient_Tests.swift
UnitTests/BraintreeCardTests/BTCard_Tests.swift
UnitTests/BraintreeUnionPayTests/BTCardClient_UnionPayTests.swift

- The iOS SDK sets expiration date, month, and year for non-graphQL card tokenization requests. Having all three of these set is not allowed for expiration date validation in the gateway. We only set month and year on Android and JS. This PR updates iOS to align with those and resolve that validation error (fixes: #772)
- @sarahkoop 

Remove Duplicate Expiration Date

---

CHANGELOG.md
Sources/BraintreeThreeDSecure/BTThreeDSecureAuthenticateJWT.m
Sources/BraintreeThreeDSecure/BTThreeDSecureV2Provider.m

- Add checks to confirm success/failure handlers are not nil before invoking in Cardinal authentication flow (fixes #769)
- Cardinal is still investigating the underlying cause of this issue, but until we get an updated SDK, the nil checks should prevent merchant apps from crashing when the authentication flow is invoked again after we've set the handlers to nil. 
**Note**: We don't currently have a test suite for `BTThreeDSecureV2Provider`. We tried to create one, but there are limitations in mocking the required Cardinal classes to invoke the delegate method. 
- @jaxdesmarais 
- @sarahkoop

Add Nil Check for Success/Failure Handlers in 3DS Flow

---

CHANGELOG.md
Sources/BraintreeCard/BTCardClient.m
Sources/BraintreeCard/Public/BraintreeCard/BTCardClient.h
UnitTests/BraintreeCardTests/BTCardClient_Tests.swift

- Add explicit error case for error code returned from Gateway when a card already exists in the vault.
- @jaxdesmarais 
- @sarahkoop

Add `BTCardClientErrorTypeCardAlreadyExists`

---

CHANGELOG.md
Sources/BraintreeCard/BTCardClient.m

- Updated error response construction
Note: Previously, when hitting the GQL tokenization call, we were not getting the error response back in the expected format. Instead it was being constructed the same as non-GQL api calls. Now we should correctly handle either format when constructing the errors as well as throw a default error if the response is `nil`.
- @sarahkoop @jaxdesmarais

Fix card already exists error construction

---

README.md
Sources/BraintreeCard/Public/BraintreeCard/BTAuthenticationInsight.h
Sources/BraintreeCard/Public/BraintreeCard/BTCard.h
Sources/BraintreeCore/BTPostalAddress.m
Sources/BraintreePaymentFlow/Public/BraintreePaymentFlow/BTLocalPaymentRequest.h
Sources/BraintreeThreeDSecure/BTThreeDSecurePostalAddress.m
V5_MIGRATION.md

- Update URLs from `developers.braintreepayments.com` to the correct `developer.paypal.com` URLs
- ~[ ] Added a changelog entry~ I do not think we need a changelog for this since no behavior changed we are just fixing links, but can add an entry if someone feels strongly about it
- @Epreuve @jaxdesmarais

Update braintreepayments URLs to paypal URLs

---

CHANGELOG.md
Demo/Application/Base/Base View Controllers/BraintreeDemoPaymentButtonBaseViewController.h
Demo/Application/Base/Base View Controllers/BraintreeDemoPaymentButtonBaseViewController.m
Demo/Application/Features/3D Secure/BraintreeDemoThreeDSecurePaymentFlowViewController.m
Demo/Application/Features/Views/BTCardFormView.swift

- Add 3D Secure v1 and v2 card autofill buttons to demo app
|-----|-----|

Add 3DS Autofill Buttons to Demo App

---

CHANGELOG.md
Demo/Application/Features/Venmo - Custom Button/BraintreeDemoCustomVenmoButtonViewController.m
Demo/Demo.xcodeproj/project.pbxproj
Demo/UI Tests/Venmo UI Tests/Venmo_UITests.swift
Sources/BraintreeCore/BTAPIClient.m
Sources/BraintreeCore/BTAnalyticsService.m
Sources/BraintreeCore/BTHTTP.m
Sources/BraintreeVenmo/BTVenmoDriver.m
UnitTests/BraintreeCoreTests/BTAnalyticsMetadataSpec.m
UnitTests/BraintreeCoreTests/BTAnalyticsService_Tests.m
UnitTests/BraintreeCoreTests/BTHTTPSpec.m
UnitTests/BraintreeVenmoTests/BTVenmoDriver_Tests.swift

- Update demo app to vault Venmo and use Payment Context
- Update demo app to not embed & sign Magnes framework (static framework should not be embedded)
- Update configuration cache request policy
- Moved logic for dispatch queue of configuration calls
- Remove unnecessary flushing of analytics when app enters background
- Throttle requests for configuration to reduce load on servers and network connection lost errors
- Add analytics events for network connection lost errors in Venmo flow
**Note:** The scope of impact for this is older devices running older iOS and Venmo app versions
- @jaxdesmarais 
- @sarahkoop

Update Configuration Threading Logic

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreeCoreSwift.xcscheme
Demo/Demo.xcodeproj/project.pbxproj
Package.swift
SampleApps/CarthageTest/Cartfile
SampleApps/CarthageTest/CarthageTest.xcodeproj/project.pbxproj
SampleApps/CarthageTest/CarthageTest/ViewController.swift
SampleApps/SPMTest/SPMTest.xcodeproj/project.pbxproj
Sources/BraintreeCoreSwift/BTAPIClientSwift.swift

Merging into `next-major-version`
- Created a temporary module `BraintreeCoreSwift` to hold Swift code while we convert the Core Module.
~- [ ] Added a changelog entry~ This module will be removed once the conversion is done, so no changelog is necessary.
- @jaxdesmarais 
- @mattwylder

Create temporary `BraintreeCoreSwift` module

---

Demo/Application/Base/BraintreeDemoAppDelegate.m
Demo/Application/Base/BraintreeDemoContainmentViewController.m
Demo/Application/Base/Settings/BraintreeDemoSettings.swift
Demo/UI Tests/PayPal UI Tests/PayPal_Checkout_UITests.swift
Demo/UI Tests/PayPal UI Tests/PayPal_Vault_UITests.swift

Now that the tokenization key used in the Gateway has a PayPal account linked, our UI tests have started failing as it expects the mocked flow. PayPal webviews cache data heavily so UI testing that would be quite difficult. Instead we can use a tokenization key with the mocked PayPal flow attached for the PayPal UI tests. The tokenization key used here is listed under the username `devs` in 1pass.

Update PayPal UI Test Tokenization Key

---

.github/workflows/build.yml
.github/workflows/tests.yml

- Updated `checkout` action in test and build workflows to v3 with use of parameters to specify use of source repo
- Removed `workflow_dispatch` GitHub actions event, as it was unused and didn't work.

Fix CI on PRs from Forks

---

.github/workflows/build.yml
.github/workflows/tests.yml
CHANGELOG.md
Demo/Application/Features/Fraud Protection - BTDataCollector/BraintreeDemoBTDataCollectorViewController.m
Demo/Application/Features/SEPA Direct Debit/BraintreeDemoSEPADirectDebitViewController.swift
Sources/BraintreeDataCollector/BTDataCollector.m
Sources/BraintreeDataCollector/BTDataCollector_Internal.h
Sources/BraintreeSEPADirectDebit/BTSEPADirectDebitClient.swift
Sources/BraintreeSEPADirectDebit/WebAuthenticationSession.swift

- Add support for Xcode 14 & iOS 16
- Tested all flows on device running iOS 16
- Removed deprecation warnings in Xcode 14
Note: These updates do not drop bitcode support - once we bump the minimum Xcode version to Xcode 14 for merchants, we will drop bitcode support.
- @scannillo @mattwylder @jaxdesmarais

Add support for Xcode 14 & iOS 16

---

Demo/MockVenmo/AppSwitcher.swift
Demo/UI Tests/Venmo UI Tests/Venmo_UITests.swift

- Due to security updates to Venmo we can no longer use the static payment context ID used previously as the ID is tied to a different merchant ID than the one used in the test.

Update Venmo UI Test

---

CHANGELOG.md
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutClient.swift

- Remove exit survey when canceling PayPal Native Checkout flow
|-----|-----|
|![Simulator Screen Recording - iPhone 13 - 2022-09-29 at 08 20 49](https://user-images.githubusercontent.com/20733831/193042697-3e7b5aa5-cd92-4b6e-b040-fde8d0ad06e9.gif)|![Simulator Screen Recording - iPhone 13 - 2022-09-28 at 16 04 37](https://user-images.githubusercontent.com/20733831/193042752-450a9fa8-dac3-49f1-980d-6c6f401e3ae2.gif)|

Disable PayPal Native Checkout Exit Survey

---

Braintree.xcodeproj/project.pbxproj
CHANGELOG.md

- Resolve Invalid Bundle error when uploading to the App Store
We were seeing the following error when uploading the app to TestFlight via App Store Connect:
```
Invalid Bundle. The bundle at 'Demo.app/Frameworks/BraintreeSEPADirectDebit.framework' contains disallowed file 'Frameworks'
```
This was due to `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` being set to `YES` in the `BraintreeSEPADirectDebit` module. Changing this value to `NO` allowed us to upload the Demo App to TestFlight as expected as suggested in [this Apple Forum thread](https://developer.apple.com/forums/thread/17732).

BraintreeSEPADirectDebit - Resolve Invalid Bundle with App Store Upload

---

CHANGELOG.md
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeRequest.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeTokenizationClient.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeCheckoutRequest_Tests.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeVaultRequest_Tests.swift

-  This PR fixes the nesting of two keys in the Native Checkout module. Previously, the `getBaseParameters` function returned a dictionary where two keys were mapped at an incorrect depth. This PR fixes that, and correctly moves `correlation_id` and `merchant_account_id` up one level in the parameters dictionary.
- @jonathajones

Moving `correlationId` and `merchant_account_id` up one level

---

Sources/BraintreeCore/Public/BraintreeCore/BTAPIClient.h

- This docstring was missed when removing support for PayPal UATs/ID Tokens
@scannillo

Remove unsupported ID Token reference

---

.github/workflows/release.yml

- Update github release workflow to update SDK version during the release process
Can test locally by pulling down this branch and running the following in root directory of the project:
```
sed -i '' 's/braintreeSDKVersion: String =.*/braintreeSDKVersion: String = "MY_SUPER_COOL_SDK_VERSION"/' Sources/BraintreeCore/BTCoreConstants.swift
```

Update Release Workflow to Update SDK Version

---

CHANGELOG.md
Demo/Application/Features/PayPal - Native Checkout/BraintreeDemoPayPalNativeCheckoutViewController.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutRequest.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeOrderCreationClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeRequest.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeTokenizationClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeTokenizationRequest.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeVaultRequest.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeCheckoutClient_Tests.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeCheckoutRequest_Tests.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeTokenizationClient_Tests.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeVaultRequest_Tests.swift

- Fix subclassing bug where merchants using CocoaPods were seeing the error "Cannot find interface declaration" with subclassed Obj-C class modules in Swift modules ([CocoaPods issue #11672](https://github.com/CocoaPods/CocoaPods/issues/11672))
- Rename `riskCorrelationId` to `riskCorrelationID`
- This fix was tested in a local cocoapods project pointing to the latest commit of this branch - the project now builds as expected without emitting any "Cannot find interface declaration" errors

Fix Subclassing CocoaPods Bug in Native Checkout Module

---

Braintree.xcodeproj/project.pbxproj
Sources/BraintreeSEPADirectDebit/BTSEPADirectDebitConstants.swift
Sources/BraintreeSEPADirectDebit/BTSEPADirectDebitRequest.swift
Sources/BraintreeSEPADirectDebit/SEPADirectDebitAPI.swift
Sources/BraintreeSEPADirectDebit/WebAuthenticationSession.swift
UnitTests/BraintreeSEPADirectDebitTests/SEPADirectDebitAPI_Tests.swift

- We don't need to access the app's `Bundle.main.bundleIdentifier` for `ASWebAuthenticationSession` flows 🎉 
- Replace `Bundle.main.bundleIdentifier` inspection with custom SDK scheme (re-used the same scheme that we already use in BraintreePayPal and BraintreePayPalNativeCheckout)
- Added missing test for the URL and POST body of the request to `"v1/sepa_debit"`
Jax, I know you mentioned there is difficulty testing this. I was able to go through the sandbox flow successfully. Let me know if there is anything else I should be testing.
@scannillo

Remove `Bundle.main.bundleIdentifier` inspection from SEPA module

---

CHANGELOG.md
Demo/Application/Features/UnionPay/BraintreeDemoUnionPayViewController.m
IntegrationTests/BraintreeUnionPay_IntegrationTests.m
Sources/BraintreeCard/BTCardClient.m
Sources/BraintreeCard/Public/BraintreeCard/BTCardClient.h
Sources/BraintreeDataCollector/BTDataCollector.m
Sources/BraintreeDataCollector/Public/BraintreeDataCollector/BTConfiguration+DataCollector.h
Sources/BraintreeDataCollector/Public/BraintreeDataCollector/BTDataCollector.h
Sources/BraintreeUnionPay/BTCardCapabilities.m
Sources/BraintreeUnionPay/BTCardClient+UnionPay.m
Sources/BraintreeUnionPay/BTConfiguration+UnionPay.m
Sources/BraintreeUnionPay/Public/BraintreeUnionPay/BTCardCapabilities.h
Sources/BraintreeUnionPay/Public/BraintreeUnionPay/BTCardClient+UnionPay.h
Sources/BraintreeUnionPay/Public/BraintreeUnionPay/BTConfiguration+UnionPay.h

- Deprecate Kount related methods
- Deprecate all UnionPay classes
- Silence deprecation warnings throughout project and demo using pragma marks
- _Side note: sadly, there is no equivalent to this once we're in Swift_
- Add helpful messaging in `DEPRECATED_MSG_ATTRIBUTE` to provide merchant alternative solution
@scannillo

Deprecate Kount and UnionPay

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Cartfile
Demo/Demo.xcodeproj/project.pbxproj
Package.swift

- This PR increments the version of native checkout included in the Braintree SDK to 0.110.0. The biggest change in this version is the support for multiple clientIDs not causing a web fallback.
- vradopp

Update native checkout110

---

README.md

- Xcode 12 was deprecated in April and devs can no longer upload Apps with it.
- Since Apple doesn't support it, I don't think we need to keep this comment around for Xcode 12.
@scannillo
-

Remove Xcode 12 note in README

---

CHANGELOG.md

- This PR amends the CHANGELOG for v5.16.0 to call out that it reverts a "bug" that was introduced in v5.8.0, when we switched from dynamic to static Magnes, which is technically a breaking change.
- I called out in [GH Issue #920 ](https://github.com/braintree/braintree_ios/issues/920)that major version V6 is where we will migrate both binaries (Cardinal and Magnes) to static frameworks.
- This go-forward plan was based on our discussions in Slack.
- Let me know what y'all think!
- If this PR gets approved, I can manually update the release notes associated with the 5.16.0 tag.
@scannillo

Amend CHANGELOG entry for 5.16.0

---

Demo/Demo.xcodeproj/xcshareddata/xcschemes/Demo.xcscheme

This is very much a quality of like fix that has been annoying me. The test schemes for NXO and SEPA were always greyed out in the Demo scheme unlike the other tests which can be run from the Demo scheme. In order to run the NXO and SEPA tests you'd have to switch to the UnitTest scheme - not a huge deal but annoying enough. Now we can run these tests from the same scheme as the others.
|-----|-----|
|![Screen Shot 2023-01-19 at 8 59 15 AM](https://user-images.githubusercontent.com/20733831/213486277-4b8ba17d-59ab-4117-b7cf-419f2193d6ea.png)|![Screen Shot 2023-01-19 at 8 31 21 AM](https://user-images.githubusercontent.com/20733831/213486333-a92fb85a-2964-46ad-8fb3-89c1724b6299.png)|
> List GitHub usernames for everyone who contributed to …

Update SEPA and NXO Test Schemes

---

Sources/BraintreeAmericanExpress/BTAmericanExpressClient.swift
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeTokenizationRequest.swift
Sources/BraintreeSEPADirectDebit/SEPADirectDebitAPI.swift

- Using Xcode's timeline tool, we saw that a few files were taking 1+ second to compile. This is due to how [Swift/Xcode compiles nested dictionaries](https://github.com/apple/swift/issues/47007) - tl;dr much slower.
- This PR extracts nested dictionaries into their own constants to speed up this compile time.
- As an example, the update here to the dictionaries in `SEPADirectDebitAPI` saves us a whopping second of compile time!
- **Note for future us:** we should look into if SwiftLint has the ability to check for this anti-pattern _or_ add a custom regex rule for this - can also likely add this to our style guide

Remove Nested Dictionary Construction

---

CHANGELOG.md
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeRequest.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeCheckoutRequest_Tests.swift

- A merchant reported an error where setting `BTPayPalNativeVaultRequest.shippingAddressOverride` as `nil` was throwing an error. Looking at the dictionary construction we were incorrectly constructing the dictionaries in this case resulting in an empty dictionary being passed as the "shipping_address" which is invalid.
- There were some other dictionaries where we weren't checking for `nil` first so made some updates in both the `BTPayPalNativeVaultRequest` and BTPayPalNativeCheckoutRequest` to ensure the dictionaries were constructed as appropriate for the values in the requests.
- Added a unit tests for the specific `request.shippingAddressOverride = nil` case initially reported

Fix NXO Dictionary Construction

---

.github/workflows/release.yml

During the 5.x release today the [release blew up on the last step](https://github.com/braintree/braintree_ios/actions/runs/3998282595/jobs/6860714412) (womp womp). We got the following error:
```
sourcekitten: A full installation of Xcode.app 14.0 is required to compile
this software. Installing just the Command Line Tools is not sufficient.
Xcode 14.0 cannot be installed on macOS 11.
You must upgrade your version of macOS.
```
tl;dr is that [Sourcekitten released a new version](https://github.com/jpsim/SourceKitten/releases/tag/0.34.0) with the following requirement: "SourceKitten now requires Swift 5.7 or higher to build.". 
Our CI for version 5.x uses Xcode 13. We went on an adventure and found out that it's actually quite difficult to specify an old version with Homebrew (more womp …

Update Release Workflow (5.x)

---

CHANGELOG.md

- Looks like a duplicate for `BraintreeUnionPay` made it's way into the CHANGELOG
@scannillo

Remove duplicate CHANGELOG entry

---

.github/workflows/release.yml

The 5.x [publish reference docs step](https://github.com/braintree/braintree_ios/actions/runs/4055780046/jobs/6979378871) failed again. 😭 We were doing the following: sudo xcode-select -switch /Applications/Xcode_14.0.app but have the runner set to macOS-11 which [does not support Xcode 14](https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md#xcode). We will need to be in the [MacOS-12 runner](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode) for Xcode 14 support.
This PR separates the docs publishing into it's own job ([we do something similar in Android release](https://github.com/braintree/braintree_android/blob/master/.github/workflows/release.yml) and the [iOS …

GitHub Actions Release Update to use MacOS-12 for Reference Docs (5.x)

---

README.md

- V4 is officially "unsupported" based on our timelines. We have gotten a few inbounds about this, and our README was out of date.
@scannillo

Mark v4 as unsupported version

---

Sources/BraintreeSEPADirectDebit/BTSEPADirectDebitClient.swift

- Doing some testing earlier I noticed we missed a docstring with the ASWeb changes to remove context from the client. We no longer pass in a context and were missing docs on returning a completion.

Update SEPA Docstring

---

CHANGELOG.md
Sources/BraintreeCore/BTMutableClientMetadata.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutRequest.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeVaultRequest.swift

- Doing some testing in Xcode 14.3 we see the error `Fixes error `@objcMembers attribute used without importing module 'Foundation'` in Xcode 14.3+` - we need to import Foundation in these places to avoid this error.
From [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes):
> An explicit import of Foundation is now required if APIs from Foundation are used in a manifest. 

Xcode 14.3 Import Error

---

Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutAccountNonce.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeCheckoutAccountNonce_Tests.swift

- Expose `payerID` property on `BTPayPalNativeCheckoutAccountNonce` publicly
- Expose all properties on `BTPayPalNativeCheckoutAccountNonce` to Objective-C
- Add test file for `BTPayPalNativeCheckoutAccountNonce`

`BTPayPalNativeCheckoutAccountNonce` Updates

---

README.md

- Add link to required M1 Mac workaround for running `pod install`
- Fix indentation of numeric list under `# Demo` header
- Add additional step for selecting the `Demo` target
- PR for adding these changes to V5 (#973)
@scannillo

[V6] Add M1 CocoaPods workaround to README

---

V6_MIGRATION.md

- Update method signature style of the `V6_MIGRATION` guide to match the Apple method signature syntax (example [here](https://developer.apple.com/documentation/passkit/pkpaymentauthorizationcontroller/1649455-canmakepayments))
- Other general cleanup

Update Migration Guide

---

Braintree.xcodeproj/project.pbxproj
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreeAmericanExpress.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreeApplePay.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreeCard.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreeCore.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreeDataCollector.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreePayPal.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreePayPalNativeCheckout.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreePaymentFlow.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreeSEPADirectDebit.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreeTestShared.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreeThreeDSecure.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/BraintreeVenmo.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/IntegrationTests.xcscheme
Braintree.xcodeproj/xcshareddata/xcschemes/UnitTests.xcscheme
Demo/Demo.xcodeproj/xcshareddata/xcschemes/Demo.xcscheme
Demo/Demo.xcodeproj/xcshareddata/xcschemes/MockVenmo.xcscheme
Demo/Demo.xcodeproj/xcshareddata/xcschemes/UITests.xcscheme

- Resolves the following Xcode warnings:
- `Directory not found for option '-f/braintree_ios/Frameworks/FatFrameworks'`
- `Skipping duplicate build file in Compile Sources build phase: braintree_ios/Sources/BraintreeVenmo/BTVenmoAccountNonce.swift`
- `Skipping duplicate build file in Compile Sources build phase: braintree_ios/Sources/BraintreeVenmo/BTVenmoRequest.swift`
- `Braintree.xcodeproj Update to recommended settings`

Resolve Xcode Warnings

---

Demo/Application/Features/PayPal - Checkout/BraintreeDemoPayPalCheckoutViewController.swift
Demo/Application/Features/PayPal - Pay Later/BraintreeDemoPayPalPayLaterViewController.swift
Demo/Application/Features/PayPal - Vault/BraintreeDemoPayPalVaultViewController.swift
Sources/BraintreeAmericanExpress/BTAmericanExpressClient.swift
Sources/BraintreeApplePay/BTApplePayClient.swift
Sources/BraintreeCore/BTAnalyticsService.swift
Sources/BraintreeCore/BTHTTP.swift
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeOrderCreationClient.swift
Sources/BraintreeVenmo/BTVenmoClient.swift

- Add missing [weak capture lists ](https://www.hackingwithswift.com/articles/179/capture-lists-in-swift-whats-the-difference-between-weak-strong-and-unowned-references)when holding references in `BTAPIClient.fetchOrReturnRemoteConfiguration()`'s non-escaping closure to avoid retain cycle.
- Use new Swift 5.8 `guard let self` shorthand.
@scannillo

Add capture lists to `fetchOrReturnRemoteConfiguration()` calls

---

Braintree.xcodeproj/project.pbxproj
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutAnalytics.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeOrderCreationClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeTokenizationClient.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeCheckoutAnalytics_Tests.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeCheckoutClient_Tests.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeOrderCreationClient_Tests.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeTokenizationClient_Tests.swift

These changes are going into the fpti-feature branch which will get merged once we audit all modules and make the switch to the FPTI endpoints
- Update PayPalNativeCheckout analytic events to prepare switch to FPT
- Update tests
- Bucketed all analytic events sent before callbacks into 3 categories of final events: tokenizeFailed, tokenizeSucceeded, tokenizeCanceled.
@KunJeongPark

PaypalNativeCheckout analytics audit

---

Sources/BraintreePayPalNativeCheckout/BTPayPalNativeOrderCreationClient.swift

- The native checkout order creation client was being weakly retained by the `fetchOrReturnRemoteConfiguration` request. This causes the order creation client to be deallocated, as it was created locally up the chain. The solution here is to strongly capture `self` in the completion of `fetchOrReturnRemoteConfiguration` - this does not risk a retain cycle as the closure is not being retained by the client
- @jonathajones

Removing weak self on native order creation client

---

Braintree.xcodeproj/project.pbxproj
Sources/BraintreeVenmo/BTVenmoAnalytics.swift
Sources/BraintreeVenmo/BTVenmoClient.swift
UnitTests/BraintreeVenmoTests/BTVenmoAnalytics_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoClient_Tests.swift

Summary of changes
These changes are going into the fpti-feature branch. Which will get merged in once we audit all modules and make the switch to the FPTI endpoints
-Update Venmo analytics events to prepare for switch to FPTI
-Update tests
-Bucketed all analytic events sent before callbacks into 3 categories counted in conversion rates:
tokenizeFailed, tokenizeSucceeded and appSwitchCanceled
Checklist
~[ ] Added a changelog entry~
Authors
@KunJeongPark @sshropshire

Venmo analytics audit

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/tests.yml
CHANGELOG.md
README.md

- On April 25, 2023 Apple is mandating that apps submitted to the App Store must be built with Xcode 14.1 or higher (Swift 5.7.1+)
- [See news article](https://developer.apple.com/news/?id=jd9wcyov#:~:text=Starting%20April%2025%2C%202023%2C%20iOS,on%20the%20Mac%20App%20Store)
@scannillo

Drop Xcode 13 & require Xcode 14.1

---

Sources/BraintreeCore/BTClientMetadataIntegration.swift
UnitTests/BraintreeCoreTests/BTClientMetadata_Tests.swift

- Remove `BTClientMetadataIntegration.dropin2`
- For V6, we will just use `dropin` (it's less confusing)
- Remove `BTClientMetadataIntegration.unknown`
- This is never sent. Verified in SPLUNK.
@scannillo

Remove unused `BTClientMetadataIntegration` types

---

Sources/BraintreeCore/BTAppContextSwitchClient.swift
Sources/BraintreeVenmo/BTVenmoClient.swift
V6_MIGRATION.md

The migration guide should only include the basics of updating an integration, while the CHANGELOG calls out every change. There were a few places we could streamline/simplify our migration guide.
- Remove Amex, ApplePay, Card module notes from Migration guide
- These were just method renames already called out in the CHANGELOG. These method renames are similar enough to the V5 method name that auto-fill should be sufficient.
- Rename `Payment Flow` --> `3DS & Local Payments` header for merchant clarity
- Remove BraintreeCore section
- These aren't merchant-facing changes
@scannillo

Cleanup V6 Migration Guide

---

.github/workflows/release.yml

The docs job has been failing for a while and we've needed to manually complete this step each time we do a release. It seems like it was always attempting to pull the release tag before it was generated vs running the job after the other job completed. Now that we require Xcode 14.1 in our `release.yml` we can remove this as a separate job as it was only done because SourceKitten required a higher Xcode + Swift version.

Update Docs Portion of GitHub Release

---

Braintree.xcodeproj/project.pbxproj
SampleApps/CarthageTest/CarthageTest.xcodeproj/project.pbxproj
SampleApps/CarthageTest/CarthageTest/ViewController.swift
SampleApps/SPMTest/SPMTest/ViewController.swift

- Based on the [SPM bug](https://paypal.sharepoint.com/:w:/r/sites/BTSDK/_layouts/15/Doc.aspx?sourcedoc=%7B006D11FE-7148-456F-B191-B9E77CC67A71%7D&file=iOS%20v6%20Beta%20SPM%20Bug.docx&action=default&mobileredirect=true) we found earlier in the conversion process, we realized that we have no way to "smoke test" these integrations as our Sample Apps don't do much
- This adds the basic structure of creating all of our clients (which would have caught the bug)
- This also acts as a bit more robust sample app vs what we had previously with no implementation
- In the future we can decide if it makes sense to add more to these sample apps

Update Test Apps to Add Basic Client Creation

---

Braintree.xcodeproj/project.pbxproj
Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Remove unnecessary `sendAnalyticsEvent()` helper method from BTPayPalClient
- This was missed in our [PayPal Web flow analytics audit PR](https://github.com/braintree/braintree_ios/pull/977)
- Sort files in `Sources/BraintreePayPal` alphabetically
@jaxdesmarais @scannillo

Remove unnecessary `sendAnalyticsEvent` helper method

---

SampleApps/CarthageTest/CarthageTest.xcodeproj/project.pbxproj

- In trying to upload our CarthageSample app to TestFlight, I encountered several local build errors:
- These were fixed by relinking `BraintreeSEPADirectDebit.xcframework`, `BraintreePayPalNativeCheckout.xcframework`, and `BraintreeLocalPayment.xcframework` into the project's `Frameworks, Libraries, and Embedded Content` settings.
- The `PayPalCheckout.xcframework` wasn't linked at all
@scannillo

Fix CarthageTest app local build

---

Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Demo/Application/Features/Venmo - Custom Button/BraintreeDemoCustomVenmoButtonViewController.m
SDK_ERROR_CODES.md
Sources/BraintreeCore/BTGraphQLHTTP.swift
Sources/BraintreeCore/BTJSON.swift
Sources/BraintreeVenmo/BTConfiguration+Venmo.swift
Sources/BraintreeVenmo/BTVenmoAccountNonce.swift
Sources/BraintreeVenmo/BTVenmoClient.swift
Sources/BraintreeVenmo/BTVenmoError.swift
Sources/BraintreeVenmo/BTVenmoLineItem.swift
Sources/BraintreeVenmo/BTVenmoRequest.swift
UnitTests/BraintreeVenmoTests/BTConfiguration+Venmo_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoAccountNonce_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoClient_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoLineItem_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoRequest_Tests.swift

Adds the following fields to BTVenmoRequest to be used in createPaymentContext:
2 new address collection fields -
collectCustomerBillingAddress
collectCustomerShippingAddress
and 6 new fields for transaction amount and line items -
lineItems
subTotalAmount
discountAmount
taxAmount
shippingAmount
totalAmount
Note: Should not be merged until [this GraphQL PR](https://github.braintreeps.com/braintree/cosmos-apps/pull/8614) is …

Add address, amount and line item fields to Venmo createPaymentContext

---

.spi.yml

Braintree iOS is currently accessible via the Swift Package Index (https://swiftpackageindex.com/braintree/braintree_ios). This PR enhances our Swift Package Index experience by supporting it's auto-hosting DocC feature.
- Add a `.spi.yml` file
- [See SPI docs](https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation/) on how this auto-hosted, auto-generated docs works. It's really neat! We could even have this replace our hosted reference docs entirely 👀. 
Once merged into `master` our SPI landing site will add this button:
The hosted docs & new button won't be visible until merged.
@scannillo

Add `.spi.yml` for Swift Package Index docs

---

CHANGELOG.md
Sources/BraintreeSEPADirectDebit/BTSEPADirectDebitRequest.swift
Sources/BraintreeSEPADirectDebit/SEPADirectDebitAPI.swift
UnitTests/BraintreeSEPADirectDebitTests/SEPADirectDebitAPI_Tests.swift

- Add the ability to set a locale when creating a SEPA direct debit request

Add `locale` to `BTSEPADirectDebitRequest`

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalAccountNonce.swift
Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Fixes #1063
- We were not constructing the `parameters` dictionary as expected, which resulted in missing account fields in the body we were getting back from the API
Account fields are now populating as expected when returned by the API:

Fix PayPal Account Nonce Missing Data

---

README.md
SampleApps/CarthageTest/Cartfile
SampleApps/SPMTest/SPMTest.xcodeproj/project.pbxproj

We renamed our default branch from `master` to `main`. This PR:
- Updates our internal Carthage & SPM sample apps to specify `main`
- Update GitHub repo URL links in README 
@scannillo @jaxdesmarais

Rename `master` to `main` cleanup

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Cartfile
Demo/Demo.xcodeproj/project.pbxproj
Package.swift

This build enables the native flows for buyers in the US and Canada. EU buyers will see a web fallback experience.
The following changes are included in this release:
Ensures return relevant billing information such as First Name, Last Name, and Email in the onApprove callback.
Removed extensions on Foundation types from our public interface.
Deprecated the following order actions:
- Patch
- Capture
- Authorize
- GetDetails …

Update PayPalCheckout to 1.0.0

---

CHANGELOG.md
Sources/BraintreeCore/BTAppContextSwitcher.swift

- Remove `nodoc` and `@_documentation(visibility: private)` annotations from `BTAppContextSwitcher. handleOpen(_url:)` and `BTAppContextSwitcher.handleOpenURL(context:)`
- These were public in V5 ([see BTAppContextSwitcher.h](https://github.com/braintree/braintree_ios/blob/752a71f2381dbef641c1865c38ce2d88779013b4/Sources/BraintreeCore/Public/BraintreeCore/BTAppContextSwitcher.h#L62-L76))
@scannillo

Un-hide public docs for BTAppContextSwitcher `handleOpenURL` methods

---

.gitignore
Braintree.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Braintree.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

- The [docs step of the release](https://github.com/braintree/braintree_ios/actions/runs/5512469326/jobs/10049340682) failed yesterday with the error `Your local changes to the following files would be overwritten by checkout: Braintree.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved`
- Remove `xcshareddata` from `gitignore` so updates to NXO result in the `Package.resolved` file updating as expected - `xcshareddata` contains target configurations that we want to persist across all users of the target and should be checked in
- Add missing `IDEWorkspaceChecks.plist`
- Bump versions in `Package.resolved`

Update `Package.resolved` with Correct NXO Version

---

CHANGELOG.md
Sources/BraintreeCore/Analytics/BTAnalyticsService.swift
Sources/BraintreeCore/BTConfiguration.swift
UnitTests/BraintreeCoreTests/BTConfiguration_Tests.swift

While creating analytics dashboards, we realized that the BT & PPCP SDKs differ in the values we are sending for the `merchant_sdk_env` key to FPTI. BT Mobile SDKs are sending: production & sandbox; PPCP mobile SDKs are sending live & sandbox. 
To easily look at our analytics cross products, we want to keep things the same as much as possible.
- Send `live` instead of `production` in the FPTI payload
- This makes more sense to me than sending `production` from the PPCP SDKs for a few reasons
- In FPTI, "live" is the accepted name for the FPTI Data Service's "live" environment
- Alignment with existing PP products already on FPTI (PP JS, NXO, etc)
@scannillo

Send `live` over `production` in FPTI payload

---

.github/workflows/tests.yml

- CI started 💩 itself out of nowhere - did some research and found [this issue on the GitHub actions runner](https://github.com/actions/runner-images/issues/8023)
- Seems like `macos-13` is now defaulting to iOS 17... which is still in beta so buggy AF
- We can hardcode our OS in `xcodebuild` as indicated in that thread [here](https://github.com/actions/runner-images/issues/8023#issuecomment-1662478605) - hopefully in a later Xcode beta/GA this will be resolved and we can go back to letting CI do it's normal thing if we want 

Update Test Workflow

---

Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Demo/Application/Features/Venmo - Custom Button/BraintreeDemoCustomVenmoButtonViewController.m
Sources/BraintreeCore/BTGraphQLHTTP.m
Sources/BraintreeVenmo/BTConfiguration+Venmo.m
Sources/BraintreeVenmo/BTVenmoAccountNonce.m
Sources/BraintreeVenmo/BTVenmoDriver.m
Sources/BraintreeVenmo/BTVenmoLineItem.m
Sources/BraintreeVenmo/Public/BraintreeVenmo/BTConfiguration+Venmo.h
Sources/BraintreeVenmo/Public/BraintreeVenmo/BTVenmoAccountNonce.h
Sources/BraintreeVenmo/Public/BraintreeVenmo/BTVenmoDriver.h
Sources/BraintreeVenmo/Public/BraintreeVenmo/BTVenmoLineItem.h
Sources/BraintreeVenmo/Public/BraintreeVenmo/BTVenmoRequest.h
Sources/BraintreeVenmo/Public/BraintreeVenmo/BraintreeVenmo.h
UnitTests/BraintreeCoreTests/BTConfiguration_Tests.swift
UnitTests/BraintreeCoreTests/BTGraphQLHTTP_Tests.m
UnitTests/BraintreeVenmoTests/BTConfiguration+Venmo_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoAccountNonce_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoDriver_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoLineItem_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoRequest_Tests.swift

This is the same change as PR #974, #1081, and #1075 - these new parameters are required in the Drop-in. Since there is not a plan to update Drop-in to v6 due to the Swift > Obj-C > Swift bug, we need to make the same changes in v5 to port these parameters to the Drop-in.
- Add `BTVenmoLineItem`
- Add new parameters to `BTVenmoRequest`
- Add `isVenmoEnrichedCustomerDataEnabled` to `BTConfiguration+Venmo`
- Update error parsing in `BTGraphQLHTTP`
- Add `billingAddress` and `shippingAddress` to `BTVenmoAccountNonce`
- Add logic to build ECD request in `BTVenmoDriver`
- Add new `BTVenmoDriverErrorTypeEnrichedCustomerDataDisabled` error
- Add ECD to Demo app
- Add new `BTConfiguration+Venmo_Tests` for ECD
- Add new `BTVenmoLineItem_Tests`
- Add error test for alternatively constructed GQL …

[5.x] Add Venmo Enriched Customer Data to BTVenmoRequest

---

Demo/Application/Base/Base View Controllers/BraintreeDemoPaymentButtonBaseViewController.m
Demo/Application/Features/Apple Pay - PassKit/BraintreeDemoApplePayViewController.swift

- When updating the constraints in `BraintreeDemoPaymentButtonBaseViewController` recently, it made the Apple Pay button in the demo app giant - all other buttons render as expected
- Added leading and trailing constraints that will apply to all buttons
- Added a height constraint to the Apple Pay button so it doesn't look wild
- All of the other UIButtons render as the correct size
|-----|-----|
|![Simulator Screenshot - iPhone 15 Pro - 2023-09-22 at 11 59 00](https://github.com/braintree/braintree_ios/assets/20733831/f190bc5d-66a2-4f9a-a854-cae10153d218)|![Simulator Screenshot - iPhone 15 Pro - 2023-09-22 at 10 36 06](https://github.com/braintree/braintree_ios/assets/20733831/a4f95a34-7eb6-43a9-9d1f-eaa288b80a45)|

Fix Giant Apple Pay Button in Demo App

---

CHANGELOG.md
Sources/BraintreeCore/Analytics/BTAnalyticsService.swift
Sources/BraintreeCore/Analytics/FPTIBatchData.swift
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutError.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutRequest.swift
UnitTests/BraintreeCoreTests/Analytics/FPTIBatchData_Tests.swift
UnitTests/BraintreeCoreTests/Analytics/FakeAnalyticsService.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeCheckoutClient_Tests.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift

Currently, we cannot tie our analytics to a PayPal correlationID (aka clientMetadataID) because we are not sending the value in our analytics batch payload. We recently had a Slack inbound where this data would be extremely helpful for handoff to the underlying PP Web or PP NXO team to do further investigation on the specific PayPal transaction.
- Update `FPTIBatchData` to send `correlation_id` at the event level (I verified that I can see these values populate in FPTI event explorer)
- Update `BTAnalyticsService` to accept an optional `correlationID` param
- Send already-existant `clientMetadataID` in BTPayPalWebClient
- Collect `clientMetadataID` & send in analytics for BTPayPalNativeCheckoutClient
- We don't have a testing infrastructure for BTPayPalNativeCheckoutClient set up right …

Send PayPal `correlation_id` in analytics payload

---

Demo/Application/Features/PayPal - Native Checkout/BraintreeDemoPayPalNativeCheckoutViewController.swift

- We were calling tokenize twice in `tappedVaultCheckout` method of the `BraintreeDemoPayPalNativeCheckoutViewController`

Remove Duplicate Tokenize Call in NXO Demo

---

V6_MIGRATION.md

- Add `BTAppContextSwitcher` method name changes to Venmo section

Update V6_MIGRATION Guide

---

CHANGELOG.md
Sources/BraintreeThreeDSecure/BTThreeDSecureCardAddChallenge.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureClient.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureRequest.swift
UnitTests/BraintreeThreeDSecureTests/BTThreeDSecureClient_Tests.swift

- Add `cardAddChallengeRequested` to `BTThreeDSecureRequest`
- Deprecate `cardAddChallenge`
- Add unit test for `cardAddChallengeRequested`

Add `cardAddChallengeRequested` to `BTThreeDSecureRequest`

---

SampleApps/CarthageTest/CarthageTest.xcodeproj/project.pbxproj

- Bump CarthageTest app to iOS 14+ (the braintree_ios v6 min supported target)
- Bump CarthageTest app to Swift 5
@scannillo

Update CarthageTest App Settings

---

CHANGELOG.md
Sources/BraintreeThreeDSecure/BTThreeDSecureClient.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureRequest.swift

Follow up to PR #1122 & [this comment](https://github.com/braintree/braintree_ios/pull/1122#discussion_r1376494256)
- Deprecate `BTThreeDSecure.cardAddChallenge`
- Create internal variable for `cardAddChallenge` to use within the SDK
- Since we cannot silence deprecation warnings in Swift, Jax's PR above revealed that referencing deprecated methods & properties internally will surface errors to merchants
- This works around that limitation by only accessing the _internal_ variable for `cardAddChallenge` throughout the SDK, while still deprecating the merchant-facing public property
- Since the internal property is not deprecated, our SDK will not trigger warnings
@scannillo

Deprecate `cardAddChallenge` & add internal property

---

Sources/BraintreeCore/BTAPIClient.swift

- Looks like we forgot to remove a reference to "PayPal ID Token". This auth type is not supported.
@scannillo

Fixup - remove reference to PayPal ID Token

---

Demo/Demo.xcodeproj/xcshareddata/xcschemes/Demo.xcscheme

- We had some outdated references in our demo app scheme that can be deleted. Removed old frameworks and frameworks with incorrect/missing `BlueprintIdentifier`, added back the necessary targets with the correct reference.
- Removed duplicate references if present

Cleanup Demo App Scheme Files

---

Sources/BraintreeAmericanExpress/BTAmericanExpressAnalytics.swift
Sources/BraintreeApplePay/BTApplePayAnalytics.swift
Sources/BraintreeCard/BTCardAnalytics.swift
Sources/BraintreeLocalPayment/BTLocalPaymentAnalytics.swift
Sources/BraintreePayPal/BTPayPalAnalytics.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutAnalytics.swift
Sources/BraintreeSEPADirectDebit/BTSEPADirectAnalytics.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureAnalytics.swift
Sources/BraintreeVenmo/BTVenmoAnalytics.swift

When we initially added the analytics classes we still had some modules in Obj-C. Caseless string enums are not a thing in Obj-C so we opted to use classes for the time being. Now that the SDK is fully Swift we can use caseless enums for these constants. These are safer because they cannot be constructed and do not contain initializers. This also tends to be preferred for storing constant values (Apple has also established this pattern for namespacing in newer frameworks such as Combine).

Move Analytics to Caseless Enum

---

Braintree.xcodeproj/project.pbxproj
Sources/BraintreeCore/UIApplication+URLOpener.swift
Sources/BraintreeVenmo/BTVenmoClient.swift
UnitTests/BraintreeTestShared/FakeApplication.swift

- Move to protocol & extension to mock `UIApplication.shared`
- This let's us remove the logic that lived in `BTVenmoClient` source code which only existed for mocking
- Update `FakeApplication` to conform to new protocol
http://swiftyjimmy.com/mock-uiapplication-swift/
@scannillo

Add `URLOpener` protocol for mocking `UIApplication.shared`

---

Sources/BraintreeVenmo/BTVenmoClient.swift
UnitTests/BraintreeVenmoTests/BTVenmoClient_Tests.swift

- We just realized that we missed removing this analytic event in iOS V6 (see [GH convo in braintree_android](https://github.com/braintree/braintree_android/pull/846#discussion_r1422907840))
@scannillo

Remove missed Venmo app store analytics event

---

CHANGELOG.md
Sources/BraintreeThreeDSecure/BTThreeDSecureClient.swift

- Address GH Issue https://github.com/braintree/braintree_ios/issues/1154
- Set completion for `initializeChallenge()` func
- I tested & verified, this was indeed a bug and the callback wasn't firing prior
- 🏈 Punting on adding unit tests to this method (DTBTSDK-3286)
@scannillo

Fix unresolved callback in `BTThreeDSecureClient.initializeChallenge()`

---

.gitignore

- We don't check in this file and it's always a pain when switching b/w branches. 
- Added it to the gitignore
@scannillo

Add SPM workspace dir to gitignore

---

CHANGELOG.md
Demo/Application/Features/IdealViewController.swift
Demo/Application/Features/SEPADirectDebitViewController.swift
Demo/Application/Features/ThreeDSecureViewController.swift
Demo/Application/Features/VenmoViewController.swift
Sources/BraintreeAmericanExpress/BTAmericanExpressError.swift
Sources/BraintreeApplePay/BTApplePayError.swift
Sources/BraintreeCard/BTCardError.swift
Sources/BraintreeCore/Analytics/BTAnalyticsServiceError.swift
Sources/BraintreeCore/BTAPIClientError.swift
Sources/BraintreeCore/BTClientTokenError.swift
Sources/BraintreeCore/BTHTTPError.swift
Sources/BraintreeCore/BTJSONError.swift
Sources/BraintreeDataCollector/BTDataCollectorError.swift
Sources/BraintreeLocalPayment/BTLocalPaymentError.swift
Sources/BraintreePayPal/BTPayPalError.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutError.swift
Sources/BraintreeSEPADirectDebit/BTSEPADirectDebitError.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureClient.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureError.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureV2Provider.swift
Sources/BraintreeVenmo/BTVenmoError.swift

- Update all SDK errors to be public (fixes #1152 and #1080)
- Update all errors to conform to Equatable
- This allows for a better merchant experience as they won't need to cast to `NSError` and can do error comparison in a more Swift-y way (see Demo app ViewController updates as an example)

Make SDK Errors Public

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Cartfile
Demo/Application/Features/PayPalMessagingViewController.swift
Package.swift

- Add Carthage support for PayPal Messaging module
- Bump `Braintree.podspec`, `Package.swift`, and package dependency to `1.0.0 prerelease.6`
- This version resolves all warnings we were previously seeing in Xcode

Bump PayPal Messages to v1.0.0 prerelease.6

---

Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClient_Tests.swift

- Equivalent Android PR - https://github.com/braintree/braintree_android/pull/872
- Add checks if Venmo & PayPal apps are installed to `BTShopperInsightsClient.getRecommendedPaymentMethods()` call
@scannillo

Add app installed checks to ShopperInsightsClient

---

Braintree.xcodeproj/project.pbxproj
Sources/BraintreeAmericanExpress/BTAmericanExpressClient.swift
Sources/BraintreeAmericanExpress/BTAmexRewardsBalanceRequest.swift
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeCore/BTConfigurationRequest.swift
Sources/BraintreeCore/BTGraphQLHTTP.swift
Sources/BraintreeCore/BTHTTP.swift
UnitTests/BraintreeAmericanExpressTests/BTAmericanExpressClient_Tests.swift
UnitTests/BraintreeCoreTests/BTHTTP_Tests.swift
UnitTests/BraintreeTestShared/FakeHTTP.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift

- Replace `BTHTTP.get()` method to require `Encodable` body instead of raw dictionary param
- Add Request.swift files for the 2 `GET` requests that exist in the SDK
- `BTAmexRewardsBalanceRequest`
- `BTConfigurationRequest`
- Update tests accordingly
@scannillo

Require `Encodable` body for all `GET` requests

---

Demo/Demo.xcodeproj/project.pbxproj

- Right now the Demo app can't run on device because we don't have PayPal Checkout pulled in as a linked framework - the demo app builds as expected on simulator
- Have confirmed with this change that the Demo app no longer crashes when running on device
I spent some time exploring alternatives (using SPM or Cocoapods) for the demo app. The major downside to not using a "direct/carthage" integration is that we would need to be tied to a branch name or version vs linking the library directly like we do today. This would mean when adding features we'd need to change the branch to add the feature to our Demo app, then change it back to main/a specific version post merge in a separate PR.
IMO having to switch the branch around regularly seems like a pain as well as something that could easily …

Add PayPalCheckout to Demo App - Required to Run on Device

---

DEVELOPMENT.md
README.md

- Importing headers is no-longer part of our development process in this SDK 🥲
@scannillo

Remove ObjC headers instructions

---

Braintree.xcodeproj/project.pbxproj
UnitTests/BraintreePayPalTests/BTPayPalLineItem_Tests.swift

- The new file `BTPayPalLineItem_Tests` was not correctly added to Xcode and therefore the tests never ran as part of CI - one of the tests was wrong and should have failed, this file has now been added to Xcode and will run on CI
- Cleanup the test file based on compiler warnings

[Important] Fix UPC Tests

---

Braintree.xcodeproj/project.pbxproj
Braintree.xcodeproj/xcshareddata/xcschemes/UnitTests.xcscheme
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeCore/BTAPIClientHTTPType.swift
Sources/BraintreeCore/BTAPIRequest.swift
Sources/BraintreeCore/BTHTTP.swift
Sources/BraintreeCore/URL+IsPayPal.swift
Sources/BraintreeShopperInsights/BTEligiblePaymentsRequest.swift
Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
Sources/BraintreeShopperInsights/BTShopperInsightsRequest.swift
UnitTests/BraintreeCoreTests/BTAPIClient_Tests.swift
UnitTests/BraintreeCoreTests/BTHTTP_Tests.swift
UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClient_Tests.swift

- Update `BTAPIClient` & `BTHTTP` to support API calls to paypal.com APIs
- Add `BTEligiblePaymentsRequest` struct to house POST body for `v2/payments/find-eligible-methods` API call
- Add relevant unit tests
- Leave TODO for parsing result of API call
- API call still expected to 403 right now ⚠️ 
- Adding support for hitting a PayPal API reveals how tightly coupled our networking implementation is to BT API specifics
- A few highlights:
- `BTHTTP` & `BTGraphQLHTTP` have a lot of overlap & duplication (3 different `URLSession` configurations, 2 different `URLRequest` creation sites)
- No service-agnostic networking interface
- When time permits, I think there's room to rework things similar to how we did in a [series of PPCP PRs](https://github.com/paypal/paypal-ios/pulls?q=is%3Apr+networ …

[ShopperInsights] Add EligiblePayments API Call

---

Sources/BraintreePayPalMessaging/BTPayPalMessagingView.swift

- A couple of docstring incorrectly mentioned the initial name for this class as `Client`, updated the docstrings to be correct and ensured there were no other references to the old name

Update Docstrings for PayPal Messaging `Init`

---

Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClient_Tests.swift

- When I ran our demo app, I realized there was an issue with [this logic](https://github.com/braintree/braintree_ios/blob/2d931f498e795d3b5f843a3182c6e73614a035c9/Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift#L52-L62) where line 62 would always execute before the `Task` had a chance to complete & even if you properly returned in all conditions within the `Task` the compiler still requires an exit out of the function outside of the `Task`
- The cleanest approach (from the `BTShopperInsightsClient` perspective) is to stick with all async-await syntax
- Add an `async` version of `BTAPIClient.post()`
- Update `BTShopperInsightsClient` to use new `post()` async method
- Add unit tests
- Added failing tests first to confirm (TDD for _life_) …

[Shopper Insights] Fix return flow bug

---

CHANGELOG.md
Sources/BraintreeCore/Analytics/BTAnalyticsService.swift
Sources/BraintreeCore/Analytics/FPTIBatchData.swift
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeLocalPayment/BTLocalPaymentClient.swift
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeOrderCreationClient.swift
UnitTests/BraintreeCoreTests/Analytics/FPTIBatchData_Tests.swift
UnitTests/BraintreeCoreTests/Analytics/FakeAnalyticsService.swift
UnitTests/BraintreeLocalPaymentTests/BTLocalPaymentClient_UnitTests.swift
UnitTests/BraintreePayPalNativeCheckoutTests/BTPayPalNativeCheckoutClient_Tests.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift

- Pass `paypal_context_id` to FPTI when available:
- PayPal Web: passing either the `token` (checkout) or `ba_token` (vault) as the `paypal_context_id`
- PayPal Native: passing the `orderID` as the `paypal_context_id`
- Local Payments: passing the `paymentToken` (which is an order ID) as the `paypal_context_id`
- If we get an empty string back we will not pass an empty string to FPTI
- I have verified that we are passing this value as expected in the above flows to FPTI
- Add Unit Tests

Add `paypal_context_id` FPTI Tag

---

Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeCore/BTGraphQLHTTP.swift
Sources/BraintreeCore/BTHTTP.swift
Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClient_Tests.swift
UnitTests/BraintreeTestShared/FakeHTTP.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift

- Adds the `PayPal-Client-Metadata-Id` to the Shopper Insights API Call
- Adds appropriate unit test to ensure `PayPal-Client-Metadata-Id` is properly set to the `sessionID` 
- Adds the optional `headers` parameter to all relevant HTTP POST methods within various files
- Adds `lastPOSTAdditionalHeaders` property to `MockAPIClient` for testing purposes
- @scannillo

[DTBTSDK-3403] Send PayPal-Client-Metadata-Id to PaymentReady API Call

---

CHANGELOG.md
Sources/BraintreeVenmo/BTVenmoClient.swift
Sources/BraintreeVenmo/BTVenmoRequest.swift
UnitTests/BraintreeVenmoTests/BTVenmoClient_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoRequest_Tests.swift

- Add `isFinalAmount` to `BTVenmoRequest`
- This removes the text "Subject to change" as seen below
| Final Amount = false (default) | Final Amount = true |
|-----|-----|
|![IMG_0015](https://github.com/braintree/braintree_ios/assets/20733831/ceb32df0-0fdd-426c-b5c6-72a9cd089dca)|![IMG_0016](https://github.com/braintree/braintree_ios/assets/20733831/d06103db-64bb-4ff3-95d0-1e251e3115d8)|

Venmo Final Amount

---

Sources/BraintreeShopperInsights/BTEligiblePaymentsRequest.swift
Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClient_Tests.swift

- This PR removes the `merchantID` parameter from the Payment Ready API Request as this value is now determined by the auth fingerprint.
-~Added a changelog entry~
- @agedd

[DTBTSDK-3544] Remove merchant_id from the Payment Ready API Request

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeAmericanExpress/PrivacyInfo.xcprivacy

See Confluence doc "Xcode Privacy Manifest Support" for background on this initiative & list of entries required for each module.
- Add `PrivacyInfo.xcprivacy` file to AmericanExpress module
- _Note:_ This is the first of 11 PRs that will be made to this repo for adding a manifest file. Each module we get it's own.
- The testing done for each package manager below I think we only have to do once, for this PR. 
- Generating a privacy report via the Demo app is sufficient after this PR.
Generated an [App Privacy Report](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests#4239187) for apps using each package manager:
See how the Privacy Report looks (for just the Amex module) - [Demo-PrivacyReport 2024-02-27 …

Add Privacy Manifest to AmericanExpress module

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeApplePay/PrivacyInfo.xcprivacy

- Adds the `PrivacyInfo.xcprivacy` file to the `BraintreeApplePay` module
- Adds corresponding changes to the `podspec` and `Package.swift` files
- @agedd

Add Privacy Manifest to BraintreeApplePay Module

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeCard/PrivacyInfo.xcprivacy

See Confluence doc "Xcode Privacy Manifest Support" for background on this initiative & list of entries required for each module.
- Add `PrivacyInfo.xcprivacy` file to BraintreeCard module
- See #1196 for testing
- ~[ ] Added a changelog entry~ I think one holistic CHANGELOG entry makes more sense here
@scannillo

Add Privacy Manifest to Card module

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeCore/PrivacyInfo.xcprivacy

- Adds the `PrivacyInfo.xcprivacy` file to the `BraintreeCore` module
- Updates the `Braintree.podspec` and `Package.swift` files to include references to the Privacy Manifest file
- @agedd

[iOS] Add Privacy Manifest to BraintreeCore module

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeSEPADirectDebit/PrivacyInfo.xcprivacy

- Adds `PrivacyInfo.xcprivacy` to `BraintreeSEPADirectDebit`
- Adds corresponding `Package.swift` and `Braintree.podspec` changes
- @agedd

[iOS] Add Privacy Manifest to SEPADirectDebit module

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Package.swift
Sources/BraintreeShopperInsights/PrivacyInfo.xcprivacy

- Added PrivacyInfo.xcprivacy to ShopperInsights module
- Added changes to Podspec and Package.swift files
Privacy report generated from demo app
[Demo-PrivacyReport 2024-02-29 12-15-15_2.pdf](https://github.com/braintree/braintree_ios/files/14453098/Demo-PrivacyReport.2024-02-29.12-15-15_2.pdf)

Add Privacy Manifest to ShopperInsights Module

---

Demo/Application/Base/AppDelegate.swift
Demo/Application/Base/SceneDelegate.swift
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Demo/Demo.entitlements

- Add "Universal Link Flow" button to PayPal Web demo app - this button with open a page that will allow us to return to the app on tapping "open"
- This PR is a proof of concept that our demo app can be set up for universal linking, follow up PRs to this feature branch will build on this work
- We are currently using Fly.io for hosting this proof of concept, I have hosted the [server side code here](https://github.com/jaxdesmarais/fly-server-demo) for the time being, as this feature develops we can consider moving this to a shared space or Heroku depending on if the free tier of Fly.io is sufficient for our usecase
- This is part of the `paypal-app-switch-feature` work and will be built upon as this feature develops

Universal Links Demo

---

CHANGELOG.md
Sources/BraintreeCore/Analytics/BTAnalyticsService.swift
Sources/BraintreeCore/BTAPIClient.swift
UnitTests/BraintreeCoreTests/Analytics/BTAnalyticsService_Tests.swift
UnitTests/BraintreeCoreTests/Analytics/FakeAnalyticsService.swift
UnitTests/BraintreeCoreTests/BTAPIClient_Tests.swift

- This PR came out of [this conversation](https://github.com/braintree/braintree_ios/pull/1198#discussion_r1515426571) in a previous PR
- We found a bug where every analytic event was being sent multiple times
- The reason why was because our [sessionsQueue](https://github.com/braintree/braintree_ios/blob/8e631aac435210357524374fc73632bb97895187/Sources/BraintreeCore/Analytics/BTAnalyticsService.swift#L19) was never being wiped after events were already sent out in an API request
- This PR takes a path-of-least-resistance approach to fixing this duplicate events bug
- It uses the existing batch POST formatting, but only sends a single event per API request
- Previously we were still sending an API request every time `sendAnalyticsEvent()` was called, but with this change, the payload …

Fix bug where AnalyticsServices fires same event multiple times

---

CHANGELOG.md
Sources/BraintreeCore/Analytics/BTAnalyticsService.swift
Sources/BraintreeCore/Analytics/FPTIBatchData.swift
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutClient.swift
Sources/BraintreeVenmo/BTVenmoClient.swift
UnitTests/BraintreeCoreTests/Analytics/FPTIBatchData_Tests.swift
UnitTests/BraintreeCoreTests/Analytics/FakeAnalyticsService.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift

- Move `paypal_context_id` from `batch_params` to `event_params`
- Cleaned up implementation
- Alphabetized parameters order in `sendAnalyticsEvent`
- Update tests

Send `paypal_context_id` at Event Level

---

CHANGELOG.md

- We were investigating our Magnes versions and realized that in v5.24.0 of Braintree iOS we switched to a static version of Magnes
- Technically switching b/w static & dynamic is a breaking change, but since it's v5 and been out for awhile we'll just leave it :) 
- This PR clarifies the CHANGELOG entry for future readers
@scannillo @agedd

[main] Amend v5.24.0 CHANGELOG entry

---

CHANGELOG.md

- We were investigating our Magnes versions and realized that in v5.24.0 of Braintree iOS we switched to a static version of Magnes
- Technically switching b/w static & dynamic is a breaking change, but since it's v5 and been out for awhile we'll just leave it :) 
- This PR clarifies the CHANGELOG entry for future readers
@scannillo @agedd

[5.x] Amend v5.24.0 CHANGELOG entry

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreePayPalNativeCheckout/PrivacyInfo.xcprivacy

- Adds `PrivacyInfo.xcprivacy` to the `BraintreePayPalNativeCheckout` module
- Adds the corresponding changes to `Package.swift` and `Braintree.podspec`
- @agedd

[DTBTSDK-3585] Add Privacy Manifest to PayPalNativeCheckout module

---

Demo/Application/Base/ContainmentViewController.swift

Right now if the `FeatureViewController` cannot be found, a message is displayed "Demo not available", by providing a default as `PayPalWebCheckoutViewController` we can load a View Controller instead of returning `nil` without a super clear message to the user. This is mainly helpful for first time installs, when nothing is stored in `UserDefaults` yet or when switching between feature branches where the demo exists on a branch but not on main.

[Open Dev] Provide Default View Controller

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeVenmo/PrivacyInfo.xcprivacy

- Added `PrivacyInfo.xcprivacy` to Venmo Module
- Modified `Braintree.podspec` and `Package.swift` files
Privacy report generated from Demo app:
[Demo-PrivacyReport 2024-03-13 08-18-55_2.pdf](https://github.com/braintree/braintree_ios/files/14589896/Demo-PrivacyReport.2024-03-13.08-18-55_2.pdf)

Add Venmo Privacy Manifest File

---

CHANGELOG.md
Demo/Application/Base/AppDelegate.swift
Demo/Application/Base/SceneDelegate.swift
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreeCore/BTAppContextSwitcher.swift
UnitTests/BraintreeCoreTests/BTAppContextSwitcher_Tests.swift

This work is going into the `paypal-app-switch-feature` branch
- Add `BTAppContextSwitcher.sharedInstance.universalLink` property
- Parse path in return URL `SceneDelegate` method

[QL] Add `BTAppContextSwitcher.universalLink`

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeDataCollector/PrivacyInfo.xcprivacy

- Adds `PrivacyInfo.xcprivacy` to the `BraintreeDataCollector` module
- Adds the corresponding changes to `Package.swift` and `Braintree.podspec`
- @agedd

Add Privacy Manifest to DataCollector Module

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeLocalPayment/PrivacyInfo.xcprivacy

- Added `PrivacyInfo.xcprivacy` file to _BraintreeLocalPayment_ module
- Modified` Braintree.podspec` and `Package.swift` files
Privacy Report generated from Demo app:
[Demo-PrivacyReport 2024-03-13 12-45-03.pdf](https://github.com/braintree/braintree_ios/files/14593269/Demo-PrivacyReport.2024-03-13.12-45-03.pdf)

Add Local Payment Privacy Manifest

---

Sources/BraintreePayPal/BTPayPalClient.swift

- Was poking through our analytics for the PP App Switch workflow and found that we're sending the `"paypal:tokenize:browser-login:canceled"` event twice
@scannillo

Fix duplicate paypal cancel analytic event

---

CHANGELOG.md
Demo/Application/Base/AppDelegate.swift
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreeCore/BTAppContextSwitcher.swift
Sources/BraintreePayPal/BTPayPalVaultRequest.swift
UnitTests/BraintreeCoreTests/BTAppContextSwitcher_Tests.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift
UnitTests/BraintreePayPalTests/BTPayPalRequest_Tests.swift
UnitTests/BraintreePayPalTests/BTPayPalVaultRequest_Tests.swift

- Replace `BTAppContextSwitcher.sharedInstance.universalLink` with init:  `BTPayPalVaultRequest(userAuthenticationEmail:enablePayPalAppSwitch:universalLink:offerCredit:)`
- OG convo here: https://github.com/braintree/braintree_ios/pull/1228#discussion_r1530809502

[QL] Update `BTAppContextSwitcher.sharedInstance.universalLink` to URL Type

---

Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Per [this conversation](https://github.com/braintree/braintree_ios/pull/1234#discussion_r1537752483) we want to prefer BA tokens over EC tokens
- Tested all 3 PayPal flows (Checkout, Vault, and Pay Later) to ensure the flows still worked as expected
- Added unit test for this logic

[QL] Prefer BA Token over EC Token

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeSEPADirectDebit/PrivacyInfo.xcprivacy

- Adds the `PrivacyInfo.xcprivacy` file to `BraintreeSEPADirectDebit`
- Adds the corresponding changes needed for `Braintree.podspec` and `Package.swift`
- ~[] Added a changelog entry~
- @agedd

[iOS v5] Add Privacy Manifest to BraintreeSEPADirectDebit

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreePayPal/PrivacyInfo.xcprivacy

- Add privacyInfo.xcprivacy in BraintreePayPal module
- Changes to Package.swift and Podspec files
[Privacy Report Generated](https://github.com/braintree/braintree_ios/files/14793571/Demo-PrivacyReport.2024-03-28.10-41-14.pdf)

BraintreePayPal 5x Privacy Manifest

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeAmericanExpress/PrivacyInfo.xcprivacy

- Add PrivacyInfo.xcprivacy file into 5x BraintreeAmericanExpress module
- Modify Package.swift and podspec files
[Generated Privacy Report](https://github.com/braintree/braintree_ios/files/14806839/Demo-PrivacyReport.2024-03-29.10-03-10.pdf)

AmericanExpress 5x Privacy Manifest

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreePayPalNativeCheckout/PrivacyInfo.xcprivacy

- Add `PrivacyInfo.xcprivacy` to `BraintreePayPalNativeCheckout`
- Add corresponding changes to `Braintree.podspec` and `Package.swift` 
- @agedd

[iOS V5] Add Privacy Manifest to BraintreePayPalNativeCheckout

---

Sources/BraintreeCore/BTJSON.swift
UnitTests/BraintreeSEPADirectDebitTests/BTSEPADirectDebitClient_Tests.swift

- `BTSEPADirectDebitClient_Tests.testTokenizeWithPresentationContext_handleCreateMandateReturnsInvalidURL_returnsError_andSendsAnalytics()`
- We were returning a `cannedErrorResponse` here which wasn't needed and was actually returning before the method completed
- `BTJSON_Tests.testLargerMixedJSONWithEmoji()`
- `"aString": "Hello, JSON 😍!"` and `"anInvalidURL": ":™£¢://://://???!!!"` were failing to evaluate as `nil` when calling `BTJSON.asURL()` - neither of these are URLs so we expect that method to evaluate as `nil`
- Adding a check of `urlString.utf8.count == urlString.utf16.count` allows us to evaluate the string in the same way that we were in Obj-C
- More details on this test as a whole below...
I found this super interesting so adding it here if other folks are also interested:
- …

Fix Failing `UnitTest`s

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeCard/PrivacyInfo.xcprivacy

- Add `PrivacyInfo.xcprivacy` to `BraintreeCard` Module
- Add corresponding changes to `Braintree.podspec` and `Package.swift`
- @agedd

[iOS v5] Add Privacy Manifest For BraintreeCard Module

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/PayPalDataCollector/PrivacyInfo.xcprivacy

- Adds the `PrivacyInfo.xcprivacy` to PayPalDataCollector module
- Adds the corresponding changes to `Braintree.podspec` and `Package.swift`
- @agedd

[iOS v5] Add Privacy Manifest For PayPalDataCollector

---

Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreePayPal/BTPayPalApprovalURLParser.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Our demo app URL for universal linking of `https://braintree-ios-demo.fly.dev/braintree-payments` has been allowlisted so we can update `PayPalWebCheckoutViewController` with this
- In `BTPayPalApprovalURLParser` we were parsing `paypalAppApprovalUrl` from `paymentResource` (Checkout) when it should be parsed from `agreementSetup` (Vault) - verified via breakpoints and our contracts that this nesting should be updated
- Updated tests with this correction

[QL] Replace Universal Link in Demo App + Update `paypalAppApprovalUrl` Parsing

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeVenmo/PrivacyInfo.xcprivacy

- Adds the `PrivacyInfo.xcprivacy` to `BraintreeVenmo` module
- Adds the corresponding changes to `Braintree.podspec` and `Package.swift`
- @agedd

[iOS v5] Add Privacy Manifest For BraintreeVenmo

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Package.swift
Sources/BraintreeUnionPay/PrivacyInfo.xcprivacy

- Adds `PrivacyInfo.xcprivacy` to the `BraintreeUnionPay` module
- Adds the corresponding changes to `Braintree.podspec` and `Package.swift`
- @agedd

[iOS V5] Add Privacy Manifest Changes For BraintreeUnionPay

---

Demo/Application/Features/PayPalWebCheckoutViewController.swift

- Updated tokenization key to `sandbox_jy4fvpfg_v7x2rb226dx4pr7b` in the `universalLinkFlow` method, which will eventually connect to stage
- @stechiu

Change tokenization key

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/tests.yml
Braintree.podspec
CHANGELOG.md
Package.swift

- Update all workflow to use Xcode 15.0.1 - currently using Xcode 15.1 for the release for Carthage will result in merchants using that version to run into errors building with Xcode 15.0 since Xcode 15.1 is built with Swift 5.9.2 and our minimally supported version is Swift 5.9.0 ([resource](https://xcodereleases.com/))
- Bump `Package.swift` and `Braintree.podspec` to use Swift 5.9

Update Workflows to Use Xcode 15.0.1 + Swift Version 5.9

---

Sources/BraintreePayPal/BTPayPalAnalytics.swift
Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreePayPalTests/BTPayPalAnalytics_Tests.swift

- This will be used to calculate customer perceived latency from when the SDK is handed back control to when we return a nonce to the merchant
- There will be a ticket made to do this work in Android as well

[QL] Add `handleReturnStarted` Analytics Event

---

Demo/Application/Features/PayPalWebCheckoutViewController.swift

- Update button name from `universalLinkButton` to `payPalAppSwitchButton`
- Update button text to "PayPal App Switch Flow"
- Update method name from `universalLinkFlow` to `tappedPayPalAppSwitchFlow`
- Address TODO
- Handle nonce an errors for this flow - NOTE: this will not work yet but prepares us for stage and end to end stage testing early next week

[QL] Update `PayPalWebCheckoutViewController` for E2E App Switch Testing

---

Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- We were not passing the `ba_token` query parameter during the App Switch flow which is required

[QL] Add Missing BA Token to Query Parameters

---

Demo/Application/Base/PaymentButtonBaseViewController.swift
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreePayPal/BTPayPalClient.swift

- Add `UILabel` with ec-token to allow troubleshooting for E2E testing
- NOTE: this will be removed before merging this feature into `main` - this is being added to allow for easier debugging from E2E testing teams
https://github.com/braintree/braintree_ios/assets/20733831/b2d563b6-5257-424e-b87f-0071e54d63f0

[QL] Add `UILabel` with Token to Allow Troubleshooting for E2E Testing

---

Demo/Application/Features/PayPalWebCheckoutViewController.swift

- When adding the email field we removed the `baTokenLabel`, this PR adds it back as it's needed for E2E Testing

[QL] Add BA Token Back to ViewController

---

Demo/Application/Supporting Files/Braintree-Demo-Info.plist
Sources/BraintreePayPal/BTPayPalClient.swift

- Due to a bug found in E2E testing we need to update the URL scheme for the Venice app to `paypal-app-switch-checkout`
- Update our Demo app `Info.plist` with the new scheme
- Update the scheme in `BTPayPalClient` and update property name to `payPalAppSwitchScheme`

[QL] Update URL Scheme

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Cartfile
Demo/Demo.xcodeproj/project.pbxproj
Package.swift

- Pull in the latest MXO build `1.3.0` that includes the privacy manifest file and code-signatures changes.
- @agedd @KunJeongPark

Bump PayPalCheckout to Version 1.3.0

---

CHANGELOG.md
Demo/Application/Base/PaymentButtonBaseViewController.swift
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreePayPal/BTPayPalCheckoutRequest.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutRequest.swift
UnitTests/BraintreePayPalTests/BTPayPalCheckoutRequest_Tests.swift

- See Android PR https://github.com/braintree/braintree_android/pull/978/files
- Add `userAuthenticationEmail` property to `BTPayPalCheckoutRequest`
- Expose text field for email in Demo
- Cherry-picked demo app UI updates from this App Switch PR (https://github.com/braintree/braintree_ios/pull/1273)
@scannillo

Add `userAuthenticationEmail` to 1-Time Checkout

---

Braintree.xcodeproj/project.pbxproj

- Change the embedding method used in the `Shopper Insights` framework to resolve distribution issues with the Demo app. This will standardize the embedding approach of the `Braintree Core` framework with those used in the other frameworks within the Demo app
- @richherrera

`Do not embed` Core in `Shopper Insights` framework

---

Sources/BraintreeCore/Analytics/BTAnalyticsService.swift

- Fix small bug where analytics timestamp was always rounding milliseconds up
- See same manual testing done in [this PR](https://github.com/braintree/braintree_ios/pull/1234#discussion_r1538054171)
- Unit testing for this rounding IMO requires more trouble than it's worth (creating & injecting a mock of `Date`) 
@scannillo

Fix millisecond timestamp rounding bug in analytics

---

Demo/Demo.entitlements

- Define Demo app associated domain for universal link switches
- Resources
- See equivalent Android app link PR. This uses the same URL for both our Demo apps - https://github.com/braintree/braintree_android/pull/989
- See similar iOS PR for app switch workstream - https://github.com/braintree/braintree_ios/pull/1205
https://github.com/braintree/braintree_ios/assets/35243507/1b34ec93-0c8a-42b1-ba19-d80bcdba4106
@scannillo

Add universal link to Demo.entitlements

---

README.md

- Added info about upgrading Braintree SDK for latest SSL certs in README. This is because the Client Reference links to an external link for iOS. By updating the README, we can inform Merchant devs about the changes if they click on the reference links
https://braintree.github.io/braintree_ios/current/
- @stechiu

Update README - Added upgrade SDK message

---

Demo/Application/Base/AppDelegate.swift
Demo/Application/Base/ContainmentViewController.swift
Demo/Application/Base/Settings/BraintreeDemoSettings.swift
Demo/Application/Base/Settings/Settings.bundle/Root.plist
Demo/Application/Features/PayPalWebCheckoutViewController.swift

This ticket allows for QA team to test the Origami Checkout flow. We want to add the tokenization key “sandbox_rz48bqvw_jcyycfw6f9j4nj9c" to launch the PayPal checkout Origami experience. To launch this, PayPal intent type must be “Sale”
This tokenization key should only be used when specified in settings (not new default tokenization key).
- Branched off of `payment-insights-feature`
- Added to Origami Tokenization Key to Authorization Type in Settings
- Added toggle switch for Origami XO experience to Web Checkout
1. Settings: Integration > PayPal - Web Checkout, Authorization Type > Origami Tokenization Key
2. Buyer email (ex: jsdk@bt.com)
3. Toggle Origami Checkout to `on`
4. Tap "PayPal Checkout"
When Authorization Type is set to `Origami Tokenization Key`, there's a known error …

Added "Origami Checkout" to Web Checkout Flow

---

Braintree.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

- The [docs portion of the release recently failed](https://github.com/braintree/braintree_ios/actions/runs/8972689186/job/24641227565) with the error: `Your local changes to the following files would be overwritten by checkout: Braintree.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved`
- Opening `Braintree.xcodeproj` generates this update for us and should resolve the docs error next time we do a release

Bump MXO Version in `Package.resolved` To Resolve Docs Release Error

---

Sources/BraintreeCore/BTHTTP.swift

- The `BTHTTP.createRequest()` method is non-async and did not need to be closure-based
- Modernized with a `throws` function signature
@scannillo

Cleanup - `BTHTTP.createRequest()` remove unneeded closure syntax

---

Demo/Application/Features/PayPalWebCheckoutViewController.swift
Demo/Demo.entitlements

- Replace app switch Universal Link URL with Heroku site URL - verified that app Switch still works as expected with the new URL

[QL] Replace App Switch Universal Link URL

---

Sources/BraintreeCore/Analytics/BTAnalyticsService.swift

- In PR #1292 I forgot to add the docstrings to `sendAnalyticsEvents`. This PR adds them. 😄 

Add Missing Docstrings to `sendAnalyticsEvent`

---

Sources/BraintreeCore/BTHTTP.swift
UnitTests/BraintreeCoreTests/BTHTTP_Tests.swift

- Remove `NSCopying` conformance in `BTHTTP` & specific unit tests
- Remove `isEqual` override in `BTHTTP` & specifici unit tests
I did not see anywhere these 2 conformances were actually used by the SDK. 
@scannillo

Remove unused `NSCopying` & `isEqual` conformance in `BTHTTP`

---

Demo/Application/Base/BaseViewController.swift
Demo/Application/Base/ContainmentViewController.swift
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreePayPal/BTPayPalClient.swift

- Remove posting BA token via `NotificationCenter` - this was added for testing, as we prepare for release we need to remove this logic
- Remove `nonceCompletionBlock` logic - this was added for testing since stage does not work with our sample merchant server, now that we have moved to sand/prod testing we can remove this logic
- Note: this PR still leaves the stage toggle, but that will be cleaned up in a follow up PR once we have confirmed sand/prod testing works for the broader group, currently it is only working for a few people

[QL] Remove `NotificationCenter` and `nonceCompletionBlock` - Previously Added for Stage Testing

---

Sources/BraintreePayPalMessaging/BTPayPalMessagingView.swift
UnitTests/BraintreePayPalMessagingTests/BTPayPalMessagingView_Tests.swift

- This PR allows merchants to pass a new `BTPayPalMessagingRequest` and update the view. 
- `PayPalMessageView.init` is called on first load and `PayPalMessageView.setConfig` on subsequent loads using the same `PayPalMessageView`.
https://github.com/braintree/braintree_ios/assets/149086692/ee9e495c-f82f-4e14-a77e-0cc63c266c82
- @richherrera

Update existing PayPalMessagingView

---

Sources/BraintreeCore/BTHTTP.swift
UnitTests/BraintreeCoreTests/BTHTTP_Tests.swift

- Remove support for "data" type URI schemes. This was unused by any feature clients in the SDK.
- From looking in braintree_android, this URL type is not explicitly expected/supported there.
- (Someone can double check me on this!)

Remove unused support for "data" URI schemes

---

Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift
UnitTests/BraintreeVenmoTests/BTVenmoClient_Tests.swift

- Unit tests for this PR have been running since last week: https://github.com/braintree/braintree_ios/actions/runs/9215293641/job/25353361230, this is causing failures across multiple PRs where Unit Tests are running continuously
- I observed the same locally and tracked it down to an issue where new tests were not properly setting `webAuthenticationSession` this was causing the tests to never stop running both locally and on CI
- Renamed `lastPostedVaultType` to `postedIsVaultRequest` to properly represent the posted tag name for that event

Fix PayPal Unit Tests

---

CHANGELOG.md
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreeCoreTests/BTAPIClient_Tests.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Send `start_time`, `end_time`, and `endpoint` to FPTI for tracking API request latency for all modules
- Update `UnitTests`
- @richherrera

[QL] Measure API Request Latency for all modules

---

Demo/Demo.xcodeproj/project.pbxproj
SampleApps/CarthageTest/CarthageTest.xcodeproj/project.pbxproj
SampleApps/CarthageTest/CarthageTest/ViewController.swift
SampleApps/SPMTest/SPMTest.xcodeproj/project.pbxproj
SampleApps/SPMTest/SPMTest/ViewController.swift

- Add `PayPalMessaging` to `CathageTest` app
- Add `PayPalMessaging` to `SPMTest` app
- Add `PayPalMessages` package dependency in `Demo` app
- @richherrera

Add `PayPalMessaging` to Sample apps and Demo app

---

CHANGELOG.md
Sources/BraintreeCore/Analytics/BTAnalyticsService.swift

- We have seen an unexpectedly high number of `"core:api-request-latency"` analytics for the `/v1/configuration` endpoint in FPTI, compared to the number of occurrences for each attempted payment method flow (see data below)
- This analytic event was added in https://github.com/braintree/braintree_ios/pull/1292
- We haven't been able to replicate the exact issue we see in the FPTI dataset, but we do know that it is related to a quick succession of calls to `/v1/configuration`, while another is in-flight, resulting in duplicate/overlapping requests.
This PR reduces the number of calls to `BTAPIClient.fetchConfiguration()` in our Analytics layer. I don't know if this will solve 100% of the issue, but it should help.
- Move `BTAPIClient.fetchConfiguration()` call in  `BTAnalyticsService`
- …

Analytics - only fetch config before flushing events cache

---

Demo/Application/Base/PaymentButtonBaseViewController.swift
Demo/Application/Features/ShopperInsightsViewController.swift

- There was some button overlap on the `ShopperInsightsViewController`
|-----|-----|
|![Simulator Screenshot - iPhone SE (3rd generation) - 2024-06-17 at 14 29 32](https://github.com/braintree/braintree_ios/assets/20733831/1a646d2c-8851-4fba-9044-2ebd0b739588)|![Simulator Screenshot - iPhone SE (3rd generation) - 2024-06-17 at 15 46 33](https://github.com/braintree/braintree_ios/assets/20733831/302ca228-1dfa-4351-a6bd-47fba0ddc684)|
|![Simulator Screenshot - iPhone 15 Pro Max - 2024-06-17 at 11 19 31](https://github.com/braintree/braintree_ios/assets/20733831/887ae7ea-13da-42c7-8af1-83f95fa2a7de)|![Simulator Screenshot - iPhone 15 - 2024-06-17 at 15 47 59](https://github.com/braintree/braintree_ios/assets/20733831/c8261f7d-39fd-4ed1-8e3f-5215e838b932)
- ~[ ] Added a …

Fix Button Overlap on `ShopperInsightsViewController`

---

Demo/Demo.xcodeproj/project.pbxproj

Running our Demo app with XCode 16-beta2 shows the following warning:
- Remove duplicate Demo pbxproj entry for `BTSEPADirectDebitTestHelper.swift`
- ~ Added a changelog entry~
@scannillo

Fix Xcode 16-beta2 duplicate file warning

---

CHANGELOG.md
Demo/Application/Features/ThreeDSecureViewController.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureClient.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureRequest.swift
UnitTests/BraintreeThreeDSecureTests/BTThreeDSecureRequest_Tests.swift

Accept a raw JSON format for customFields in BTThreeDSecureRequest for VerifyCard.
@agedd 
@jwarmkessel 
@warmkesselj

Add customFields for 3DS verifyCard

---

CHANGELOG.md
Demo/Application/Features/PayPalNativeCheckoutViewController.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutAccountNonce.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutError.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutProvider.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutRequest.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutStartable.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeOrderCreationClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeTokenizationClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeTokenizationRequest.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeVaultRequest.swift

- Add deprecation message -
@available(*, deprecated, message: "BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead") for all public classes and enums for BraintreePayPalNativeCheckout module

Deprecation Lines for BTPayPalNativeCheckout Module

---

CHANGELOG.md
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
Sources/BraintreeShopperInsights/BTShopperInsightsError.swift
UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClient_Tests.swift

- Add new `BTShopperInsightsError.invalidAuthorization` and check authorization type in `BTShopperInsightsClient`
- This fixes a bug where you would see `SWIFT TASK CONTINUATION MISUSE: post(_:parameters:headers:httpType:) leaked its continuation!` when using shopper insights with a tokenization key

[Bug Fix] Add new `BTShopperInsightsError.invalidAuthorization`

---

Sources/BraintreeCore/BTAPIClient.swift
UnitTests/BraintreeApplePayTests/BTConfiguration+ApplePay_Tests.swift
UnitTests/BraintreeCoreTests/Analytics/BTAnalyticsService_Tests.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift

- Remove an unnecessary parameter.
- @richherrera

Clean up BTAPIClient.init

---

CHANGELOG.md
Sources/BraintreeCore/UIApplication+URLOpener.swift
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreeVenmo/BTVenmoClient.swift
UnitTests/BraintreeTestShared/FakeApplication.swift

- Update `URLOpener.openURL(_:options:completionHandler:)` protocol method to fix method signature change in Xcode 16 beta 3 (fixes #1359)
- This method signature changed and I expect it will change moving forward in future version of Xcode 16 based on the apple dev docs: https://developer.apple.com/documentation/uikit/uiapplication/1648685-open?changes=latest_minor

Update `URLOpener.openURL(_:options:completionHandler:)` for Xcode 16 beta 3

---

Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreePayPal/BTPayPalEditRequest.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift
UnitTests/BraintreePayPalTests/BTPayPalEditRequest_Tests.swift

- Create `PayPalEditRequest` that takes in a String `token`
- Add `tokenize` function that takes in` PayPalEditRequest` and returns` BTPayPalAccountNonce` or `Error`

Add BTPayPalEditRequest and Tokenize for Edit FI

---

CHANGELOG.md
Demo/Application/Features/ThreeDSecureViewController.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureClient.swift

- I noticed on recent CI runs that all of the UI tests for 3D Secure were failing, this is due to the additional of custom fields that are not set up in the gateway - updated to remove these from the ViewController since they were not set on the Android PR: https://github.com/braintree/braintree_android/pull/1044
- Additionally I noticed that with this removed 3DS was still not launching, this is because we were not checking that `customFields` was not nil before adding it to the request dictionary - this is implemented correctly in the Android PR

Update Custom Fields Implementation

---

.github/workflows/swiftlint.yml
.swiftlint.yml
Braintree.xcodeproj/project.pbxproj
DEVELOPMENT.md
README.md
Sources/BraintreeCore/Analytics/BTAnalyticsService.swift
Sources/BraintreeCore/Analytics/FPTIBatchData.swift
Sources/BraintreeCore/Authorization/BTClientToken.swift
Sources/BraintreeCore/Authorization/BTClientTokenError.swift
Sources/BraintreeCore/Authorization/TokenizationKey.swift
Sources/BraintreeCore/Authorization/TokenizationKeyError.swift
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeCore/BTAppContextSwitcher.swift
Sources/BraintreeCore/BTCoreConstants.swift
Sources/BraintreeCore/BTGraphQLErrorTree.swift
Sources/BraintreeCore/BTGraphQLHTTP.swift
Sources/BraintreeCore/BTGraphQLMultiErrorNode.swift
Sources/BraintreeCore/BTGraphQLSingleErrorNode.swift
Sources/BraintreeCore/BTHTTP.swift
Sources/BraintreeCore/BTJSON.swift
Sources/BraintreeCore/BTJSONError.swift
Sources/BraintreeCore/BTLogLevel.swift
Sources/BraintreeCore/BTPaymentMethodNonceParser.swift
Sources/BraintreeCore/BTPostalAddress.swift
Sources/BraintreeCore/BTURLUtils.swift
Sources/BraintreeCore/BTWebAuthenticationSession.swift
Sources/BraintreeCore/ConfigurationLoader.swift
Sources/BraintreeCore/UIApplication+URLOpener.swift

- Add `swiftlint.yml` to GitHub workflows
- Add `.swiftlint.yml` file with ruleset - this ruleset is the same as PPCP
- Add build script for `swiftlint`
- Address all swiftlint violations in `BraintreeCore` - will enable 1 module at a time to make PRs easier to reason about, additionally this allow us to progressively enable Swiftlint across the SDK while ensure code changes in modules where it's enable are compliant

[OPEN DEV] Add Swiftlint to `BraintreeCore`

---

Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeCore/ConfigurationLoader.swift
UnitTests/BraintreeCoreTests/ConfigurationLoader_Tests.swift
UnitTests/BraintreeCoreTests/MockConfigurationLoader.swift

- Remove `authorization` argument from `ConfigurationLoader.getConfig()` method since the `authorization` is already available on the `BTHTTP` instance (which is required via the `ConfigurationLoader.init`)
- This will help in a following PR to ensure the `GET` requests triggered from `ConfigurationLoader` are idempotent
@scannillo

Remove `Authorization` argument in `ConfigurationLoader.getConfig` method

---

CHANGELOG.md
Sources/BraintreeCore/BTHTTP.swift
UnitTests/BraintreeCoreTests/BTHTTP_Tests.swift

- Now that we are collecting data ([original PR](https://github.com/braintree/braintree_ios/pull/1292)) on how much time the SDK spends waiting for each network request to complete, we observed some incredibly long outlier datapoints. See the below image for examples:
- The goal of this PR is to reduce the max timeout for each API request. Currently, we're using Apple's defaults which are:
- The default [timeoutIntervalForRequest](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408259-timeoutintervalforrequest) is 60 seconds.
- The default [timeoutIntervalForResource](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408153-timeoutintervalforresource) is 7 days.
- This PR matches our [Android …

Set `URLSessionConfiguration` timeouts to 30 seconds

---

CHANGELOG.md
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeCore/BTHTTP.swift
UnitTests/BraintreeCoreTests/BTHTTP_Tests.swift

- 3D Secure: remove token/unique ID from path
- GraphQL: remove reliance on `operationName` since this is only present for card, causing us not to send the correct path for the Venmo flow
- Both endpoints sending as expected have been verified in FPTI and via breakpoints, additionally all endpoint have been checked to ensure we are sending the expected paths now

Update 3DS and GraphQL Endpoint Sent to FPTI

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreePayPal/BTPayPalError.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Fix bug where we were hardcoding the `paymentType` to `vault` when returning from `webAuthenticationSession.start` -this caused us to not pass the correct parameters to the Gateway as this block was never executed for the Checkout flow: https://github.com/braintree/braintree_ios/blob/7b81129478fb3302b2ffacdbb4ade80e561faef7/Sources/BraintreePayPal/BTPayPalClient.swift#L225-L230

PayPal Payment Type Bug Fix

---

Sources/BraintreeCore/Analytics/BTAnalyticsService.swift
Sources/BraintreeCore/Analytics/RepeatingTimer.swift

- Move `timeInterval` default value into `RepeatingTimer` init - `BTAnalyticsService` should not need to know about our timer's default

Move `timeInterval` Default Value

---

Sources/BraintreeLocalPayment/BTLocalPaymentRequest.swift

- While poking around some things I noticed we had the wrong docstring for `merchantAccountID` in `BTLocalPaymentRequest`

Update Incorrect Docstrings

---

Sources/BraintreePayPal/BTPayPalVaultEditRequest.swift

- Add optional merchantAccountID and docstrings to PayPalVaultEditRequest

Add Optional merchantAccountID to PayPalVaultEditRequest

---

Braintree.xcodeproj/project.pbxproj
Sources/BraintreeCore/Analytics/LinkType.swift
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreePayPal/BTPayPalApprovalURLParser.swift
Sources/BraintreePayPal/BTPayPalCheckoutRequest.swift
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreePayPal/BTPayPalRequest.swift
Sources/BraintreePayPal/BTPayPalReturnURL.swift
Sources/BraintreePayPal/BTPayPalVaultBaseRequest.swift
Sources/BraintreePayPal/BTPayPalVaultRequest.swift
Sources/BraintreeVenmo/BTVenmoClient.swift
UnitTests/BraintreeCoreTests/Analytics/FPTIBatchData_Tests.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift
UnitTests/BraintreePayPalTests/BTPayPalVaultRequest_Tests.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift
UnitTests/BraintreeVenmoTests/BTVenmoClient_Tests.swift

- Move `LinkType` to enum
- Remove logic to pass `linkType` into Approval URL parser
- Move app installed check into Vault Request

Cleanup App Switch

---

Sources/BraintreeCore/Analytics/FPTIBatchData.swift
Sources/BraintreeCore/BTHTTP.swift
UnitTests/BraintreeCoreTests/Analytics/FPTIBatchData_Tests.swift

- Move venmo_installed and paypal_installed FPTI metadata params to `batch_prams` from `event_params`
on device (less events here since I didn't go through actual Apple Pay on device, but both sets matched up number of events = these fields):
on simulator 
- @KunJeongPark @jwarmkessel

Move payPalInstalled and venmoInstalled to batch_params

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalClient.swift

- Send `isVaultRequest` for app switch events to FPTI
- Verified that all events are now sending this bool to FPTI

Send `isVaultRequest` for App Switch Events

---

Sources/BraintreeCore/Configuration/ConfigurationLoader.swift

- Cleanup comments left post merge from Sammy in PR: https://github.com/braintree/braintree_ios/pull/1385

Configuration Cleanup

---

.swiftlint.yml
Sources/BraintreeDataCollector/BTDataCollector.swift
Sources/BraintreeDataCollector/BTDataCollectorEnvironment.swift

- Add `BraintreeDataCollector` module to `.swiftlint.yml`
- Address all swiftlint violations in `BraintreeDataCollector` - will enable 1 module at a time to make PRs easier to reason about, additionally this allow us to progressively enable Swiftlint across the SDK while ensure code changes in modules where it's enable are compliant

Add SwiftLint to `BraintreeDataCollector`

---

Sources/BraintreePayPal/BTPayPalVaultEditResult.swift

- Update `BTPayPalVaultEditResult` to only return `riskCorrelationID`
- @KunJeongPark @jwarmkessel

Update `BTPayPalVaultEditResult` to Return Only `riskCorrelationID`

---

Demo/Application/Features/ShopperInsightsViewController.swift

- Doing some other troubleshooting and noticed we were using `self` all over `ShopperInsightsViewController` when we didn't need to be. Cleaned it up to make the code a bit clearer.

Cleanup Use of Self in `ShopperInsightsViewController`

---

.swiftlint.yml
Sources/BraintreePayPalMessaging/BTPayPalMessagingLogoType.swift
Sources/BraintreePayPalMessaging/BTPayPalMessagingOfferType.swift
Sources/BraintreePayPalMessaging/BTPayPalMessagingPageType.swift
Sources/BraintreePayPalMessaging/BTPayPalMessagingRequest.swift
Sources/BraintreePayPalMessaging/BTPayPalMessagingView.swift

- Add `BraintreePayPalMessaging` module to `.swiftlint.yml`
- Address all swiftlint violations in `BraintreePayPalMessaging` - will enable 1 module at a time to make PRs easier to reason about, additionally this allow us to progressively enable Swiftlint across the SDK while ensure code changes in modules where it's enable are compliant

Add SwiftLint to `BraintreePayPalMessaging`

---

.swiftlint.yml
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutAccountNonce.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutProtocol.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutProvider.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeCheckoutStartable.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeHermesResponse.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeOrderCreationClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeTokenizationClient.swift
Sources/BraintreePayPalNativeCheckout/BTPayPalNativeTokenizationRequest.swift

- Add `BraintreePayPalNativeCheckout` module to `.swiftlint.yml`
- Address all swiftlint violations in `BraintreePayPalNativeCheckout` - will enable 1 module at a time to make PRs easier to reason about, additionally this allow us to progressively enable Swiftlint across the SDK while ensure code changes in modules where it's enable are compliant

Add SwiftLint to `BraintreePayPalNativeCheckout`

---

.swiftlint.yml
Sources/BraintreeSEPADirectDebit/BTSEPADirectDebitClient.swift
Sources/BraintreeSEPADirectDebit/CreateMandateResult.swift
Sources/BraintreeSEPADirectDebit/SEPADebitAccountsRequest.swift
Sources/BraintreeSEPADirectDebit/SEPADebitRequest.swift
Sources/BraintreeSEPADirectDebit/SEPADirectDebitAPI.swift

- Add `BraintreeSEPADirectDebit` module to `.swiftlint.yml`
- Address all swiftlint violations in `BraintreeSEPADirectDebit` - will enable 1 module at a time to make PRs easier to reason about, additionally this allow us to progressively enable Swiftlint across the SDK while ensure code changes in modules where it's enable are compliant

Add SwiftLint to `BraintreeSEPADirectDebit`

---

.swiftlint.yml
Sources/BraintreeThreeDSecure/BTThreeDSecureAdditionalInformation.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureAuthenticateJWT.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureClient.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureLookup.swift
Sources/BraintreeThreeDSecure/BTThreeDSecurePostalAddress.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureRequest.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureV2Provider.swift
Sources/BraintreeThreeDSecure/V2UICustomization/BTThreeDSecureV2UICustomization.swift

- Add `BraintreeThreeDSecure` module to `.swiftlint.yml`
- Address all swiftlint violations in `BraintreeThreeDSecure` - will enable 1 module at a time to make PRs easier to reason about, additionally this allow us to progressively enable Swiftlint across the SDK while ensure code changes in modules where it's enable are compliant

Add SwiftLint to `BraintreeThreeDSecure`

---

Demo/Application/Base/ContainmentViewController.swift
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreePayPal/RecurringBillingMetadata/BTPayPalBillingCycle.swift
UnitTests/BraintreePayPalTests/BTPayPalVaultRequest_Tests.swift

- End to end testing revealed that there are cases where `billing_frequency` and `billing_frequency_unit` are not required for `unscheduled` cases for RBA metadata - updated and tested that these fields can be omitted without error when the `recurringBillingPlanType` is `.unscheduled` and the `pricingModel` is `.autoReload` per the test case
- Updated docstrings

[QL] Update `interval` and `intervalCount`

---

Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreePayPal/BTPayPalError.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Add new `BTPayPalError.invalidAuthorization` and check authorization type in `edit` method
- Add warnings that authorization can only be client token with this feature
- Add unit test for new error

[QL] Add New `BTPayPalError.invalidAuthorization`

---

CHANGELOG.md
Demo/Application/Features/ShopperInsightsViewController.swift
Sources/BraintreeCore/Analytics/FPTIBatchData.swift
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClient_Tests.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift

- Add additional analytic parameters to the `ShopperInsights` Button Presentment Analytics 
- Tested out various use cases and ensured appropriate logs were rendered in FPTI:
- `paymentMethodsDisplayed = ["Apple Pay", "Card", "PayPal"] `and `experiment` set to sampleJSON 
- `sessionID: FE9334072FBD47C7B81EFED6C314C9DF `
- @agedd

Add Additional Parameters To ShopperInsights Button Analytics

---

CHANGELOG.md
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Remove completion Edit FI methods
- Update unit tests to use async/await Edit FI methods

Remove Completion Edit FI Methods

---

Demo/Application/Base/BaseViewController.swift
Demo/Application/Features/PayPalMessagingViewController.swift

- Remove the gesture implemented in the `BaseViewController` to avoid interference with the gesture in the `PayPalMessagingViewController`. This ensures that the `PayPalMessagingViewController` receives the gesture and launches the `PayPalMessageView`.
https://github.com/user-attachments/assets/229141d0-8f8e-44d2-92e0-a6f3031ad51b
- @richherrera

Remove the dismiss keyboard gesture from PayPalMessagingViewController

---

CHANGELOG.md
Sources/BraintreeCore/Analytics/BTAnalyticsEventsStorage.swift
Sources/BraintreeCore/Analytics/BTAnalyticsService.swift
Sources/BraintreeCore/BTHTTP.swift
Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
UnitTests/BraintreeCoreTests/Analytics/BTAnalyticsService_Tests.swift

- There was a bug found with an LE merchant's ShopperInsights integration where the PaymentReady API team logs were tracking _more_ unique sessionIDs used to call their API from our SDK, than our SDK logs were tracking alone
- The SDK sends our `session_id` to the PaymentReady API via[ this header](https://github.com/braintree/braintree_ios/blob/971196de71e88b1ccf2c35bf79ca7fc4c4c60b77/Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift#L58)
- Our analytics batch upload logic was including events across varying sessionIDs in a single batch payload. Since the `session_id` is at the `batch_params` level, the unique sessionIDs per API call were squashed/lost only logging the latest sessionID to be created/used.
- This PR follows BT Android's model of doing a unique POST to …

Fixup - only batch analytics events with same sessionID

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/swiftlint.yml
.github/workflows/tests.yml

- Move all GitHub actions workflows to v4 - the main improvement in v4 should be performance speed as noted in the [GitHub blog here](https://github.blog/news-insights/product-news/get-started-with-v4-of-github-actions-artifacts/#whats-improved-in-v4)
- We were getting the following warning with continuing to use an old version, which v4 should also resolve:
- It doesn't look like there should be any breaking changes in the release portion, but a bit hard to say since we were on v2 (while the rest of our workflows were on v3) - we will just need to be slightly aware of this next release

[OPEN DEV] Move Workflows to GitHub Actions v4

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalRequest.swift
UnitTests/BraintreePayPalTests/BTPayPalRequest_Tests.swift

- Add a new property to the `BTPayPalRequest` and pass it to support server-side shipping callbacks
- @richherrera

Add Shipping Callback URL to BTPayPalRequest

---

Demo/Application/Features/PayPalWebCheckoutViewController.swift

- Create new `UIStackView`s to organize the layout of the components (UILabel & UITextFields), allowing them to be easily selectable
- Change the keyboard type of the `emailTextField` to `.emailAddress`
- Increase the height of the view to create more space between the UI components
|  🐛  | ⭐️ |
| -------- | ------- |
| ![Screenshot 2024-10-18 at 11 08 48 a m](https://github.com/user-attachments/assets/e66a9e97-f904-4b39-aa48-fefee05da560)  | ![Screenshot 2024-10-18 at 11 40 11 a m](https://github.com/user-attachments/assets/9ad3295f-11b4-4899-961e-62cc715c4a91) |
UI Warnings fixed
- @richherrera

[Open Dev] Fix PayPal Demo UI

---

Demo/Application/Features/Helpers/Toggle.swift
Demo/Application/Features/Helpers/ToggleWithLabel.swift
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Demo/Application/Features/VenmoViewController.swift
Demo/Demo.xcodeproj/project.pbxproj
Demo/UI Tests/Venmo UI Tests/Venmo_UITests.swift

- Create re-usable Toggle + Label UIView file
- Remove 3 different Venmo buttons in favor of toggles for opt-in settings
- This change is to prepare for another upcoming toggle to enable universal link returns from the Venmo app --> SDK (DTMOBILES-927)
- Remove ECD options button & UI test (Android doesn't have them and I've never seen us use it)
| Before    | After |
| -------- | ------- |
|  ![Screenshot 2024-10-17 at 3 55 26 PM](https://github.com/user-attachments/assets/687d2f19-e779-41c4-ac2d-4f55fc4ac16b) |  ![Screenshot 2024-10-17 at 4 56 44 PM](https://github.com/user-attachments/assets/4e1d8b67-3e91-4f1f-a1df-59483cbb82eb) |
I am indeed a designer :D 
@scannillo

Cleanup Venmo Demo UI

---

CHANGELOG.md
Sources/BraintreeCore/Analytics/FPTIBatchData.swift
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeVenmo/BTVenmoAnalytics.swift
Sources/BraintreeVenmo/BTVenmoClient.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift
UnitTests/BraintreeVenmoTests/BTVenmoClient_Tests.swift

- Add the same events for the Venmo flow that were added for the PayPal app switch flow:
`venmo:tokenize:app-switch:started` and `venmo:tokenize:handle-return:started`
- Add `appSwitchUrl` in the `appSwitchSucceeded` and `appSwitchFailed` events.
<p>
</p>
- @richherrera

Add App Switch Analytics events

---

Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreePayPal/BTPayPalVaultEditRequest.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Rename `risk_correlation_id` to `correlation_id` to match what should be passed to the gateway for Edit FI/Error Handling.
- Update unit tests

Update CMID Property Passed to the Gateway

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalCheckoutRequest.swift
UnitTests/BraintreePayPalTests/BTPayPalCheckoutRequest_Tests.swift

- Add a new property to the `BTPayPalCheckoutRequest` and pass it to support server-side shipping callbacks. Shipping callbacks should only be available for PayPal checkout flows.
- @richherrera

Add Shipping Callback URL to `BTPayPalCheckoutRequest` 

---

CHANGELOG.md
Demo/Application/Features/IdealViewController.swift
Sources/BraintreeLocalPayment/BTLocalPaymentClient.swift
Sources/BraintreeLocalPayment/BTLocalPaymentRequest.swift
UnitTests/BraintreeLocalPaymentTests/BTLocalPaymentClient_UnitTests.swift
V7_MIGRATION.md

- Update BTCard properties to have everything in the init vs using dot syntax
Docstrings:
- @richherrera

[V7] Update `BTLocalPaymentRequest`

---

Demo/Application/Base/Settings/BraintreeDemoSettings.swift
Demo/UI Tests/ThreeDSecure UI Tests/ThreeDSecure_V2_UITests.swift

Updating the url endpoints for the new Heroku apps ruby server.

Update heroku server endpoints

---

CHANGELOG.md
Sources/BraintreeCore/BTCoreConstants.swift
UnitTests/BraintreeCoreTests/BTGraphQLHTTP_Tests.swift

- Bump the GraphQL API Version based on the current date
- Verified the card and venmo flows work as expected (these are the only flows using GQL currently)
- Android v5 PR with this change: https://github.com/braintree/braintree_android/pull/1128

Bump GraphQL API Version

---

Demo/UI Tests/PayPal Messaging UI Tests/PayPalMessaging_UITests.swift

The test `testStart_withValidRequest_firesDelegates` has been failing recently. Upon investigation the text for `PayPal - Pay monthly for purchases of $199-$10,000. Learn more` has changed to `PayPal - Pay monthly for purchases of $49-$10,000. Learn more`. This is likely due to a backend change to vary the offers in some cases. Instead of just hardcoding the new value since we now know this can change, I opted to use `NSPredicate` for the portion of the text that we likely do not expect to change. This should hopefully keep our test more flexible with changes the messaging team may make to the text on the back end.

Update PayPal Messaging UI Test

---

Demo/UI Tests/ThreeDSecure UI Tests/ThreeDSecure_UITests_Extensions.swift
Demo/UI Tests/ThreeDSecure UI Tests/ThreeDSecure_V2_UITests.swift

* Remove all 3DS UI tests except the following cases:
1)  Successfully completes challenge flow & returns to app
2) Cancels 3DS challenge flow & returns to app
* Why? 
* The SDK's test suite is not responsible for serving as E2E integration tests for numerous [test card cases](https://developer.paypal.com/braintree/docs/guides/3d-secure/testing/ruby#testing). Our UI tests should capture the functionality that our SDK adds to a checkout experience.
* UI tests are timely and expensive. Read about Mike Cohn's "Testing Pyramid" concept, where UI tests should make up the top, smallest part of the pyramid.
Total time reduced: **2 min 20 sec** (140 seconds)
```
✔ testThreeDSecurePaymentFlowV2_frictionlessFlow_andTransacts (17.442 seconds)
✔ testThreeDSecurePaymentFlowV2_noChallenge_andFails …
```

Streamline 3DS UI Tests

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalCheckoutRequest.swift
Sources/BraintreePayPal/BTPayPalRequest.swift
Sources/BraintreePayPal/BTPayPalVaultBaseRequest.swift
Sources/BraintreePayPal/BTPayPalVaultRequest.swift

- Update `BTPayPalRequest` with app-switch properties, `enablePayPalAppSwitch` and `userAuthenticationEmail`
- Remove these properties from `BTPayPalVaultRequest`
- Add init to `BTPayPalCheckoutRequest` with these properties
- Tested and verified app switch flow for vaulting works as expected (the checkout flow is not yet expected to work)
- @agedd

Update `BTPayPalRequest` with App Switch Properties

---

Demo/Application/Features/PayPalWebCheckoutViewController.swift

- Add 'PayPal App Switch - Checkout' Button To 1-Time Checkout Flow
| -------- | ------- |
|![Simulator Screenshot - iPhone 15 Pro - 2024-11-22 at 14 48 10](https://github.com/user-attachments/assets/ed6a81dd-f98e-4696-b8bc-bb7226c58125)| ![Simulator Screenshot - iPhone 15 Pro - 2024-11-22 at 14 40 43](https://github.com/user-attachments/assets/0bcd45e3-bc68-46a8-be22-b7abf19dfcc9) |
- @agedd

Update Demo App to Support App Switch for Checkout

---

Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreePayPal/BTContactInformation.swift
Sources/BraintreePayPal/BTPayPalCheckoutRequest.swift
UnitTests/BraintreePayPalTests/BTPayPalCheckoutRequest_Tests.swift

Introduces support for passing recipient contact information in the `BTPayPalCheckoutRequest`
- A new class `BTContactInformation` was created to encapsulate the recipient's contact information for the order.
Properties: `recipientEmail` and`recipientPhoneNumber`
- Updated BTPayPalCheckoutRequest: Added a new optional property `contactInformation` of type `BTContactInformation`.
- The `contactInformation.recipientEmail` and `contactInformation.recipientPhoneNumber` are passed to the `create_payment_resource` endpoint as the `recipient_email`  and `international_phone` parameters when present.
**Note:** When the new parameters (recipient_email and international_phone) are included, the gateway returns an error. I will follow up with updates once I gather more information or implement any …

Add Contact Information request object

---

Braintree.xcodeproj/project.pbxproj
Sources/BraintreeLocalPayment/BTLocalPaymentClient.swift
Sources/BraintreeLocalPayment/BTLocalPaymentRequest.swift
Sources/BraintreeLocalPayment/Models/LocalPaymentPOSTBody.swift

- Add encodable types for `post` bodies used in the Local Payment flow.
- Local Payment flow has been tested in the Demo app to ensure the dictionaries are still constructed as expected.
- @richherrera

[V7] Add `Encodable` protocol for Local Payments.

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Add `url` to `appSwitchSucceeded` and `appSwitchFailed` events
- Add unit tests

Add URL to PayPal App Switch Events

---

CHANGELOG.md
Demo/Application/Supporting Files/Braintree-Demo-Info.plist
Sources/BraintreeCore/BTCoreConstants.swift
V7_MIGRATION.md

- Update the PayPal App URL query scheme from `paypal-app-switch-checkout` to `paypal` 
- See DTMOBILES-1286 for more detail.
@scannillo

V7 app switch url

---

CHANGELOG.md
Sources/BraintreeThreeDSecure/BTThreeDSecureRequest.swift
Sources/BraintreeThreeDSecure/BTThreeDSecureV2Provider.swift

- Add `BTThreeDSecureRequest.requestorAppURL` - this is a new property required by Mastercard for 3DS for out of band transactions. There was an internal request from a large merchant for exposing this field.
- There is currently not a good way to test values set on `cardinalConfiguration` so those are not included. I did test setting this value locally to ensure this value is being set on `cardinalConfiguration` when passed.

Add `BTThreeDSecureRequest.requestorAppURL`

---

Sources/BraintreeCore/Analytics/FPTIBatchData.swift
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreeShopperInsights/BTShopperInsightsClient.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift
UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClient_Tests.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift

- This PR addresses some previous confusion around requirements for how to log the `shopperSessionID`
- Send a new FPTI param with the tag `shopper_session_id`
- Send this anywhere a shopperSessionID is accessible (in the PayPalClient & ShopperInsightsClient)
- Revert change to of overriding the SDK sessionID with the shopperSessionID
- Keeps `/v2/payments/find-eligible-methods` API call as it was prior
- Note: This API call will be swapped in the future to one that actually requires a shopperSessionID. Will get tackled in RP3. This is when we can require the shopperSessionID at the init level.
This feature has been a bit confusing, so please let me know if there are questions!
- ~Tested and confirmed payment flows affected by this change are functioning as …

ShopperInsights - send `shopper_session_id` to FPTI

---

CHANGELOG.md
Demo/Application/Base/AppDelegate.swift
Demo/Application/Base/PaymentButtonBaseViewController.swift
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Demo/Application/Features/ShopperInsightsViewController.swift
Demo/Application/Features/VenmoViewController.swift
SampleApps/CarthageTest/CarthageTest/ViewController.swift
SampleApps/SPMTest/SPMTest/ViewController.swift
Sources/BraintreeCore/BTAppContextSwitcher.swift
Sources/BraintreeVenmo/BTVenmoAppSwitchRedirectURL.swift
Sources/BraintreeVenmo/BTVenmoAppSwitchReturnURL.swift
Sources/BraintreeVenmo/BTVenmoClient.swift
Sources/BraintreeVenmo/BTVenmoError.swift
UnitTests/BraintreeCoreTests/BTAppContextSwitcher_Tests.swift
UnitTests/BraintreeLocalPaymentTests/BTLocalPaymentClient_UnitTests.swift
UnitTests/BraintreeVenmoTests/BTVenmoAppSwitchRedirectURL_Tests.swift
UnitTests/BraintreeVenmoTests/BTVenmoClient_Tests.swift
V7_MIGRATION.md

- Remove `BTAppContextSwitcher.sharedInstance.returnURLScheme`
- Remove `BTVenmoClient(apiClient:)` init in favor of `universalLink` init
- Cleanup demo app
- Remove logic around `returnURLScheme` in the Venmo flow since this is no longer needed
- Remove no longer needed error case
- Cleanup unit tests based on updated logic

[v7] Update Venmo to Support Only Universal Links 

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalClient.swift

Fixing a bad merge from main branch
@jwarmkessel 
@warmkesselj 
-

Shopper insights rp1 feature fixes from main merge

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalVaultRequest.swift

- Add a conditional check to ensure that the userAuthenticationEmail is not empty before setting it as the payer_email in baseParameters. 
- @richherrera

Add Payer Email to Base Parameters if not empty

---

CHANGELOG.md
Sources/BraintreeThreeDSecure/BTThreeDSecureClient.swift
UnitTests/BraintreeThreeDSecureTests/BTThreeDSecureClient_Tests.swift
UnitTests/BraintreeThreeDSecureTests/MockCardinalSession.swift

- Return error if no `dfReferenceId` is returned in the 3D Secure flow
- Confirmed with Cardinal that we should not continue the flow if we do not get a `dfReferenceId` back, there is also no fallback mechanism on mobile like exists on web

Bug Fix: Handle Missing 3DS `dfReferenceId`

---

Demo/Demo.xcodeproj/xcshareddata/xcschemes/Demo.xcscheme

- Move `BraintreeShopperInsightsTests` into the Demo apps testable reference with all of our other tests
|-----|-----|
|![Screenshot 2025-01-10 at 8 49 07 AM](https://github.com/user-attachments/assets/6cee7890-aeee-413b-b3d2-160b4c031a41)|<img width="281" alt="Screenshot 2025-01-10 at 1 01 41 PM" src="https://github.com/user-attachments/assets/f75312c7-a060-4cb1-85c7-7ffc1690e5ad" />|

[OPEN DEV] Move BraintreeShopperInsightsTests to Demo

---

Braintree.xcodeproj/project.pbxproj
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreePayPal/BTConfiguration+PayPal.swift
Sources/BraintreePayPal/BTPayPalCheckoutRequest.swift
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreePayPal/BTPayPalLineItem.swift
Sources/BraintreePayPal/BTPayPalPaymentType.swift
Sources/BraintreePayPal/BTPayPalRequest.swift
Sources/BraintreePayPal/BTPayPalRequestLandingPageType.swift
Sources/BraintreePayPal/BTPayPalVaultRequest.swift
Sources/BraintreePayPal/Models/BTPayPalCheckoutPOSTBody.swift
Sources/BraintreePayPal/Models/PayPalCheckoutPOSTBody.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Add `PayPalRequest` protocol to define the contract for the base properties for `BTPayPalCheckoutRequest` and `BTPayPalVaultRequest`
- Conform to the new protocol in the three concrete classes (BTPayPalRequest, BTPayPalCheckoutRequest and BTPayPalVaultRequest) to eliminate inheritance
- Update docstrings for classes BTPayPalCheckoutRequest and BTPayPalVaultRequest
- LineItems now conforms to the Encodable protocol.
- Add encodable types for `post` bodies used in the PayPal Checkout flow.
- PayPal Checkout has been tested in the Demo app to ensure the dictionaries are still constructed as expected.
**Note**: Since we have two different classes (`PayPalCheckoutRequest` and `PayPalVaultRequest`) used in `PayPalClient`, it's currently not possible to use `Encodable` until the same …

[V7] Add `Encodable` protocol for PayPal Checkout

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/tests.yml
Braintree.podspec
Braintree.xcodeproj/xcshareddata/xcschemes/UnitTests.xcscheme
CHANGELOG.md
Package.swift
README.md
V7_MIGRATION.md

- Update all workflow to use Xcode 16.2.0 ([resource](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#xcode))
- Bump `Package.swift` and `Braintree.podspec` to use Swift 5.10
- Update CHANGELOG, Migration guide and Readme
- @richherrera

[V7] Update workflows to use Xcode 16.2.0 + Swift Version 5.10

---

Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreePayPal/BTContactInformation.swift
Sources/BraintreePayPal/BTPayPalCheckoutRequest.swift
UnitTests/BraintreePayPalTests/BTPayPalCheckoutRequest_Tests.swift

- These changes were reviewed and approved previously, this is just to trigger CI and ensure all passes before merging into main
- @richherrera @agedd @jaxdesmarais

[DO NOT REVIEW] Merge Contact Information Feature Branch

---

Braintree.xcodeproj/xcshareddata/xcschemes/UnitTests.xcscheme
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreePayPal/BTPayPalError.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Update logic to launch the PP app for the 1-time checkout flow.
**Note**: verified app-switch flow works as expected for both flows w/ intercepting the url before app-switch - would need to wait until #1500 is merged in and gateway/other components changes have been deployed.
- @agedd

Launch PayPal App For Checkout Flow

---

CHANGELOG.md
Demo/Application/Features/VenmoViewController.swift
Sources/BraintreeVenmo/BTVenmoClient.swift
UnitTests/BraintreeVenmoTests/BTVenmoClient_Tests.swift

- A bug was recently brought to the service channel where if a merchant trys to move from the deprecated `BTAppContextSwitcher.sharedInstance.returnURLScheme` for Venmo they get an error if only passing a universal link. We should allow merchants to only use universal links without needing to set both that and a `returnURLScheme`
I tested the following flows on device, please feel free to retest these or call out any use cases I missed:
- `universalLink` and `returnURLScheme` not set (returns an error)
- only `returnURLScheme` set (uses `returnURLScheme` for switch and return)
- only `universalLink` set (uses `universalLink`  for switch and return)

Allow Merchant to Only Set Universal Links for Venmo

---

CHANGELOG.md
Sources/BraintreeCore/Authorization/BTClientToken.swift

- Update to use `NSSecureCoding` protocol (fixes #1508)

Update to use `NSSecureCoding` protocol 

---

Sources/BraintreePayPal/BTPayPalApprovalURLParser.swift
Sources/BraintreePayPal/BTPayPalClient.swift

- Re-added the `token` parameter  and added logic to pass that into the `launchPayPalApp()` function
- Fixed parsing logic to read the `launchPayPalApp` boolean value from GW to determine the redirectType
- @agedd

ECS5 App Switch Feature Bug Fixes

---

CHANGELOG.md
Sources/BraintreeApplePay/BTApplePayCardNonce.swift

Expose isDeviceToken on BTApplePayCardNonce [Duplicate]

---

CHANGELOG.md
Demo/Application/Features/ApplePayViewController.swift
Sources/BraintreeApplePay/BTApplePayCardNonce.swift
UnitTests/BraintreeApplePayTests/BTApplePayCardNonce_Tests.swift

This is a feature branch going into `main`
- Merged in https://github.com/braintree/braintree_ios/pull/1516
- Merged in https://github.com/braintree/braintree_ios/pull/1517
- @stechiu

Merge `mpan` feature branch into `main`

---

.github/workflows/tests.yml
UnitTests/BraintreeSEPADirectDebitTests/BTSEPADirectDebitClient_Tests.swift

- Set the destination to a runnable destination from the logs - specifically it looks like `OS=17.2` needs to be run on an `iPhone 15`

[v5] Fix CI Tests

---

CHANGELOG.md
Demo/Application/Features/Apple Pay - PassKit/BraintreeDemoApplePayPassKitViewController.m
Sources/BraintreeApplePay/BTApplePayCardNonce.m
Sources/BraintreeApplePay/Public/BraintreeApplePay/BTApplePayCardNonce.h
UnitTests/BraintreeApplePayTests/BTApplePayCardNonce_Tests.swift

- Exposed `isDeviceToken`
- Updated demo app to demonstrate `isDeviceToken` usage and to confirm whether a transaction uses MPAN or DPAN
- @stechiu

[v5] Merge Apple MPAN into `5.x` branch

---

Braintree.xcodeproj/project.pbxproj
CHANGELOG.md
Demo/Application/Base/PaymentButtonBaseViewController.swift
Demo/Application/Features/AmexViewController.swift
IntegrationTests/BraintreeAmexExpress_IntegrationTests.swift
SampleApps/CarthageTest/CarthageTest/ViewController.swift
SampleApps/SPMTest/SPMTest/ViewController.swift
Sources/BraintreeAmericanExpress/BTAmericanExpressClient.swift
Sources/BraintreeCore/Authorization/ClientAuthorization.swift
Sources/BraintreeCore/Authorization/InvalidAuthorization.swift
Sources/BraintreeCore/Authorization/TokenizationKey.swift
Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeCore/BTAPIClientError.swift
Sources/BraintreeCore/BTHTTPError.swift
UnitTests/BraintreeAmericanExpressTests/BTAmericanExpressClient_Tests.swift
UnitTests/BraintreeCoreTests/Configuration/ConfigurationLoader_Tests.swift
V7_MIGRATION.md

- Update initializer to `BTAmericanExpressClient(authorization:)`
- Add `InvalidAuthorization` type - this matches the [pattern used on Android](https://github.com/braintree/braintree_android/blob/main/BraintreeCore/src/main/java/com/braintreepayments/api/core/InvalidAuthorization.kt)
- Update `BTAPIClient` initializer to require an authorization string
- Add new `BTAPIClientError.invalidAuthorization`
- Update `PaymentButtonBaseViewController` with new authorization string
- Update `AmexViewController` demo app with new initializer
- Update unit and integration tests
- Add `TODO`s for final PR cleanup

[v7] Make APIClient Non-optional & Update `BTAmericanExpressClient` Init

---

CHANGELOG.md
Demo/Application/Features/ApplePayViewController.swift
IntegrationTests/Braintree-API-Integration-Specs/BraintreeApplePay_IntegrationTests.swift
SampleApps/CarthageTest/CarthageTest/ViewController.swift
SampleApps/SPMTest/SPMTest/ViewController.swift
Sources/BraintreeApplePay/BTApplePayClient.swift
UnitTests/BraintreeApplePayTests/BTApplePay_Tests.swift
V7_MIGRATION.md

Update BTApplePayClient init to BTApplePayClient(authorization: String) ✅ 
Update unit tests ✅ 
Update demo app ✅ 
Add CHANGELOG entry ✅ 
Add migration guide entry ✅ 
@jwarmkessel @warmkesselj

Api client update apple pay

---

.github/workflows/release.yml

Move the cocoapods portion of the release to the last step. We’ve been seeing failures with this step recently and the reference docs are the step after. The reference docs are one of the mere tedious steps to release manually. Due to cocoapods being deprecated we can likely expect the cocapods portion of the release to fail more often (as we have seen). This allows us to hopefully have the least amount of steps to do manually if the release fails as cocoapods is often our failing step. We can then release cocoapods via the command line when we see these failures without also needing to do the reference docs.

Update Cocoapods to End of Release

---

Sources/BraintreeCore/BTAPIClient.swift
Sources/BraintreeCore/BTAPIClientHTTPType.swift
Sources/BraintreeCore/BTAppContextSwitchClient.swift
Sources/BraintreeCore/BTAppContextSwitcher.swift
Sources/BraintreeCore/BTClientMetadataIntegration.swift
Sources/BraintreeCore/BTClientMetadataSource.swift
Sources/BraintreeCore/BTCoreConstants.swift
Sources/BraintreeCore/BTJSON.swift
Sources/BraintreeCore/BTPaymentMethodNonce.swift
Sources/BraintreeCore/BTURLUtils.swift
Sources/BraintreeCore/Configuration/BTConfiguration.swift
UnitTests/BraintreeCoreTests/BTGraphQLHTTP_Tests.swift
UnitTests/BraintreeCoreTests/BTJSON_Tests.swift
UnitTests/BraintreeDataCollectorTests/BTDataCollector_Tests.swift

- Remove `@objc` annotations from several internal classes
- Remove and update related tests
- @agedd

[v7] Remove ObjC annotations from internal classes

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreePayPal/BTPayPalReturnURL.swift
Sources/BraintreeVenmo/BTVenmoAppSwitchReturnURL.swift
Sources/BraintreeVenmo/BTVenmoClient.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Fix bug where instantiating multiple feature clients with  universal links in the same view causes `handleOpen` to return in the wrong feature client
On main you can see this bug by adding the following in `PayPalWebCheckoutViewController` and tapping the app switch flow:
```swift
/// add under `lazy var payPalClient`
var venmoClient: BTVenmoClient?
/// add to `tappedPayPalAppSwitchForVault`
venmoClient = BTVenmoClient(
apiClient: apiClient,
// swiftlint:disable:next force_unwrapping
universalLink: URL(string: "https://mobile-sdk-demo-site-838cead5d3ab.herokuapp.com/braintree-payments")!
)
payPalClient.tokenize(request) { nonce, error in
...
```
If you add a breakpoint to `canHandleReturnURL` in `BTVenmoClient` you will see we hit that breakpoint but not the one in `BTPayPalClient`. …

Bug Fix: Universal Links in Same View

---

CHANGELOG.md
Demo/Application/Features/PayPalMessagingViewController.swift
SampleApps/CarthageTest/CarthageTest/ViewController.swift
SampleApps/SPMTest/SPMTest/ViewController.swift
Sources/BraintreePayPalMessaging/BTPayPalMessagingView.swift
UnitTests/BraintreePayPalMessagingTests/BTPayPalMessagingView_Tests.swift
V7_MIGRATION.md

- Update `BTPayPalMessagingView` with new `APIClient` pattern 
- @agedd

[v7] Update `BTPayPalMessagingView` with new `APIClient` pattern

---

README.md

SSL cert expiration date has been extended to March 30, 2026
- Updated README
- @stechiu

Changed SSL cert expiration date

---

.github/workflows/release.yml

- The release for v7 failed on the reference docs step because the GitHub action runner did not have the iPhone type being specified. This bumps to an iPhone 16 which is [supported on the runner](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md#installed-simulators) we are using.

[v7] Update `release.yml`

---

Braintree.podspec
Braintree.xcodeproj/project.pbxproj
Sources/BraintreeVenmo/BTVenmoClient.swift
Sources/BraintreeVenmo/Models/VenmoAccountsPOSTBody.swift
Sources/BraintreeVenmo/Models/VenmoCreatePaymentContextGraphQLBody.swift
Sources/BraintreeVenmo/Models/VenmoQueryPaymentContextGraphQLBody.swift

- Convert the following POST requests to Encodable for the Venmo flow:
- `VenmoAccountsPOSTBody`
- `VenmoCreatePaymentContextGraphQLBody`
- `VenmoQueryPaymentContextGraphQLBody`
🚀  **Note:** I used GitHub Copilot to help with some of this logic. While I did need to update some things to match our patterns and the expected Graph QL keys, it was helpful in generating some of the encodable boilerplate.
**Testing:** I have tested both the app switch and universal link fallback flow on device with these changes

[v7] Venmo GraphQL Encodable

---

Demo/Application/Features/PayPalWebCheckoutViewController.swift

- Update demo app for RBA metadata to work as expected when toggled on, we were previously getting an error because:
- `reloadThresholdAmount` cannot be used with the `. subscription` plan type
- we need at least 1 billing cycle for `. subscription` plan type so setting `isTrial` to false allows us to have one

[OPEN DEV] Fix RBA Metadata in Demo App

---

Sources/BraintreeCore/Analytics/AnalyticsSendable.swift
Sources/BraintreeCore/Analytics/BTAnalyticsService.swift
Sources/BraintreeCore/BTAPIClient.swift
UnitTests/BraintreeCoreTests/Analytics/BTAnalyticsService_Tests.swift
UnitTests/BraintreeCoreTests/Analytics/FakeAnalyticsService.swift

Updates the sendAnalyticsEventsImmediately method to leverage UIApplication.shared.beginBackgroundTask in order to ensure that analytics events are successfully delivered even if the app is transitioning to the background.
Key changes:
Wrapped the call to sendAnalyticEvent in a background task to extend the app’s execution time beyond the default 30 seconds allowed by the OS.
Ensured the background task is properly ended in all execution paths to avoid potential app termination.
The update follows Apple’s recommended pattern for background task usage and includes a fallback with MainActor.assumeIsolated to safely call endBackgroundTask.
This change improves the reliability of analytics delivery, especially in critical scenarios like app switch events that may occur just as the app is …

Remove analytics batching

---

Braintree.xcodeproj/project.pbxproj
Sources/BraintreeShopperInsights/BTCustomerRecommendationsAPI.swift
Sources/BraintreeShopperInsights/BTCustomerRecommendationsResult.swift
Sources/BraintreeShopperInsights/Models/CreateCustomerSessionMutationGraphQLBody.swift
Sources/BraintreeShopperInsights/Models/GenerateCustomerRecommendationsGraphQLBody.swift
Sources/BraintreeShopperInsights/Models/UpdateCustomerSessionMutationGraphQLBody.swift
Sources/BraintreeShopperInsights/Models/Variables.swift
UnitTests/BraintreeShopperInsightsTests/BTGenerateCustomerRecommendationAPI_Tests.swift
UnitTests/BraintreeShopperInsightsTests/BTUpdateCustomerSessionAPI_Tests.swift
UnitTests/BraintreeShopperInsightsTests/GenerateCustomerRecommendationsGraphQLBody_Tests.swift

- Add a new feature to generate customer recommendations using the `GenerateCustomerRecommendations` GraphQL mutation.
- Implement the `BTCustomerRecommendationsApi` class, its corresponding GraphQL POST body, and unit tests for both the class and model
- @agedd

Add GenerateCustomerRecommendations GraphQL Query

---

CHANGELOG.md
Sources/BraintreeShopperInsights/BTShopperInsightsClientV2.swift
UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClientV2_Tests.swift

- Add the `createCustomerSession` func to the `BTShopperInsightsClientV2` class
- ~[] Tested and confirmed payment flows affected by this change are functioning as expected~
- @agedd

Add  `createCustomerSession` function to BTShopperInsightsClientV2

---

CHANGELOG.md
Sources/BraintreeShopperInsights/BTShopperInsightsClientV2.swift
UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClientV2_Tests.swift

- Add the `updateCustomerSession` func to the `BTShopperInsightsClientV2` class
- @agedd

Add `updateCustomerSession` to the `ShopperInsightsClientV2`

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalAnalytics.swift
Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreePayPalTests/BTPayPalAnalytics_Tests.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

Introduces a new analytics event, `paypal:tokenize:browser-presentation:started`, to track when the `ASWebAuthenticationSession.start` is launched in the PayPal tokenization flow. 
* **Event added to changelog**: Documented the addition of the `paypal:tokenize:browser-presentation:started` event in `CHANGELOG.md`.
* **Constant definition**: Added `browserPresentationStarted` to the `BTPayPalAnalytics` enum in `Sources/BraintreePayPal/BTPayPalAnalytics.swift`.
* **Event handling in client**: Updated `BTPayPalClient.swift` to send the `browserPresentationStarted` analytics event when the browser presentation begins.
* **Analytics constant test**: Verified the `browserPresentationStarted` constant in `BTPayPalAnalytics_Tests.swift`.
* **Client behavior test**: Added a test in …

[Analytics] Add `browser-presentation:started` event

---

Sources/BraintreeShopperInsights/BTCreateCustomerSessionAPI.swift
Sources/BraintreeShopperInsights/BTCustomerRecommendationsAPI.swift
Sources/BraintreeShopperInsights/BTShopperInsightsAnalytics.swift
Sources/BraintreeShopperInsights/BTUpdateCustomerSessionAPI.swift
UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsAnalytics_Tests.swift
UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClientV2_Tests.swift
UnitTests/BraintreeTestShared/MockAPIClient.swift

- Add all the new events and sanity unit tests for events we want to send as part of Payment Ready v2
- @agedd

Add Payment Ready v2 Events

---

Sources/BraintreeCore/UIApplication+URLOpener.swift
Sources/BraintreePayPal/BTPayPalClient.swift
Sources/BraintreeVenmo/BTVenmoClient.swift
UnitTests/BraintreeTestShared/FakeApplication.swift
UnitTests/BraintreeVenmoTests/BTVenmoClient_Tests.swift

- Revert this override change needed when supporting older Xcode versions: https://github.com/braintree/braintree_ios/pull/1360#discussion_r1672339486

[v7] Revert Open Override

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

Updates the `BTPayPalClient` to include the `appSwitchURL` parameter in various analytics events.
* Added the `appSwitchURL` parameter to the `sendAnalyticsEvent` method for the following analytics events:
- `handleReturnStarted` to track the URL used during app switch return handling.
- `tokenizeDuplicateRequest` to track duplicate tokenization requests. [[1]](diffhunk://#diff-7593900bd413ee81d48fae61aeeab899a00cbfdc0d2a688e21d3acf3f7ef3360R465) [[2]](diffhunk://#diff-7593900bd413ee81d48fae61aeeab899a00cbfdc0d2a688e21d3acf3f7ef3360R596)
- `appSwitchStarted` to track the initiation of PayPal app switching.
- `browserPresentationSucceeded` and `browserPresentationFailed` to track the success or failure of browser presentation during PayPal interactions. …

[Analytics] URL FPTI Tag Updates

---

CHANGELOG.md
Sources/BraintreeCore/Analytics/FPTIBatchData.swift
UnitTests/BraintreeCoreTests/Analytics/FPTIBatchData_Tests.swift

**Note:** this work is going into a feature branch, once all changes are completed this will be verified and merged in with the appropriate teams. This is part of an alignment on the tags we pass to FPTI as well as some new tags and the same work being done on iOS will also be done on Android.
- Add `space_key` - this is a hardcoded value that represents the BT SDKs
- Verified this tag is now sent in FPTI
- Add unit test

[Analytics] Add Space Key

---

CHANGELOG.md
Sources/BraintreeCore/Analytics/FPTIBatchData.swift
UnitTests/BraintreeCoreTests/Analytics/FPTIBatchData_Tests.swift

**Note:** this work is going into a feature branch, once all changes are completed this will be verified and merged in with the appropriate teams. This is part of an alignment on the tags we pass to FPTI as well as some new tags and the same work being done on iOS will also be done on Android.
- Add `product_name` - this is a hardcoded value that represents the BT SDKs and is the value we were told to use for this change
- Verified this tag is now sent in FPTI
- Add unit test

[Analytics] Add Product Name

---

Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreeCoreTests/Analytics/FPTIBatchData_Tests.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

**Note:** this work is going into a feature branch, once all changes are completed this will be verified and merged in with the appropriate teams. This is part of an alignment on the tags we pass to FPTI as well as some new tags and the same work being done on iOS will also be done on Android.
- The values for context type should use dashes and not underscores

[Analytics] Correct Context Type Values

---

CHANGELOG.md
Demo/Application/Features/PayPalWebCheckoutViewController.swift
Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift

- Added new query parameters that will be required from the PayPal app switch universal link.
- Updated the Demo App so that we'd be able to test the Pay Later functionality.
> @nastassiarodzik
Pay later functionality on One time checkout flow:
https://github.com/user-attachments/assets/9ab4fe2f-9908-40e5-beaf-7ce725bc95b1

Add required query params

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalAccountNonce.swift
UnitTests/BraintreePayPalTests/BTPayPalAccountNonce_Tests.swift

- Add `paymentID` to `BTPayPalAccountNonce` - tested and verified we are getting this value as expected in sandbox
- Android PR: https://github.com/braintree/braintree_android/pull/1405

Feature: Add Payment ID to PayPal Nonce

---

Sources/BraintreePayPal/BTPayPalCheckoutRequest.swift
Sources/BraintreePayPal/BTPayPalVaultRequest.swift

* Updated the default value description for the `contactPreference` parameter to state it defaults to `.none` instead of `BTContactPreference.noContactInformation` in both `BTPayPalCheckoutRequest` initializers. [[1]](diffhunk://#diff-49e322ceda0295e096bd87fcbac95670577c9eb9ce74916c97faba40eee54195L104-R104) [[2]](diffhunk://#diff-49e322ceda0295e096bd87fcbac95670577c9eb9ce74916c97faba40eee54195L137-R142)
* Added missing periods at the end of parameter descriptions.
- @richherrera

[v7] PayPal Encodable

---

.github/workflows/release.yml

Recently we received the error `[!] The specified path Braintree.podspec does not point to an existing podspec file.` when doing releases. I think this is due to change in the runners where we are attempting to push the `Braintree.podspec` from the `gh-pages` branch previous to this step. This PR updated to stash and diff, checkout the release tag, then do `pod trunk push`. Hoping my theory is correct but no way to test until the next release. 😅 

[OPEN DEV] Update `release.yml` for Cocoapods

---

Sources/BraintreePayPal/Models/PayPalCheckoutPOSTBody.swift
Sources/BraintreePayPal/RecurringBillingMetadata/BTAmountBreakdown.swift
UnitTests/BraintreePayPalTests/BTPayPalCheckoutRequest_Tests.swift

Updates the PayPal Checkout integration to support additional recurring billing and amount breakdown features. 
Improve how amount breakdown data is encoded and tested.
* Added new fields to `PayPalCheckoutPOSTBody` for recurring billing: `recurringBillingDetails` and `recurringBillingPlanType`, enabling the request to carry plan metadata and type for subscriptions. These fields are now set from the request and mapped to their respective JSON keys.
* Introduced the `amountBreakdown` property in `PayPalCheckoutPOSTBody`, which is now populated from the request and encoded using the new `BTAmountBreakdown` model.
* Updated `BTAmountBreakdown` to conform to `Encodable`, added a `CodingKeys` enum for explicit JSON key mapping, and removed the manual `parameters()` method for a cleaner …

[v7] Checkout RBA Metadata

---

README.md

Updated README to include all the payment methods we offer.
- Updated README
- @stechiu

Update README to list all new payment methods

---

CHANGELOG.md
Sources/BraintreePayPal/BTPayPalAnalytics.swift
Sources/BraintreePayPal/BTPayPalClient.swift
UnitTests/BraintreePayPalTests/BTPayPalAnalytics_Tests.swift
UnitTests/BraintreePayPalTests/BTPayPalClient_Tests.swift
UnitTests/BraintreeTestShared/FakeApplication.swift

This PR updates the `v7` feature branch with the latest changes merged into `main`. The recent [AppSwitch instrumentation changes](https://github.com/braintree/braintree_ios/pull/1648) create a custom “open” API, but the goal in `v7` is to use the native API.
- @richherrera

[v7] AppSwitch Instrumentation
